// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: osi_datarecording.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { SensorData } from "./osi_sensordata";

/**
 * \brief (Time) Series of \c SensorData messages that may be used for data
 * recording or internal buffering by some sensor models.
 */
export interface SensorDataSeries {
  /** List of sensor data messages for subsequent time steps. */
  sensor_data: SensorData[];
}

/**
 * \brief List of sensors where each element contains a time series of
 * \c SensorData messages.
 */
export interface SensorDataSeriesList {
  /** List of sensor data for multiple sensors at subsequent time steps. */
  sensor: SensorDataSeries[];
}

function createBaseSensorDataSeries(): SensorDataSeries {
  return { sensor_data: [] };
}

export const SensorDataSeries: MessageFns<SensorDataSeries> = {
  encode(message: SensorDataSeries, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.sensor_data) {
      SensorData.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SensorDataSeries {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSensorDataSeries();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.sensor_data.push(SensorData.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SensorDataSeries {
    return {
      sensor_data: globalThis.Array.isArray(object?.sensor_data)
        ? object.sensor_data.map((e: any) => SensorData.fromJSON(e))
        : [],
    };
  },

  toJSON(message: SensorDataSeries): unknown {
    const obj: any = {};
    if (message.sensor_data?.length) {
      obj.sensor_data = message.sensor_data.map((e) => SensorData.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SensorDataSeries>, I>>(base?: I): SensorDataSeries {
    return SensorDataSeries.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SensorDataSeries>, I>>(object: I): SensorDataSeries {
    const message = createBaseSensorDataSeries();
    message.sensor_data = object.sensor_data?.map((e) => SensorData.fromPartial(e)) || [];
    return message;
  },
};

function createBaseSensorDataSeriesList(): SensorDataSeriesList {
  return { sensor: [] };
}

export const SensorDataSeriesList: MessageFns<SensorDataSeriesList> = {
  encode(message: SensorDataSeriesList, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.sensor) {
      SensorDataSeries.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SensorDataSeriesList {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSensorDataSeriesList();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.sensor.push(SensorDataSeries.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SensorDataSeriesList {
    return {
      sensor: globalThis.Array.isArray(object?.sensor)
        ? object.sensor.map((e: any) => SensorDataSeries.fromJSON(e))
        : [],
    };
  },

  toJSON(message: SensorDataSeriesList): unknown {
    const obj: any = {};
    if (message.sensor?.length) {
      obj.sensor = message.sensor.map((e) => SensorDataSeries.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SensorDataSeriesList>, I>>(base?: I): SensorDataSeriesList {
    return SensorDataSeriesList.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SensorDataSeriesList>, I>>(object: I): SensorDataSeriesList {
    const message = createBaseSensorDataSeriesList();
    message.sensor = object.sensor?.map((e) => SensorDataSeries.fromPartial(e)) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
