// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: osi_sensordata.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { BaseMoving, Identifier, MountingPosition, Polygon3d, Timestamp } from "./osi_common";
import { DetectedLane, DetectedLaneBoundary } from "./osi_detectedlane";
import { DetectedMovingObject, DetectedStationaryObject } from "./osi_detectedobject";
import { DetectedOccupant } from "./osi_detectedoccupant";
import { DetectedRoadMarking } from "./osi_detectedroadmarking";
import { DetectedTrafficLight } from "./osi_detectedtrafficlight";
import { DetectedTrafficSign } from "./osi_detectedtrafficsign";
import { FeatureData } from "./osi_featuredata";
import { LogicalDetectionData } from "./osi_logicaldetectiondata";
import { SensorView } from "./osi_sensorview";
import { InterfaceVersion } from "./osi_version";

/** \brief The header attributes of each detected entity. */
export interface DetectedEntityHeader {
  /**
   * Time stamp at which the measurement was taken (not the time at which it
   * was processed or at which it is transmitted) in the global synchronized
   * time.
   *
   * \note See \c SensorData::timestamp and \c
   * SensorData::last_measurement_time for detailed discussions on the
   * semantics of time-related fields.
   */
  measurement_time?:
    | Timestamp
    | undefined;
  /** Continuous up counter to identify the cycle. */
  cycle_counter?:
    | number
    | undefined;
  /**
   * Data Qualifier expresses to what extent the content of this event can be
   * relied on.
   */
  data_qualifier?: DetectedEntityHeader_DataQualifier | undefined;
}

/**
 * Data qualifier communicates the overall availability of the
 * interface.
 */
export enum DetectedEntityHeader_DataQualifier {
  /** DATA_QUALIFIER_UNKNOWN - Unknown (must not be used in ground truth). */
  DATA_QUALIFIER_UNKNOWN = 0,
  /** DATA_QUALIFIER_OTHER - Other (unspecified but known). */
  DATA_QUALIFIER_OTHER = 1,
  /** DATA_QUALIFIER_AVAILABLE - Data is available. */
  DATA_QUALIFIER_AVAILABLE = 2,
  /** DATA_QUALIFIER_AVAILABLE_REDUCED - Reduced data is available. */
  DATA_QUALIFIER_AVAILABLE_REDUCED = 3,
  /** DATA_QUALIFIER_NOT_AVAILABLE - Data is not available. */
  DATA_QUALIFIER_NOT_AVAILABLE = 4,
  /** DATA_QUALIFIER_BLINDNESS - Sensor is blind. */
  DATA_QUALIFIER_BLINDNESS = 5,
  /** DATA_QUALIFIER_TEMPORARY_AVAILABLE - Sensor temporary available. */
  DATA_QUALIFIER_TEMPORARY_AVAILABLE = 6,
}

export function detectedEntityHeader_DataQualifierFromJSON(object: any): DetectedEntityHeader_DataQualifier {
  switch (object) {
    case 0:
    case "DATA_QUALIFIER_UNKNOWN":
      return DetectedEntityHeader_DataQualifier.DATA_QUALIFIER_UNKNOWN;
    case 1:
    case "DATA_QUALIFIER_OTHER":
      return DetectedEntityHeader_DataQualifier.DATA_QUALIFIER_OTHER;
    case 2:
    case "DATA_QUALIFIER_AVAILABLE":
      return DetectedEntityHeader_DataQualifier.DATA_QUALIFIER_AVAILABLE;
    case 3:
    case "DATA_QUALIFIER_AVAILABLE_REDUCED":
      return DetectedEntityHeader_DataQualifier.DATA_QUALIFIER_AVAILABLE_REDUCED;
    case 4:
    case "DATA_QUALIFIER_NOT_AVAILABLE":
      return DetectedEntityHeader_DataQualifier.DATA_QUALIFIER_NOT_AVAILABLE;
    case 5:
    case "DATA_QUALIFIER_BLINDNESS":
      return DetectedEntityHeader_DataQualifier.DATA_QUALIFIER_BLINDNESS;
    case 6:
    case "DATA_QUALIFIER_TEMPORARY_AVAILABLE":
      return DetectedEntityHeader_DataQualifier.DATA_QUALIFIER_TEMPORARY_AVAILABLE;
    default:
      throw new globalThis.Error("Unrecognized enum value " + object + " for enum DetectedEntityHeader_DataQualifier");
  }
}

export function detectedEntityHeader_DataQualifierToJSON(object: DetectedEntityHeader_DataQualifier): string {
  switch (object) {
    case DetectedEntityHeader_DataQualifier.DATA_QUALIFIER_UNKNOWN:
      return "DATA_QUALIFIER_UNKNOWN";
    case DetectedEntityHeader_DataQualifier.DATA_QUALIFIER_OTHER:
      return "DATA_QUALIFIER_OTHER";
    case DetectedEntityHeader_DataQualifier.DATA_QUALIFIER_AVAILABLE:
      return "DATA_QUALIFIER_AVAILABLE";
    case DetectedEntityHeader_DataQualifier.DATA_QUALIFIER_AVAILABLE_REDUCED:
      return "DATA_QUALIFIER_AVAILABLE_REDUCED";
    case DetectedEntityHeader_DataQualifier.DATA_QUALIFIER_NOT_AVAILABLE:
      return "DATA_QUALIFIER_NOT_AVAILABLE";
    case DetectedEntityHeader_DataQualifier.DATA_QUALIFIER_BLINDNESS:
      return "DATA_QUALIFIER_BLINDNESS";
    case DetectedEntityHeader_DataQualifier.DATA_QUALIFIER_TEMPORARY_AVAILABLE:
      return "DATA_QUALIFIER_TEMPORARY_AVAILABLE";
    default:
      throw new globalThis.Error("Unrecognized enum value " + object + " for enum DetectedEntityHeader_DataQualifier");
  }
}

/**
 * \brief The sensor information derived from \c GroundTruth and processed by
 * sensor-models.
 *
 * The sensor information is supposed to imitate the output of real sensors.
 * All information regarding the environment is given with respect to
 * the virtual sensor coordinate system specified in
 * \c SensorData::mounting_position, except for feature data, which is given
 * with respect to the physical sensor coordinate system specified in the
 * corresponding physical sensor's coordinate system.
 *
 * When simulating multiple distinct sensors, each sensor can produce an
 * individual copy of the \c SensorData interface. This allows an independent
 * treatment of the sensors.
 *
 * Sensor fusion models can consolidate multiple \c SensorData interfaces into
 * one consolidated \c SensorData interface.  This can happen either in
 * separate logical models, consuming and producing \c SensorData interfaces,
 * or it can happen as part of a combined sensor/logical model, that consumes
 * \c SensorView interfaces and directly produces one consolidated \c SensorData
 * output.
 */
export interface SensorData {
  /**
   * The interface version used by the sender.
   *
   * \rules
   * is_set
   * \endrules
   */
  version?:
    | InterfaceVersion
    | undefined;
  /**
   * The timestamp of the sensor data. Zero time is arbitrary but must be
   * identical for all messages. Zero time does not need to coincide with
   * the unix epoch. Recommended is the starting time point of the
   * simulation.
   *
   * \note This is the point in time that the sensor data message becomes
   * available to the rest of the system (i.e. the driving functions), so
   * it corresponds with the sending time and thus takes the latency of
   * internal processing of the sensor into account. Latencies of bus
   * communications, etc., that occur after the sensor output have to be
   * applied on top of this, if needed.
   *
   * The time that the actual measurement was performed (which will usually
   * correspond with the timestamp of the \c GroundTruth the sensor model
   * processed to arrive at these results) can be found in the additional
   * field \c SensorData::last_measurement_time.
   *
   * For an ideal zero latency sensor the two timestamps would be the same
   * and would correspond with the timestamp from the current \c GroundTruth
   * message.
   *
   * For a sensor model that does not know its own internal latencies (e.g.
   * a dumb sensor with no internal time concept), the two timestamps might
   * also be identical, but delayed from the \c GroundTruth timestamp.
   *
   * \rules
   * is_set
   * \endrules
   */
  timestamp?:
    | Timestamp
    | undefined;
  /**
   * The sensors estimated location of the host vehicle
   *
   * \note This value is only set by sensors that are able to
   * provide an own estimation of the host vehicle location.
   * \note Note that dimension and base_polygon need not be set.
   * \note The parent frame of \c host_vehicle_location is the sensor frame.
   */
  host_vehicle_location?:
    | BaseMoving
    | undefined;
  /**
   * The sensors estimated location error of the host vehicle
   *
   * \note This value is only set by sensors that are able to
   * provide an own estimation of the host vehicle location.
   * \note Note that dimension and base_polygon need not be set.
   * \note The parent frame of \c host_vehicle_location_rmse is the sensor
   * frame.
   */
  host_vehicle_location_rmse?:
    | BaseMoving
    | undefined;
  /**
   * The ID of the sensor at host vehicle's mounting_position.
   *
   * This is the ID of the virtual sensor, to be used in its detected
   * object output; it is distinct from the IDs of its physical detectors,
   * which are used in the detected features.
   *
   * \rules
   * is_set
   * \endrules
   */
  sensor_id?:
    | Identifier
    | undefined;
  /**
   * The virtual mounting position of the sensor (origin and orientation
   * of the sensor coordinate system) given in vehicle coordinates [1].
   * The virtual position pertains to the sensor as a whole, regardless
   * of the actual position of individual physical detectors, and governs
   * the sensor-relative coordinates in detected objects of the sensor
   * as a whole.  Individual features detected by individual physical
   * detectors are governed by the actual physical mounting positions
   * of the detectors, as indicated in the technology-specific sub-views
   * and sub-view configurations.
   *
   * \arg \b x-direction of sensor coordinate system: sensor viewing direction
   * \arg \b z-direction of sensor coordinate system: sensor (up)
   * \arg \b y-direction of sensor coordinate system: perpendicular to x and z
   * right hand system
   *
   * \par Reference:
   * [1] DIN Deutsches Institut fuer Normung e. V. (2013). <em>DIN ISO 8855 Strassenfahrzeuge - Fahrzeugdynamik und Fahrverhalten - Begriffe</em>. (DIN ISO 8855:2013-11). Berlin, Germany.
   *
   * \note This field is usually static during the simulation.
   * \note The origin of vehicle's coordinate system in world frame is
   * ( \c MovingObject::base . \c BaseMoving::position +
   * Inverse_Rotation_yaw_pitch_roll( \c MovingObject::base . \c
   * BaseMoving::orientation) * \c
   * MovingObject::VehicleAttributes::bbcenter_to_rear) . The orientation of
   * the vehicle's coordinate system is equal to the orientation of the
   * vehicle's bounding box \c MovingObject::base . \c
   * BaseMoving::orientation.
   *
   * \rules
   * is_set
   * \endrules
   */
  mounting_position?:
    | MountingPosition
    | undefined;
  /** The root mean squared error of the mounting position. */
  mounting_position_rmse?:
    | MountingPosition
    | undefined;
  /**
   * Sensor view w.r.t. the sensor coordinate system
   *
   * This provides a copy of the \c SensorView data received by the sensor
   * for reference purposes.  For complex sensors or logic models this
   * can be multiple copies.
   */
  sensor_view: SensorView[];
  /**
   * The timestamp of the last real-world measurement (e.g. GT input) that
   * this set of sensor data takes into account. This in effect is the last
   * time instance of reality the measurements correspond to. See field
   * \c SensorData::timestamp for a detailed discussion. This value is also
   * the upper bound to the \c DetectedEntityHeader::measurement_time and the
   * feature data \c SensorDetectionHeader::measurement_time fields.
   */
  last_measurement_time?:
    | Timestamp
    | undefined;
  /** General information about the \c DetectedStationaryObject . */
  stationary_object_header?:
    | DetectedEntityHeader
    | undefined;
  /** The list of stationary objects (e.g. landmarks) detected by the sensor. */
  stationary_object: DetectedStationaryObject[];
  /** General information about the \c DetectedMovingObject . */
  moving_object_header?:
    | DetectedEntityHeader
    | undefined;
  /**
   * The list of moving objects detected by the sensor as perceived by
   * the sensor.
   */
  moving_object: DetectedMovingObject[];
  /** General information about the \c DetectedTrafficSign . */
  traffic_sign_header?:
    | DetectedEntityHeader
    | undefined;
  /** The list of traffic signs detected by the sensor. */
  traffic_sign: DetectedTrafficSign[];
  /** General information about the \c DetectedTrafficLight . */
  traffic_light_header?:
    | DetectedEntityHeader
    | undefined;
  /** The list of traffic lights detected by the sensor. */
  traffic_light: DetectedTrafficLight[];
  /** General information about the \c DetectedRoadMarking . */
  road_marking_header?:
    | DetectedEntityHeader
    | undefined;
  /**
   * The list of road markings detected by the sensor.
   * This excludes lane boundary markings.
   */
  road_marking: DetectedRoadMarking[];
  /** General information about the \c DetectedLaneBoundary . */
  lane_boundary_header?:
    | DetectedEntityHeader
    | undefined;
  /** The list of lane boundary markings detected by the sensor. */
  lane_boundary: DetectedLaneBoundary[];
  /** General information about the \c DetectedLane . */
  lane_header?:
    | DetectedEntityHeader
    | undefined;
  /** The list of lanes detected by the sensor */
  lane: DetectedLane[];
  /** General information about the \c DetectedOccupant . */
  occupant_header?:
    | DetectedEntityHeader
    | undefined;
  /** The list of occupants of the host vehicle */
  occupant: DetectedOccupant[];
  /**
   * Low level feature data interface.
   *
   * Low Level feature data is optionally provided by sensor models that
   * model sensors giving access to this low level data, i.e. data prior to
   * object hypothesis and tracking.
   */
  feature_data?:
    | FeatureData
    | undefined;
  /**
   * Logical detection data interface.
   *
   * Logical detection data are provided by a transformation
   * (and optional sensor fusion)
   * performed by a sensor model or a logical model
   * that fuses multiple sensors and/or sensor types
   * into a single reference frame
   * of the so called logical/virtual sensor.
   * Therefore, all information is given with respect to
   * the reference frame of the logical/virtual sensor
   * \c SensorView::mounting_position (e.g. center of rear axle of the ego car)
   * in cartesian coordinates.
   */
  logical_detection_data?:
    | LogicalDetectionData
    | undefined;
  /** Virtual detection area of the sensor */
  virtual_detection_area?:
    | SensorData_VirtualDetectionArea
    | undefined;
  /**
   * The system time of the modeled source of the sensor data, given
   * in UTC (Unix Epoch timestamp).
   *
   * The system time can be used to transmit the internal time of the
   * simulated component that supplies the sensor data, which might
   * not coincide with the simulation time as transmitted in the
   * timestamp field. Example use cases include recorded data traces
   * or the simulation of time synchronization mechanisms and errors.
   */
  system_time?: Timestamp | undefined;
}

/**
 * \brief Virtual detection area of a sensor
 *
 * The virtual detection area describes the nominal area the sensor is capable of covering
 * in its current operating mode, without taking occlusion or other statistical effects into account.
 * This information can be used for visualization or other development purposes as a rough guide
 * to nominal sensor performance.
 *
 * It is described by a set of polygons in cartesian coordinates as a pragmatic approximation for
 * the rough shapes expected.
 */
export interface SensorData_VirtualDetectionArea {
  /**
   * List of polygons. Each polygon represents a surface of the virtual detection area
   * and is given with respect to the virtual sensor coordinate system.
   */
  polygon: Polygon3d[];
}

function createBaseDetectedEntityHeader(): DetectedEntityHeader {
  return { measurement_time: undefined, cycle_counter: 0, data_qualifier: 0 };
}

export const DetectedEntityHeader: MessageFns<DetectedEntityHeader> = {
  encode(message: DetectedEntityHeader, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.measurement_time !== undefined) {
      Timestamp.encode(message.measurement_time, writer.uint32(10).fork()).join();
    }
    if (message.cycle_counter !== undefined && message.cycle_counter !== 0) {
      writer.uint32(16).uint64(message.cycle_counter);
    }
    if (message.data_qualifier !== undefined && message.data_qualifier !== 0) {
      writer.uint32(24).int32(message.data_qualifier);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DetectedEntityHeader {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDetectedEntityHeader();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.measurement_time = Timestamp.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.cycle_counter = longToNumber(reader.uint64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.data_qualifier = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DetectedEntityHeader {
    return {
      measurement_time: isSet(object.measurement_time) ? Timestamp.fromJSON(object.measurement_time) : undefined,
      cycle_counter: isSet(object.cycle_counter) ? globalThis.Number(object.cycle_counter) : 0,
      data_qualifier: isSet(object.data_qualifier)
        ? detectedEntityHeader_DataQualifierFromJSON(object.data_qualifier)
        : 0,
    };
  },

  toJSON(message: DetectedEntityHeader): unknown {
    const obj: any = {};
    if (message.measurement_time !== undefined) {
      obj.measurement_time = Timestamp.toJSON(message.measurement_time);
    }
    if (message.cycle_counter !== undefined) {
      obj.cycle_counter = Math.round(message.cycle_counter);
    }
    if (message.data_qualifier !== undefined) {
      obj.data_qualifier = detectedEntityHeader_DataQualifierToJSON(message.data_qualifier);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DetectedEntityHeader>, I>>(base?: I): DetectedEntityHeader {
    return DetectedEntityHeader.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DetectedEntityHeader>, I>>(object: I): DetectedEntityHeader {
    const message = createBaseDetectedEntityHeader();
    message.measurement_time = (object.measurement_time !== undefined && object.measurement_time !== null)
      ? Timestamp.fromPartial(object.measurement_time)
      : undefined;
    message.cycle_counter = object.cycle_counter ?? 0;
    message.data_qualifier = object.data_qualifier ?? 0;
    return message;
  },
};

function createBaseSensorData(): SensorData {
  return {
    version: undefined,
    timestamp: undefined,
    host_vehicle_location: undefined,
    host_vehicle_location_rmse: undefined,
    sensor_id: undefined,
    mounting_position: undefined,
    mounting_position_rmse: undefined,
    sensor_view: [],
    last_measurement_time: undefined,
    stationary_object_header: undefined,
    stationary_object: [],
    moving_object_header: undefined,
    moving_object: [],
    traffic_sign_header: undefined,
    traffic_sign: [],
    traffic_light_header: undefined,
    traffic_light: [],
    road_marking_header: undefined,
    road_marking: [],
    lane_boundary_header: undefined,
    lane_boundary: [],
    lane_header: undefined,
    lane: [],
    occupant_header: undefined,
    occupant: [],
    feature_data: undefined,
    logical_detection_data: undefined,
    virtual_detection_area: undefined,
    system_time: undefined,
  };
}

export const SensorData: MessageFns<SensorData> = {
  encode(message: SensorData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.version !== undefined) {
      InterfaceVersion.encode(message.version, writer.uint32(10).fork()).join();
    }
    if (message.timestamp !== undefined) {
      Timestamp.encode(message.timestamp, writer.uint32(18).fork()).join();
    }
    if (message.host_vehicle_location !== undefined) {
      BaseMoving.encode(message.host_vehicle_location, writer.uint32(26).fork()).join();
    }
    if (message.host_vehicle_location_rmse !== undefined) {
      BaseMoving.encode(message.host_vehicle_location_rmse, writer.uint32(34).fork()).join();
    }
    if (message.sensor_id !== undefined) {
      Identifier.encode(message.sensor_id, writer.uint32(42).fork()).join();
    }
    if (message.mounting_position !== undefined) {
      MountingPosition.encode(message.mounting_position, writer.uint32(50).fork()).join();
    }
    if (message.mounting_position_rmse !== undefined) {
      MountingPosition.encode(message.mounting_position_rmse, writer.uint32(58).fork()).join();
    }
    for (const v of message.sensor_view) {
      SensorView.encode(v!, writer.uint32(66).fork()).join();
    }
    if (message.last_measurement_time !== undefined) {
      Timestamp.encode(message.last_measurement_time, writer.uint32(74).fork()).join();
    }
    if (message.stationary_object_header !== undefined) {
      DetectedEntityHeader.encode(message.stationary_object_header, writer.uint32(82).fork()).join();
    }
    for (const v of message.stationary_object) {
      DetectedStationaryObject.encode(v!, writer.uint32(90).fork()).join();
    }
    if (message.moving_object_header !== undefined) {
      DetectedEntityHeader.encode(message.moving_object_header, writer.uint32(98).fork()).join();
    }
    for (const v of message.moving_object) {
      DetectedMovingObject.encode(v!, writer.uint32(106).fork()).join();
    }
    if (message.traffic_sign_header !== undefined) {
      DetectedEntityHeader.encode(message.traffic_sign_header, writer.uint32(114).fork()).join();
    }
    for (const v of message.traffic_sign) {
      DetectedTrafficSign.encode(v!, writer.uint32(122).fork()).join();
    }
    if (message.traffic_light_header !== undefined) {
      DetectedEntityHeader.encode(message.traffic_light_header, writer.uint32(130).fork()).join();
    }
    for (const v of message.traffic_light) {
      DetectedTrafficLight.encode(v!, writer.uint32(138).fork()).join();
    }
    if (message.road_marking_header !== undefined) {
      DetectedEntityHeader.encode(message.road_marking_header, writer.uint32(146).fork()).join();
    }
    for (const v of message.road_marking) {
      DetectedRoadMarking.encode(v!, writer.uint32(154).fork()).join();
    }
    if (message.lane_boundary_header !== undefined) {
      DetectedEntityHeader.encode(message.lane_boundary_header, writer.uint32(162).fork()).join();
    }
    for (const v of message.lane_boundary) {
      DetectedLaneBoundary.encode(v!, writer.uint32(170).fork()).join();
    }
    if (message.lane_header !== undefined) {
      DetectedEntityHeader.encode(message.lane_header, writer.uint32(178).fork()).join();
    }
    for (const v of message.lane) {
      DetectedLane.encode(v!, writer.uint32(186).fork()).join();
    }
    if (message.occupant_header !== undefined) {
      DetectedEntityHeader.encode(message.occupant_header, writer.uint32(194).fork()).join();
    }
    for (const v of message.occupant) {
      DetectedOccupant.encode(v!, writer.uint32(202).fork()).join();
    }
    if (message.feature_data !== undefined) {
      FeatureData.encode(message.feature_data, writer.uint32(210).fork()).join();
    }
    if (message.logical_detection_data !== undefined) {
      LogicalDetectionData.encode(message.logical_detection_data, writer.uint32(218).fork()).join();
    }
    if (message.virtual_detection_area !== undefined) {
      SensorData_VirtualDetectionArea.encode(message.virtual_detection_area, writer.uint32(226).fork()).join();
    }
    if (message.system_time !== undefined) {
      Timestamp.encode(message.system_time, writer.uint32(234).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SensorData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSensorData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.version = InterfaceVersion.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.timestamp = Timestamp.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.host_vehicle_location = BaseMoving.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.host_vehicle_location_rmse = BaseMoving.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.sensor_id = Identifier.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.mounting_position = MountingPosition.decode(reader, reader.uint32());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.mounting_position_rmse = MountingPosition.decode(reader, reader.uint32());
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.sensor_view.push(SensorView.decode(reader, reader.uint32()));
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.last_measurement_time = Timestamp.decode(reader, reader.uint32());
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.stationary_object_header = DetectedEntityHeader.decode(reader, reader.uint32());
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.stationary_object.push(DetectedStationaryObject.decode(reader, reader.uint32()));
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.moving_object_header = DetectedEntityHeader.decode(reader, reader.uint32());
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.moving_object.push(DetectedMovingObject.decode(reader, reader.uint32()));
          continue;
        }
        case 14: {
          if (tag !== 114) {
            break;
          }

          message.traffic_sign_header = DetectedEntityHeader.decode(reader, reader.uint32());
          continue;
        }
        case 15: {
          if (tag !== 122) {
            break;
          }

          message.traffic_sign.push(DetectedTrafficSign.decode(reader, reader.uint32()));
          continue;
        }
        case 16: {
          if (tag !== 130) {
            break;
          }

          message.traffic_light_header = DetectedEntityHeader.decode(reader, reader.uint32());
          continue;
        }
        case 17: {
          if (tag !== 138) {
            break;
          }

          message.traffic_light.push(DetectedTrafficLight.decode(reader, reader.uint32()));
          continue;
        }
        case 18: {
          if (tag !== 146) {
            break;
          }

          message.road_marking_header = DetectedEntityHeader.decode(reader, reader.uint32());
          continue;
        }
        case 19: {
          if (tag !== 154) {
            break;
          }

          message.road_marking.push(DetectedRoadMarking.decode(reader, reader.uint32()));
          continue;
        }
        case 20: {
          if (tag !== 162) {
            break;
          }

          message.lane_boundary_header = DetectedEntityHeader.decode(reader, reader.uint32());
          continue;
        }
        case 21: {
          if (tag !== 170) {
            break;
          }

          message.lane_boundary.push(DetectedLaneBoundary.decode(reader, reader.uint32()));
          continue;
        }
        case 22: {
          if (tag !== 178) {
            break;
          }

          message.lane_header = DetectedEntityHeader.decode(reader, reader.uint32());
          continue;
        }
        case 23: {
          if (tag !== 186) {
            break;
          }

          message.lane.push(DetectedLane.decode(reader, reader.uint32()));
          continue;
        }
        case 24: {
          if (tag !== 194) {
            break;
          }

          message.occupant_header = DetectedEntityHeader.decode(reader, reader.uint32());
          continue;
        }
        case 25: {
          if (tag !== 202) {
            break;
          }

          message.occupant.push(DetectedOccupant.decode(reader, reader.uint32()));
          continue;
        }
        case 26: {
          if (tag !== 210) {
            break;
          }

          message.feature_data = FeatureData.decode(reader, reader.uint32());
          continue;
        }
        case 27: {
          if (tag !== 218) {
            break;
          }

          message.logical_detection_data = LogicalDetectionData.decode(reader, reader.uint32());
          continue;
        }
        case 28: {
          if (tag !== 226) {
            break;
          }

          message.virtual_detection_area = SensorData_VirtualDetectionArea.decode(reader, reader.uint32());
          continue;
        }
        case 29: {
          if (tag !== 234) {
            break;
          }

          message.system_time = Timestamp.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SensorData {
    return {
      version: isSet(object.version) ? InterfaceVersion.fromJSON(object.version) : undefined,
      timestamp: isSet(object.timestamp) ? Timestamp.fromJSON(object.timestamp) : undefined,
      host_vehicle_location: isSet(object.host_vehicle_location)
        ? BaseMoving.fromJSON(object.host_vehicle_location)
        : undefined,
      host_vehicle_location_rmse: isSet(object.host_vehicle_location_rmse)
        ? BaseMoving.fromJSON(object.host_vehicle_location_rmse)
        : undefined,
      sensor_id: isSet(object.sensor_id) ? Identifier.fromJSON(object.sensor_id) : undefined,
      mounting_position: isSet(object.mounting_position)
        ? MountingPosition.fromJSON(object.mounting_position)
        : undefined,
      mounting_position_rmse: isSet(object.mounting_position_rmse)
        ? MountingPosition.fromJSON(object.mounting_position_rmse)
        : undefined,
      sensor_view: globalThis.Array.isArray(object?.sensor_view)
        ? object.sensor_view.map((e: any) => SensorView.fromJSON(e))
        : [],
      last_measurement_time: isSet(object.last_measurement_time)
        ? Timestamp.fromJSON(object.last_measurement_time)
        : undefined,
      stationary_object_header: isSet(object.stationary_object_header)
        ? DetectedEntityHeader.fromJSON(object.stationary_object_header)
        : undefined,
      stationary_object: globalThis.Array.isArray(object?.stationary_object)
        ? object.stationary_object.map((e: any) => DetectedStationaryObject.fromJSON(e))
        : [],
      moving_object_header: isSet(object.moving_object_header)
        ? DetectedEntityHeader.fromJSON(object.moving_object_header)
        : undefined,
      moving_object: globalThis.Array.isArray(object?.moving_object)
        ? object.moving_object.map((e: any) => DetectedMovingObject.fromJSON(e))
        : [],
      traffic_sign_header: isSet(object.traffic_sign_header)
        ? DetectedEntityHeader.fromJSON(object.traffic_sign_header)
        : undefined,
      traffic_sign: globalThis.Array.isArray(object?.traffic_sign)
        ? object.traffic_sign.map((e: any) => DetectedTrafficSign.fromJSON(e))
        : [],
      traffic_light_header: isSet(object.traffic_light_header)
        ? DetectedEntityHeader.fromJSON(object.traffic_light_header)
        : undefined,
      traffic_light: globalThis.Array.isArray(object?.traffic_light)
        ? object.traffic_light.map((e: any) => DetectedTrafficLight.fromJSON(e))
        : [],
      road_marking_header: isSet(object.road_marking_header)
        ? DetectedEntityHeader.fromJSON(object.road_marking_header)
        : undefined,
      road_marking: globalThis.Array.isArray(object?.road_marking)
        ? object.road_marking.map((e: any) => DetectedRoadMarking.fromJSON(e))
        : [],
      lane_boundary_header: isSet(object.lane_boundary_header)
        ? DetectedEntityHeader.fromJSON(object.lane_boundary_header)
        : undefined,
      lane_boundary: globalThis.Array.isArray(object?.lane_boundary)
        ? object.lane_boundary.map((e: any) => DetectedLaneBoundary.fromJSON(e))
        : [],
      lane_header: isSet(object.lane_header) ? DetectedEntityHeader.fromJSON(object.lane_header) : undefined,
      lane: globalThis.Array.isArray(object?.lane)
        ? object.lane.map((e: any) => DetectedLane.fromJSON(e))
        : [],
      occupant_header: isSet(object.occupant_header)
        ? DetectedEntityHeader.fromJSON(object.occupant_header)
        : undefined,
      occupant: globalThis.Array.isArray(object?.occupant)
        ? object.occupant.map((e: any) => DetectedOccupant.fromJSON(e))
        : [],
      feature_data: isSet(object.feature_data) ? FeatureData.fromJSON(object.feature_data) : undefined,
      logical_detection_data: isSet(object.logical_detection_data)
        ? LogicalDetectionData.fromJSON(object.logical_detection_data)
        : undefined,
      virtual_detection_area: isSet(object.virtual_detection_area)
        ? SensorData_VirtualDetectionArea.fromJSON(object.virtual_detection_area)
        : undefined,
      system_time: isSet(object.system_time) ? Timestamp.fromJSON(object.system_time) : undefined,
    };
  },

  toJSON(message: SensorData): unknown {
    const obj: any = {};
    if (message.version !== undefined) {
      obj.version = InterfaceVersion.toJSON(message.version);
    }
    if (message.timestamp !== undefined) {
      obj.timestamp = Timestamp.toJSON(message.timestamp);
    }
    if (message.host_vehicle_location !== undefined) {
      obj.host_vehicle_location = BaseMoving.toJSON(message.host_vehicle_location);
    }
    if (message.host_vehicle_location_rmse !== undefined) {
      obj.host_vehicle_location_rmse = BaseMoving.toJSON(message.host_vehicle_location_rmse);
    }
    if (message.sensor_id !== undefined) {
      obj.sensor_id = Identifier.toJSON(message.sensor_id);
    }
    if (message.mounting_position !== undefined) {
      obj.mounting_position = MountingPosition.toJSON(message.mounting_position);
    }
    if (message.mounting_position_rmse !== undefined) {
      obj.mounting_position_rmse = MountingPosition.toJSON(message.mounting_position_rmse);
    }
    if (message.sensor_view?.length) {
      obj.sensor_view = message.sensor_view.map((e) => SensorView.toJSON(e));
    }
    if (message.last_measurement_time !== undefined) {
      obj.last_measurement_time = Timestamp.toJSON(message.last_measurement_time);
    }
    if (message.stationary_object_header !== undefined) {
      obj.stationary_object_header = DetectedEntityHeader.toJSON(message.stationary_object_header);
    }
    if (message.stationary_object?.length) {
      obj.stationary_object = message.stationary_object.map((e) => DetectedStationaryObject.toJSON(e));
    }
    if (message.moving_object_header !== undefined) {
      obj.moving_object_header = DetectedEntityHeader.toJSON(message.moving_object_header);
    }
    if (message.moving_object?.length) {
      obj.moving_object = message.moving_object.map((e) => DetectedMovingObject.toJSON(e));
    }
    if (message.traffic_sign_header !== undefined) {
      obj.traffic_sign_header = DetectedEntityHeader.toJSON(message.traffic_sign_header);
    }
    if (message.traffic_sign?.length) {
      obj.traffic_sign = message.traffic_sign.map((e) => DetectedTrafficSign.toJSON(e));
    }
    if (message.traffic_light_header !== undefined) {
      obj.traffic_light_header = DetectedEntityHeader.toJSON(message.traffic_light_header);
    }
    if (message.traffic_light?.length) {
      obj.traffic_light = message.traffic_light.map((e) => DetectedTrafficLight.toJSON(e));
    }
    if (message.road_marking_header !== undefined) {
      obj.road_marking_header = DetectedEntityHeader.toJSON(message.road_marking_header);
    }
    if (message.road_marking?.length) {
      obj.road_marking = message.road_marking.map((e) => DetectedRoadMarking.toJSON(e));
    }
    if (message.lane_boundary_header !== undefined) {
      obj.lane_boundary_header = DetectedEntityHeader.toJSON(message.lane_boundary_header);
    }
    if (message.lane_boundary?.length) {
      obj.lane_boundary = message.lane_boundary.map((e) => DetectedLaneBoundary.toJSON(e));
    }
    if (message.lane_header !== undefined) {
      obj.lane_header = DetectedEntityHeader.toJSON(message.lane_header);
    }
    if (message.lane?.length) {
      obj.lane = message.lane.map((e) => DetectedLane.toJSON(e));
    }
    if (message.occupant_header !== undefined) {
      obj.occupant_header = DetectedEntityHeader.toJSON(message.occupant_header);
    }
    if (message.occupant?.length) {
      obj.occupant = message.occupant.map((e) => DetectedOccupant.toJSON(e));
    }
    if (message.feature_data !== undefined) {
      obj.feature_data = FeatureData.toJSON(message.feature_data);
    }
    if (message.logical_detection_data !== undefined) {
      obj.logical_detection_data = LogicalDetectionData.toJSON(message.logical_detection_data);
    }
    if (message.virtual_detection_area !== undefined) {
      obj.virtual_detection_area = SensorData_VirtualDetectionArea.toJSON(message.virtual_detection_area);
    }
    if (message.system_time !== undefined) {
      obj.system_time = Timestamp.toJSON(message.system_time);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SensorData>, I>>(base?: I): SensorData {
    return SensorData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SensorData>, I>>(object: I): SensorData {
    const message = createBaseSensorData();
    message.version = (object.version !== undefined && object.version !== null)
      ? InterfaceVersion.fromPartial(object.version)
      : undefined;
    message.timestamp = (object.timestamp !== undefined && object.timestamp !== null)
      ? Timestamp.fromPartial(object.timestamp)
      : undefined;
    message.host_vehicle_location =
      (object.host_vehicle_location !== undefined && object.host_vehicle_location !== null)
        ? BaseMoving.fromPartial(object.host_vehicle_location)
        : undefined;
    message.host_vehicle_location_rmse =
      (object.host_vehicle_location_rmse !== undefined && object.host_vehicle_location_rmse !== null)
        ? BaseMoving.fromPartial(object.host_vehicle_location_rmse)
        : undefined;
    message.sensor_id = (object.sensor_id !== undefined && object.sensor_id !== null)
      ? Identifier.fromPartial(object.sensor_id)
      : undefined;
    message.mounting_position = (object.mounting_position !== undefined && object.mounting_position !== null)
      ? MountingPosition.fromPartial(object.mounting_position)
      : undefined;
    message.mounting_position_rmse =
      (object.mounting_position_rmse !== undefined && object.mounting_position_rmse !== null)
        ? MountingPosition.fromPartial(object.mounting_position_rmse)
        : undefined;
    message.sensor_view = object.sensor_view?.map((e) => SensorView.fromPartial(e)) || [];
    message.last_measurement_time =
      (object.last_measurement_time !== undefined && object.last_measurement_time !== null)
        ? Timestamp.fromPartial(object.last_measurement_time)
        : undefined;
    message.stationary_object_header =
      (object.stationary_object_header !== undefined && object.stationary_object_header !== null)
        ? DetectedEntityHeader.fromPartial(object.stationary_object_header)
        : undefined;
    message.stationary_object = object.stationary_object?.map((e) => DetectedStationaryObject.fromPartial(e)) || [];
    message.moving_object_header = (object.moving_object_header !== undefined && object.moving_object_header !== null)
      ? DetectedEntityHeader.fromPartial(object.moving_object_header)
      : undefined;
    message.moving_object = object.moving_object?.map((e) => DetectedMovingObject.fromPartial(e)) || [];
    message.traffic_sign_header = (object.traffic_sign_header !== undefined && object.traffic_sign_header !== null)
      ? DetectedEntityHeader.fromPartial(object.traffic_sign_header)
      : undefined;
    message.traffic_sign = object.traffic_sign?.map((e) => DetectedTrafficSign.fromPartial(e)) || [];
    message.traffic_light_header = (object.traffic_light_header !== undefined && object.traffic_light_header !== null)
      ? DetectedEntityHeader.fromPartial(object.traffic_light_header)
      : undefined;
    message.traffic_light = object.traffic_light?.map((e) => DetectedTrafficLight.fromPartial(e)) || [];
    message.road_marking_header = (object.road_marking_header !== undefined && object.road_marking_header !== null)
      ? DetectedEntityHeader.fromPartial(object.road_marking_header)
      : undefined;
    message.road_marking = object.road_marking?.map((e) => DetectedRoadMarking.fromPartial(e)) || [];
    message.lane_boundary_header = (object.lane_boundary_header !== undefined && object.lane_boundary_header !== null)
      ? DetectedEntityHeader.fromPartial(object.lane_boundary_header)
      : undefined;
    message.lane_boundary = object.lane_boundary?.map((e) => DetectedLaneBoundary.fromPartial(e)) || [];
    message.lane_header = (object.lane_header !== undefined && object.lane_header !== null)
      ? DetectedEntityHeader.fromPartial(object.lane_header)
      : undefined;
    message.lane = object.lane?.map((e) => DetectedLane.fromPartial(e)) || [];
    message.occupant_header = (object.occupant_header !== undefined && object.occupant_header !== null)
      ? DetectedEntityHeader.fromPartial(object.occupant_header)
      : undefined;
    message.occupant = object.occupant?.map((e) => DetectedOccupant.fromPartial(e)) || [];
    message.feature_data = (object.feature_data !== undefined && object.feature_data !== null)
      ? FeatureData.fromPartial(object.feature_data)
      : undefined;
    message.logical_detection_data =
      (object.logical_detection_data !== undefined && object.logical_detection_data !== null)
        ? LogicalDetectionData.fromPartial(object.logical_detection_data)
        : undefined;
    message.virtual_detection_area =
      (object.virtual_detection_area !== undefined && object.virtual_detection_area !== null)
        ? SensorData_VirtualDetectionArea.fromPartial(object.virtual_detection_area)
        : undefined;
    message.system_time = (object.system_time !== undefined && object.system_time !== null)
      ? Timestamp.fromPartial(object.system_time)
      : undefined;
    return message;
  },
};

function createBaseSensorData_VirtualDetectionArea(): SensorData_VirtualDetectionArea {
  return { polygon: [] };
}

export const SensorData_VirtualDetectionArea: MessageFns<SensorData_VirtualDetectionArea> = {
  encode(message: SensorData_VirtualDetectionArea, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.polygon) {
      Polygon3d.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SensorData_VirtualDetectionArea {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSensorData_VirtualDetectionArea();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.polygon.push(Polygon3d.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SensorData_VirtualDetectionArea {
    return {
      polygon: globalThis.Array.isArray(object?.polygon) ? object.polygon.map((e: any) => Polygon3d.fromJSON(e)) : [],
    };
  },

  toJSON(message: SensorData_VirtualDetectionArea): unknown {
    const obj: any = {};
    if (message.polygon?.length) {
      obj.polygon = message.polygon.map((e) => Polygon3d.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SensorData_VirtualDetectionArea>, I>>(base?: I): SensorData_VirtualDetectionArea {
    return SensorData_VirtualDetectionArea.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SensorData_VirtualDetectionArea>, I>>(
    object: I,
  ): SensorData_VirtualDetectionArea {
    const message = createBaseSensorData_VirtualDetectionArea();
    message.polygon = object.polygon?.map((e) => Polygon3d.fromPartial(e)) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
