// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.0
//   protoc               unknown
// source: osi_detectedoccupant.proto

/* eslint-disable */
import { type DetectedItemHeader } from "./osi_detectedobject";
import { type Occupant_Classification } from "./osi_occupant";

/** \brief A vehicle occupant as detected and perceived by an interior sensor. */
export interface DetectedOccupant {
  /** Common information of one detected item. */
  header?:
    | DetectedItemHeader
    | undefined;
  /**
   * A list of candidates for this occupant as estimated by the
   * sensor.
   */
  candidate?: DetectedOccupant_CandidateOccupant[] | undefined;
}

/**
 * \brief A candidate for a detected occupant as estimated by
 * the sensor.
 */
export interface DetectedOccupant_CandidateOccupant {
  /**
   * The estimated probability that this candidate is the true value.
   *
   * \note The sum of all \c #probability must be one. This probability is
   * given under the condition of
   * \c DetectedItemHeader::existence_probability.
   *
   * \rules
   * is_greater_than_or_equal_to: 0
   * is_less_than_or_equal_to: 1
   * \endrules
   */
  probability?:
    | number
    | undefined;
  /**
   * The detected vehicle occupant classification.
   *
   * \note IDs, which are referenced in this message, usually
   * reference to \c DetectedXXX::tracking_id IDs.
   */
  classification?: Occupant_Classification | undefined;
}
