// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.0
//   protoc               unknown
// source: osi_detectedtrafficlight.proto

/* eslint-disable */
import { type BaseStationary } from "./osi_common";
import { type DetectedItemHeader } from "./osi_detectedobject";
import { type TrafficLight_Classification } from "./osi_trafficlight";

/**
 * \brief A traffic light in the environment as detected by the sensor.
 *
 * \image html OSI_DetectedTrafficLight.svg
 *
 * One detected traffic light message defines a single 'bulb' and not a box of
 * several bulbs, e.g. red, yellow, green are three separate detected traffic
 * lights.
 */
export interface DetectedTrafficLight {
  /** Common information of one detected item. */
  header?:
    | DetectedItemHeader
    | undefined;
  /**
   * The base parameters of the traffic light.
   *
   * \c BaseStationary::orientation x-axis is view normal of the traffic
   * light's icon.
   */
  base?:
    | BaseStationary
    | undefined;
  /**
   * The root mean squared error of the base parameters of the detected
   * traffic light's geometry. \c TrafficLight::base has to be identical
   * for all \c #candidate traffic lights.
   */
  base_rmse?:
    | BaseStationary
    | undefined;
  /**
   * A list of candidates for this traffic light as estimated by the
   * sensor.
   *
   * \note OSI uses singular instead of plural for repeated field names.
   */
  candidate?: DetectedTrafficLight_CandidateTrafficLight[] | undefined;
}

/**
 * \brief A candidate for a detected traffic light as estimated by
 * the sensor.
 */
export interface DetectedTrafficLight_CandidateTrafficLight {
  /**
   * The estimated probability that this candidate is the true value.
   *
   * \note The sum of all \c #probability must be one. This probability is
   * given under the condition of
   * \c DetectedItemHeader::existence_probability.
   *
   * Range: [0,1]
   */
  probability?:
    | number
    | undefined;
  /**
   * The classification of one traffic light that define this candidate.
   *
   * \note IDs, which are referenced in this message, usually
   * reference to \c DetectedXXX::tracking_id IDs.
   */
  classification?: TrafficLight_Classification | undefined;
}
