// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: osi_detectedoccupant.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { DetectedItemHeader } from "./osi_detectedobject";
import { Occupant_Classification } from "./osi_occupant";

/** \brief A vehicle occupant as detected and perceived by an interior sensor. */
export interface DetectedOccupant {
  /** Common information of one detected item. */
  header?:
    | DetectedItemHeader
    | undefined;
  /**
   * A list of candidates for this occupant as estimated by the
   * sensor.
   */
  candidate: DetectedOccupant_CandidateOccupant[];
}

/**
 * \brief A candidate for a detected occupant as estimated by
 * the sensor.
 */
export interface DetectedOccupant_CandidateOccupant {
  /**
   * The estimated probability that this candidate is the true value.
   *
   * \note The sum of all \c #probability must be one. This probability is
   * given under the condition of
   * \c DetectedItemHeader::existence_probability.
   *
   * \rules
   * is_greater_than_or_equal_to: 0
   * is_less_than_or_equal_to: 1
   * \endrules
   */
  probability?:
    | number
    | undefined;
  /**
   * The detected vehicle occupant classification.
   *
   * \note IDs, which are referenced in this message, usually
   * reference to \c DetectedXXX::tracking_id IDs.
   */
  classification?: Occupant_Classification | undefined;
}

function createBaseDetectedOccupant(): DetectedOccupant {
  return { header: undefined, candidate: [] };
}

export const DetectedOccupant: MessageFns<DetectedOccupant> = {
  encode(message: DetectedOccupant, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.header !== undefined) {
      DetectedItemHeader.encode(message.header, writer.uint32(10).fork()).join();
    }
    for (const v of message.candidate) {
      DetectedOccupant_CandidateOccupant.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DetectedOccupant {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDetectedOccupant();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.header = DetectedItemHeader.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.candidate.push(DetectedOccupant_CandidateOccupant.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DetectedOccupant {
    return {
      header: isSet(object.header) ? DetectedItemHeader.fromJSON(object.header) : undefined,
      candidate: globalThis.Array.isArray(object?.candidate)
        ? object.candidate.map((e: any) => DetectedOccupant_CandidateOccupant.fromJSON(e))
        : [],
    };
  },

  toJSON(message: DetectedOccupant): unknown {
    const obj: any = {};
    if (message.header !== undefined) {
      obj.header = DetectedItemHeader.toJSON(message.header);
    }
    if (message.candidate?.length) {
      obj.candidate = message.candidate.map((e) => DetectedOccupant_CandidateOccupant.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DetectedOccupant>, I>>(base?: I): DetectedOccupant {
    return DetectedOccupant.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DetectedOccupant>, I>>(object: I): DetectedOccupant {
    const message = createBaseDetectedOccupant();
    message.header = (object.header !== undefined && object.header !== null)
      ? DetectedItemHeader.fromPartial(object.header)
      : undefined;
    message.candidate = object.candidate?.map((e) => DetectedOccupant_CandidateOccupant.fromPartial(e)) || [];
    return message;
  },
};

function createBaseDetectedOccupant_CandidateOccupant(): DetectedOccupant_CandidateOccupant {
  return { probability: 0, classification: undefined };
}

export const DetectedOccupant_CandidateOccupant: MessageFns<DetectedOccupant_CandidateOccupant> = {
  encode(message: DetectedOccupant_CandidateOccupant, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.probability !== undefined && message.probability !== 0) {
      writer.uint32(9).double(message.probability);
    }
    if (message.classification !== undefined) {
      Occupant_Classification.encode(message.classification, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DetectedOccupant_CandidateOccupant {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDetectedOccupant_CandidateOccupant();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 9) {
            break;
          }

          message.probability = reader.double();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.classification = Occupant_Classification.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DetectedOccupant_CandidateOccupant {
    return {
      probability: isSet(object.probability) ? globalThis.Number(object.probability) : 0,
      classification: isSet(object.classification)
        ? Occupant_Classification.fromJSON(object.classification)
        : undefined,
    };
  },

  toJSON(message: DetectedOccupant_CandidateOccupant): unknown {
    const obj: any = {};
    if (message.probability !== undefined) {
      obj.probability = message.probability;
    }
    if (message.classification !== undefined) {
      obj.classification = Occupant_Classification.toJSON(message.classification);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DetectedOccupant_CandidateOccupant>, I>>(
    base?: I,
  ): DetectedOccupant_CandidateOccupant {
    return DetectedOccupant_CandidateOccupant.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DetectedOccupant_CandidateOccupant>, I>>(
    object: I,
  ): DetectedOccupant_CandidateOccupant {
    const message = createBaseDetectedOccupant_CandidateOccupant();
    message.probability = object.probability ?? 0;
    message.classification = (object.classification !== undefined && object.classification !== null)
      ? Occupant_Classification.fromPartial(object.classification)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
