// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: osi_sensorspecific.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Identifier } from "./osi_common";

/**
 * \brief Message encapsulates all data for detected objects that is specific to
 * radar sensors.
 */
export interface RadarSpecificObjectData {
  /**
   * The radar cross section (RCS) of the detected object.
   *
   * Unit: dB m^2
   */
  rcs?: number | undefined;
}

/**
 * \brief Message encapsulates all data for detected objects that is specific to
 * lidar sensors.
 */
export interface LidarSpecificObjectData {
}

/**
 * \brief Message encapsulates all data for detected objects that is specific to
 * camera sensors.
 */
export interface CameraSpecificObjectData {
}

/**
 * \brief Message encapsulates all data for detected objects that is specific to
 * ultrasonic sensors.
 */
export interface UltrasonicSpecificObjectData {
  /**
   * Maximum measured distance from one sensor which leads to the calculation
   * of this object.
   *
   * Unit: m
   *
   * \rules
   * is_greater_than_or_equal_to: 0
   * \endrules
   */
  maximum_measurement_distance_sensor?:
    | number
    | undefined;
  /**
   * This value indicates the probability height for the classification in the
   * calculated object.
   *
   * Unit: %
   *
   * \rules
   * is_less_than_or_equal_to: 1
   * is_greater_than_or_equal_to: 0
   * \endrules
   */
  probability?:
    | number
    | undefined;
  /**
   * This indicates if the detection was calculated based on one or multiple
   * sensors.
   */
  trilateration_status?:
    | UltrasonicSpecificObjectData_TrilaterationStatus
    | undefined;
  /** Describes the general moving direction of the detection. */
  trend?:
    | UltrasonicSpecificObjectData_Trend
    | undefined;
  /**
   * Ultrasonic signalway. Sender to receiver.
   *
   * \note This information can also be derived from the corresponding \c
   * UltrasonicDetection. \c UltrasonicDetection refer to DetectedXXX by \c
   * UltrasonicDetection::object_id.
   */
  signalway: UltrasonicSpecificObjectData_Signalway[];
}

/**
 * This indicates if the object was calculated based on one or multiple
 * sensors.
 */
export enum UltrasonicSpecificObjectData_TrilaterationStatus {
  /** TRILATERATION_STATUS_UNKNOWN - Unknown (must not be used in ground truth). */
  TRILATERATION_STATUS_UNKNOWN = 0,
  /** TRILATERATION_STATUS_OTHER - Other (unspecified but known). */
  TRILATERATION_STATUS_OTHER = 1,
  /** TRILATERATION_STATUS_NOT_TRILATERATED - No trilateration used. */
  TRILATERATION_STATUS_NOT_TRILATERATED = 2,
  /** TRILATERATION_STATUS_TRILATERATED - Trilateration used. */
  TRILATERATION_STATUS_TRILATERATED = 3,
}

export function ultrasonicSpecificObjectData_TrilaterationStatusFromJSON(
  object: any,
): UltrasonicSpecificObjectData_TrilaterationStatus {
  switch (object) {
    case 0:
    case "TRILATERATION_STATUS_UNKNOWN":
      return UltrasonicSpecificObjectData_TrilaterationStatus.TRILATERATION_STATUS_UNKNOWN;
    case 1:
    case "TRILATERATION_STATUS_OTHER":
      return UltrasonicSpecificObjectData_TrilaterationStatus.TRILATERATION_STATUS_OTHER;
    case 2:
    case "TRILATERATION_STATUS_NOT_TRILATERATED":
      return UltrasonicSpecificObjectData_TrilaterationStatus.TRILATERATION_STATUS_NOT_TRILATERATED;
    case 3:
    case "TRILATERATION_STATUS_TRILATERATED":
      return UltrasonicSpecificObjectData_TrilaterationStatus.TRILATERATION_STATUS_TRILATERATED;
    default:
      throw new globalThis.Error(
        "Unrecognized enum value " + object + " for enum UltrasonicSpecificObjectData_TrilaterationStatus",
      );
  }
}

export function ultrasonicSpecificObjectData_TrilaterationStatusToJSON(
  object: UltrasonicSpecificObjectData_TrilaterationStatus,
): string {
  switch (object) {
    case UltrasonicSpecificObjectData_TrilaterationStatus.TRILATERATION_STATUS_UNKNOWN:
      return "TRILATERATION_STATUS_UNKNOWN";
    case UltrasonicSpecificObjectData_TrilaterationStatus.TRILATERATION_STATUS_OTHER:
      return "TRILATERATION_STATUS_OTHER";
    case UltrasonicSpecificObjectData_TrilaterationStatus.TRILATERATION_STATUS_NOT_TRILATERATED:
      return "TRILATERATION_STATUS_NOT_TRILATERATED";
    case UltrasonicSpecificObjectData_TrilaterationStatus.TRILATERATION_STATUS_TRILATERATED:
      return "TRILATERATION_STATUS_TRILATERATED";
    default:
      throw new globalThis.Error(
        "Unrecognized enum value " + object + " for enum UltrasonicSpecificObjectData_TrilaterationStatus",
      );
  }
}

/** Describes the general moving direction of the detection. */
export enum UltrasonicSpecificObjectData_Trend {
  /** TREND_UNKNOWN - Unknown (must not be used in ground truth). */
  TREND_UNKNOWN = 0,
  /** TREND_OTHER - Other (unspecified but known). */
  TREND_OTHER = 1,
  /**
   * TREND_CONSTANT_APPROACHING - Distance (object, sensor) is constant. The object has approached in
   * the past before it was constant.
   */
  TREND_CONSTANT_APPROACHING = 2,
  /**
   * TREND_CONSTANT - Distance (object, sensor) is constant. The object has departed in the
   * past before it was constant or there is no history.
   */
  TREND_CONSTANT = 3,
  /** TREND_APPROACHING - Distance (object, sensor) is decreasing. */
  TREND_APPROACHING = 4,
  /** TREND_DEPARTING - Distance (object, sensor) is increasing. */
  TREND_DEPARTING = 5,
}

export function ultrasonicSpecificObjectData_TrendFromJSON(object: any): UltrasonicSpecificObjectData_Trend {
  switch (object) {
    case 0:
    case "TREND_UNKNOWN":
      return UltrasonicSpecificObjectData_Trend.TREND_UNKNOWN;
    case 1:
    case "TREND_OTHER":
      return UltrasonicSpecificObjectData_Trend.TREND_OTHER;
    case 2:
    case "TREND_CONSTANT_APPROACHING":
      return UltrasonicSpecificObjectData_Trend.TREND_CONSTANT_APPROACHING;
    case 3:
    case "TREND_CONSTANT":
      return UltrasonicSpecificObjectData_Trend.TREND_CONSTANT;
    case 4:
    case "TREND_APPROACHING":
      return UltrasonicSpecificObjectData_Trend.TREND_APPROACHING;
    case 5:
    case "TREND_DEPARTING":
      return UltrasonicSpecificObjectData_Trend.TREND_DEPARTING;
    default:
      throw new globalThis.Error("Unrecognized enum value " + object + " for enum UltrasonicSpecificObjectData_Trend");
  }
}

export function ultrasonicSpecificObjectData_TrendToJSON(object: UltrasonicSpecificObjectData_Trend): string {
  switch (object) {
    case UltrasonicSpecificObjectData_Trend.TREND_UNKNOWN:
      return "TREND_UNKNOWN";
    case UltrasonicSpecificObjectData_Trend.TREND_OTHER:
      return "TREND_OTHER";
    case UltrasonicSpecificObjectData_Trend.TREND_CONSTANT_APPROACHING:
      return "TREND_CONSTANT_APPROACHING";
    case UltrasonicSpecificObjectData_Trend.TREND_CONSTANT:
      return "TREND_CONSTANT";
    case UltrasonicSpecificObjectData_Trend.TREND_APPROACHING:
      return "TREND_APPROACHING";
    case UltrasonicSpecificObjectData_Trend.TREND_DEPARTING:
      return "TREND_DEPARTING";
    default:
      throw new globalThis.Error("Unrecognized enum value " + object + " for enum UltrasonicSpecificObjectData_Trend");
  }
}

/**
 * \brief Message encapsulates all data for detected objects that is
 * specific to ultrasonic sensors.
 */
export interface UltrasonicSpecificObjectData_Signalway {
  /** The ID of the ultrasonic sensor's sender. */
  sender_id?:
    | Identifier
    | undefined;
  /** The ID of the ultrasonic sensor's receiver. */
  receiver_id?: Identifier | undefined;
}

function createBaseRadarSpecificObjectData(): RadarSpecificObjectData {
  return { rcs: 0 };
}

export const RadarSpecificObjectData: MessageFns<RadarSpecificObjectData> = {
  encode(message: RadarSpecificObjectData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.rcs !== undefined && message.rcs !== 0) {
      writer.uint32(9).double(message.rcs);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RadarSpecificObjectData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRadarSpecificObjectData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 9) {
            break;
          }

          message.rcs = reader.double();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RadarSpecificObjectData {
    return { rcs: isSet(object.rcs) ? globalThis.Number(object.rcs) : 0 };
  },

  toJSON(message: RadarSpecificObjectData): unknown {
    const obj: any = {};
    if (message.rcs !== undefined) {
      obj.rcs = message.rcs;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RadarSpecificObjectData>, I>>(base?: I): RadarSpecificObjectData {
    return RadarSpecificObjectData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RadarSpecificObjectData>, I>>(object: I): RadarSpecificObjectData {
    const message = createBaseRadarSpecificObjectData();
    message.rcs = object.rcs ?? 0;
    return message;
  },
};

function createBaseLidarSpecificObjectData(): LidarSpecificObjectData {
  return {};
}

export const LidarSpecificObjectData: MessageFns<LidarSpecificObjectData> = {
  encode(_: LidarSpecificObjectData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LidarSpecificObjectData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLidarSpecificObjectData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): LidarSpecificObjectData {
    return {};
  },

  toJSON(_: LidarSpecificObjectData): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<LidarSpecificObjectData>, I>>(base?: I): LidarSpecificObjectData {
    return LidarSpecificObjectData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LidarSpecificObjectData>, I>>(_: I): LidarSpecificObjectData {
    const message = createBaseLidarSpecificObjectData();
    return message;
  },
};

function createBaseCameraSpecificObjectData(): CameraSpecificObjectData {
  return {};
}

export const CameraSpecificObjectData: MessageFns<CameraSpecificObjectData> = {
  encode(_: CameraSpecificObjectData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CameraSpecificObjectData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCameraSpecificObjectData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): CameraSpecificObjectData {
    return {};
  },

  toJSON(_: CameraSpecificObjectData): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<CameraSpecificObjectData>, I>>(base?: I): CameraSpecificObjectData {
    return CameraSpecificObjectData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CameraSpecificObjectData>, I>>(_: I): CameraSpecificObjectData {
    const message = createBaseCameraSpecificObjectData();
    return message;
  },
};

function createBaseUltrasonicSpecificObjectData(): UltrasonicSpecificObjectData {
  return { maximum_measurement_distance_sensor: 0, probability: 0, trilateration_status: 0, trend: 0, signalway: [] };
}

export const UltrasonicSpecificObjectData: MessageFns<UltrasonicSpecificObjectData> = {
  encode(message: UltrasonicSpecificObjectData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (
      message.maximum_measurement_distance_sensor !== undefined && message.maximum_measurement_distance_sensor !== 0
    ) {
      writer.uint32(9).double(message.maximum_measurement_distance_sensor);
    }
    if (message.probability !== undefined && message.probability !== 0) {
      writer.uint32(17).double(message.probability);
    }
    if (message.trilateration_status !== undefined && message.trilateration_status !== 0) {
      writer.uint32(24).int32(message.trilateration_status);
    }
    if (message.trend !== undefined && message.trend !== 0) {
      writer.uint32(32).int32(message.trend);
    }
    for (const v of message.signalway) {
      UltrasonicSpecificObjectData_Signalway.encode(v!, writer.uint32(42).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UltrasonicSpecificObjectData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUltrasonicSpecificObjectData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 9) {
            break;
          }

          message.maximum_measurement_distance_sensor = reader.double();
          continue;
        }
        case 2: {
          if (tag !== 17) {
            break;
          }

          message.probability = reader.double();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.trilateration_status = reader.int32() as any;
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.trend = reader.int32() as any;
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.signalway.push(UltrasonicSpecificObjectData_Signalway.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UltrasonicSpecificObjectData {
    return {
      maximum_measurement_distance_sensor: isSet(object.maximum_measurement_distance_sensor)
        ? globalThis.Number(object.maximum_measurement_distance_sensor)
        : 0,
      probability: isSet(object.probability) ? globalThis.Number(object.probability) : 0,
      trilateration_status: isSet(object.trilateration_status)
        ? ultrasonicSpecificObjectData_TrilaterationStatusFromJSON(object.trilateration_status)
        : 0,
      trend: isSet(object.trend) ? ultrasonicSpecificObjectData_TrendFromJSON(object.trend) : 0,
      signalway: globalThis.Array.isArray(object?.signalway)
        ? object.signalway.map((e: any) => UltrasonicSpecificObjectData_Signalway.fromJSON(e))
        : [],
    };
  },

  toJSON(message: UltrasonicSpecificObjectData): unknown {
    const obj: any = {};
    if (message.maximum_measurement_distance_sensor !== undefined) {
      obj.maximum_measurement_distance_sensor = message.maximum_measurement_distance_sensor;
    }
    if (message.probability !== undefined) {
      obj.probability = message.probability;
    }
    if (message.trilateration_status !== undefined) {
      obj.trilateration_status = ultrasonicSpecificObjectData_TrilaterationStatusToJSON(message.trilateration_status);
    }
    if (message.trend !== undefined) {
      obj.trend = ultrasonicSpecificObjectData_TrendToJSON(message.trend);
    }
    if (message.signalway?.length) {
      obj.signalway = message.signalway.map((e) => UltrasonicSpecificObjectData_Signalway.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UltrasonicSpecificObjectData>, I>>(base?: I): UltrasonicSpecificObjectData {
    return UltrasonicSpecificObjectData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UltrasonicSpecificObjectData>, I>>(object: I): UltrasonicSpecificObjectData {
    const message = createBaseUltrasonicSpecificObjectData();
    message.maximum_measurement_distance_sensor = object.maximum_measurement_distance_sensor ?? 0;
    message.probability = object.probability ?? 0;
    message.trilateration_status = object.trilateration_status ?? 0;
    message.trend = object.trend ?? 0;
    message.signalway = object.signalway?.map((e) => UltrasonicSpecificObjectData_Signalway.fromPartial(e)) || [];
    return message;
  },
};

function createBaseUltrasonicSpecificObjectData_Signalway(): UltrasonicSpecificObjectData_Signalway {
  return { sender_id: undefined, receiver_id: undefined };
}

export const UltrasonicSpecificObjectData_Signalway: MessageFns<UltrasonicSpecificObjectData_Signalway> = {
  encode(message: UltrasonicSpecificObjectData_Signalway, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.sender_id !== undefined) {
      Identifier.encode(message.sender_id, writer.uint32(10).fork()).join();
    }
    if (message.receiver_id !== undefined) {
      Identifier.encode(message.receiver_id, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UltrasonicSpecificObjectData_Signalway {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUltrasonicSpecificObjectData_Signalway();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.sender_id = Identifier.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.receiver_id = Identifier.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UltrasonicSpecificObjectData_Signalway {
    return {
      sender_id: isSet(object.sender_id) ? Identifier.fromJSON(object.sender_id) : undefined,
      receiver_id: isSet(object.receiver_id) ? Identifier.fromJSON(object.receiver_id) : undefined,
    };
  },

  toJSON(message: UltrasonicSpecificObjectData_Signalway): unknown {
    const obj: any = {};
    if (message.sender_id !== undefined) {
      obj.sender_id = Identifier.toJSON(message.sender_id);
    }
    if (message.receiver_id !== undefined) {
      obj.receiver_id = Identifier.toJSON(message.receiver_id);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UltrasonicSpecificObjectData_Signalway>, I>>(
    base?: I,
  ): UltrasonicSpecificObjectData_Signalway {
    return UltrasonicSpecificObjectData_Signalway.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UltrasonicSpecificObjectData_Signalway>, I>>(
    object: I,
  ): UltrasonicSpecificObjectData_Signalway {
    const message = createBaseUltrasonicSpecificObjectData_Signalway();
    message.sender_id = (object.sender_id !== undefined && object.sender_id !== null)
      ? Identifier.fromPartial(object.sender_id)
      : undefined;
    message.receiver_id = (object.receiver_id !== undefined && object.receiver_id !== null)
      ? Identifier.fromPartial(object.receiver_id)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
