// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.0
//   protoc               unknown
// source: osi_streamingupdate.proto

/* eslint-disable */
import { type Identifier, type Timestamp } from "./osi_common";
import { type EnvironmentalConditions } from "./osi_environment";
import { type HostVehicleData } from "./osi_hostvehicledata";
import { type MovingObject, type StationaryObject } from "./osi_object";
import { type TrafficLight } from "./osi_trafficlight";
import { type TrafficSign } from "./osi_trafficsign";
import { type InterfaceVersion } from "./osi_version";

/**
 * \brief The streaming update interface enables simulation entities to send
 * partial updates to other modules that favor performance (especially latency)
 * over data completeness/consistency (e.g. visualization applications).
 *
 * Static and/or non-relevant objects can be omitted as required for the
 * specific use case. Adding an object's unique id to the repeated field \c
 * obsolete_id indicates that it will no longer be updated from then on.
 *
 * \note The receiver of partial streaming update messages can only rely on the
 * most up-to-date information at the corresponding timestamp. E.g. omitting
 * objects does not indicate static behavior but it may be sufficient for the
 * use case to update certain objects at a later point in time.
 */
export interface StreamingUpdate {
  /**
   * The interface version used by the sender.
   *
   * \rules
   * is_set
   * \endrules
   */
  version?:
    | InterfaceVersion
    | undefined;
  /**
   * The data timestamp where the information of contained objects is calculated.
   *
   * Zero time is arbitrary but must be identical for all messages.
   * Zero time does not need to coincide with the UNIX epoch.
   * Recommended is the starting time point of the simulation.
   *
   * \rules
   * is_set
   * \endrules
   */
  timestamp?:
    | Timestamp
    | undefined;
  /**
   * The list of stationary objects (excluding traffic signs and traffic
   * lights).
   */
  stationary_object_update?:
    | StationaryObject[]
    | undefined;
  /** The list of moving objects. */
  moving_object_update?:
    | MovingObject[]
    | undefined;
  /** The list of traffic signs. */
  traffic_sign_update?:
    | TrafficSign[]
    | undefined;
  /** The list of traffic lights. */
  traffic_light_update?:
    | TrafficLight[]
    | undefined;
  /** Conditions of the environment. */
  environmental_conditions_update?:
    | EnvironmentalConditions
    | undefined;
  /**
   * Host vehicle data.
   *
   * Host vehicle data is data that the host vehicle knows about itself,
   * e.g. from location sensors, internal sensors and ECU bus data, etc.,
   * that is made available to sensors as input.
   *
   * The ID inside this message allows an association to moving object data.
   */
  host_vehicle_data_update?:
    | HostVehicleData[]
    | undefined;
  /**
   * Entities that will no longer be updated, because they are considered
   * obsolete by the sender.
   *
   * \note IDs are globally unique.
   */
  obsolete_id?: Identifier[] | undefined;
}
