// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: osi_detectedtrafficlight.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { BaseStationary, ColorDescription } from "./osi_common";
import { DetectedItemHeader } from "./osi_detectedobject";
import { TrafficLight_Classification } from "./osi_trafficlight";

/**
 * \brief A traffic light in the environment as detected by the sensor.
 *
 * \image html OSI_DetectedTrafficLight.svg
 *
 * One detected traffic light message defines a single 'bulb' and not a box of
 * several bulbs, e.g. red, yellow, green are three separate detected traffic
 * lights.
 *
 * The parent frame of a detected traffic light is the virtual sensor coordinate
 * system.
 *
 * /note The virtual sensor coordinate system is relative to the vehicle coordinate
 * system which has its origin in the center of the rear axle of the ego
 * vehicle. This means if virtual sensor mounting position and orientation are
 * set to (0,0,0) the virtual sensor coordinate system coincides with the
 * vehicle coordinate system.
 */
export interface DetectedTrafficLight {
  /** Common information of one detected item. */
  header?:
    | DetectedItemHeader
    | undefined;
  /**
   * The base parameters of the traffic light.
   *
   * \c BaseStationary::orientation x-axis is view normal of the traffic
   * light's icon.
   */
  base?:
    | BaseStationary
    | undefined;
  /**
   * The root mean squared error of the base parameters of the detected
   * traffic light's geometry. \c TrafficLight::base has to be identical
   * for all \c #candidate traffic lights.
   */
  base_rmse?:
    | BaseStationary
    | undefined;
  /**
   * A list of candidates for this traffic light as estimated by the
   * sensor.
   */
  candidate: DetectedTrafficLight_CandidateTrafficLight[];
  /**
   * The visual color of the traffic light.
   *
   * \note This does not represent the semantic classification but the visual
   * appearance.  For semantic classification of the traffic light use the color
   * field in \c CandidateTrafficLight::classification.
   */
  color_description?: ColorDescription | undefined;
}

/**
 * \brief A candidate for a detected traffic light as estimated by
 * the sensor.
 */
export interface DetectedTrafficLight_CandidateTrafficLight {
  /**
   * The estimated probability that this candidate is the true value.
   *
   * \note The sum of all \c #probability must be one. This probability is
   * given under the condition of
   * \c DetectedItemHeader::existence_probability.
   *
   * \rules
   * is_less_than_or_equal_to: 1
   * is_greater_than_or_equal_to: 0
   * \endrules
   */
  probability?:
    | number
    | undefined;
  /**
   * The classification of one traffic light that define this candidate.
   *
   * \note IDs, which are referenced in this message, usually
   * reference to \c DetectedXXX::tracking_id IDs.
   */
  classification?: TrafficLight_Classification | undefined;
}

function createBaseDetectedTrafficLight(): DetectedTrafficLight {
  return { header: undefined, base: undefined, base_rmse: undefined, candidate: [], color_description: undefined };
}

export const DetectedTrafficLight: MessageFns<DetectedTrafficLight> = {
  encode(message: DetectedTrafficLight, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.header !== undefined) {
      DetectedItemHeader.encode(message.header, writer.uint32(10).fork()).join();
    }
    if (message.base !== undefined) {
      BaseStationary.encode(message.base, writer.uint32(18).fork()).join();
    }
    if (message.base_rmse !== undefined) {
      BaseStationary.encode(message.base_rmse, writer.uint32(26).fork()).join();
    }
    for (const v of message.candidate) {
      DetectedTrafficLight_CandidateTrafficLight.encode(v!, writer.uint32(34).fork()).join();
    }
    if (message.color_description !== undefined) {
      ColorDescription.encode(message.color_description, writer.uint32(42).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DetectedTrafficLight {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDetectedTrafficLight();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.header = DetectedItemHeader.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.base = BaseStationary.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.base_rmse = BaseStationary.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.candidate.push(DetectedTrafficLight_CandidateTrafficLight.decode(reader, reader.uint32()));
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.color_description = ColorDescription.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DetectedTrafficLight {
    return {
      header: isSet(object.header) ? DetectedItemHeader.fromJSON(object.header) : undefined,
      base: isSet(object.base) ? BaseStationary.fromJSON(object.base) : undefined,
      base_rmse: isSet(object.base_rmse) ? BaseStationary.fromJSON(object.base_rmse) : undefined,
      candidate: globalThis.Array.isArray(object?.candidate)
        ? object.candidate.map((e: any) => DetectedTrafficLight_CandidateTrafficLight.fromJSON(e))
        : [],
      color_description: isSet(object.color_description)
        ? ColorDescription.fromJSON(object.color_description)
        : undefined,
    };
  },

  toJSON(message: DetectedTrafficLight): unknown {
    const obj: any = {};
    if (message.header !== undefined) {
      obj.header = DetectedItemHeader.toJSON(message.header);
    }
    if (message.base !== undefined) {
      obj.base = BaseStationary.toJSON(message.base);
    }
    if (message.base_rmse !== undefined) {
      obj.base_rmse = BaseStationary.toJSON(message.base_rmse);
    }
    if (message.candidate?.length) {
      obj.candidate = message.candidate.map((e) => DetectedTrafficLight_CandidateTrafficLight.toJSON(e));
    }
    if (message.color_description !== undefined) {
      obj.color_description = ColorDescription.toJSON(message.color_description);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DetectedTrafficLight>, I>>(base?: I): DetectedTrafficLight {
    return DetectedTrafficLight.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DetectedTrafficLight>, I>>(object: I): DetectedTrafficLight {
    const message = createBaseDetectedTrafficLight();
    message.header = (object.header !== undefined && object.header !== null)
      ? DetectedItemHeader.fromPartial(object.header)
      : undefined;
    message.base = (object.base !== undefined && object.base !== null)
      ? BaseStationary.fromPartial(object.base)
      : undefined;
    message.base_rmse = (object.base_rmse !== undefined && object.base_rmse !== null)
      ? BaseStationary.fromPartial(object.base_rmse)
      : undefined;
    message.candidate = object.candidate?.map((e) => DetectedTrafficLight_CandidateTrafficLight.fromPartial(e)) || [];
    message.color_description = (object.color_description !== undefined && object.color_description !== null)
      ? ColorDescription.fromPartial(object.color_description)
      : undefined;
    return message;
  },
};

function createBaseDetectedTrafficLight_CandidateTrafficLight(): DetectedTrafficLight_CandidateTrafficLight {
  return { probability: 0, classification: undefined };
}

export const DetectedTrafficLight_CandidateTrafficLight: MessageFns<DetectedTrafficLight_CandidateTrafficLight> = {
  encode(message: DetectedTrafficLight_CandidateTrafficLight, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.probability !== undefined && message.probability !== 0) {
      writer.uint32(9).double(message.probability);
    }
    if (message.classification !== undefined) {
      TrafficLight_Classification.encode(message.classification, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DetectedTrafficLight_CandidateTrafficLight {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDetectedTrafficLight_CandidateTrafficLight();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 9) {
            break;
          }

          message.probability = reader.double();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.classification = TrafficLight_Classification.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DetectedTrafficLight_CandidateTrafficLight {
    return {
      probability: isSet(object.probability) ? globalThis.Number(object.probability) : 0,
      classification: isSet(object.classification)
        ? TrafficLight_Classification.fromJSON(object.classification)
        : undefined,
    };
  },

  toJSON(message: DetectedTrafficLight_CandidateTrafficLight): unknown {
    const obj: any = {};
    if (message.probability !== undefined) {
      obj.probability = message.probability;
    }
    if (message.classification !== undefined) {
      obj.classification = TrafficLight_Classification.toJSON(message.classification);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DetectedTrafficLight_CandidateTrafficLight>, I>>(
    base?: I,
  ): DetectedTrafficLight_CandidateTrafficLight {
    return DetectedTrafficLight_CandidateTrafficLight.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DetectedTrafficLight_CandidateTrafficLight>, I>>(
    object: I,
  ): DetectedTrafficLight_CandidateTrafficLight {
    const message = createBaseDetectedTrafficLight_CandidateTrafficLight();
    message.probability = object.probability ?? 0;
    message.classification = (object.classification !== undefined && object.classification !== null)
      ? TrafficLight_Classification.fromPartial(object.classification)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
