// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: osi_logicallane.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { ExternalReference, Identifier, Vector3d } from "./osi_common";
import {
  MovingObject_Type,
  movingObject_TypeFromJSON,
  movingObject_TypeToJSON,
  MovingObject_VehicleClassification_Role,
  movingObject_VehicleClassification_RoleFromJSON,
  movingObject_VehicleClassification_RoleToJSON,
  MovingObject_VehicleClassification_Type,
  movingObject_VehicleClassification_TypeFromJSON,
  movingObject_VehicleClassification_TypeToJSON,
} from "./osi_object";
import { TrafficSignValue } from "./osi_trafficsign";

/**
 * \brief Boundary line of a LogicalLane
 *
 * Similar to a LaneBoundary, but with a reference line and ST positions.
 *
 * A logical lane boundary describes the boundary between two logical lanes. As
 * such, there will always be exactly one logical lane boundary between two
 * lanes at a given S position. Contrary to that, there can be 0 to N physical
 * lane boundaries (i.e. type LaneBoundary) between two logical lanes at a
 * given S position.
 *
 * If there are multiple physical lane boundaries at one S position between two
 * lanes (think of a solid-broken marking, which would be described by two
 * LaneBoundary objects, one for the solid lane marking, one for the broken lane
 * marking), then the single LogicalLaneBoundary describing the boundary between
 * two logical lanes should be between the physical boundaries.
 *
 * A logical lane boundary consists of a list of \link LogicalBoundaryPoint
 * LogicalBoundaryPoints\endlink. Each point has a XYZ and an ST coordinate.
 * The XYZ coordinates describe the position and height of the boundary in the
 * world.
 *
 * Notes on design decisions:
 * - The LogicalLaneBoundary has ST coordinates, and is thus a separate type
 *   from LaneBoundary.
 *   Advantages of this decision:
 *   - Calculations like getting the lane width at a position are easy, since
 *     one can just get the boundary points of the left and right boundary at
 *     the desired S position (via linear interpolation), and calculate the
 *     width from the two points. Also getting something like the distance to
 *     the lane border is very easy.
 *   - No centerline of the lane is necessary, since this can very easily be
 *     generated from the boundaries.
 *   Disadvantages of this decision:
 *   - %Lane boundaries cannot be shared with physical lanes. This results in
 *     more data needed. This can mostly be mitigated by only transmitting the
 *     lane boundaries during initialization (e.g. via the OSMP GroundTruthInit
 *     message).
 * - The LogicalLaneBoundary contains all data directly which an agent model is
 *   likely to need. It does not include information normally only used by
 *   sensor models (e.g. the exact length of the color markings on the road).
 *   This information can be gotten from the physical lane referenced in the
 *   LogicalLane, if needed.
 */
export interface LogicalLaneBoundary {
  /**
   * The ID of the lane boundary.
   *
   * \rules
   * is_globally_unique
   * is_set
   * \endrules
   */
  id?:
    | Identifier
    | undefined;
  /**
   * Points making up the lane boundary.
   *
   * The boundary must be defined in the same direction as the reference
   * line. So S positions should increase along the line. Note that S
   * positions will not always increase strictly monotonically.
   * Example:
   * <pre>
   *                |---------\
   *                |          \
   *  /---boundary--|           \\------------
   * /
   * ---------- reference line --------------
   * </pre>
   * At the place where the boundary suddenly increases, two points will have
   * the same S coordinate.
   *
   * If the boundary approximates a curve (e.g. a cubic function in
   * OpenDRIVE), the points must be chosen in a way that the lateral distance
   * to the ideal line does not exceed 5cm. As shown in the following image:
   *
   * \image html line_approximation_error.svg "Approximation error"
   * Approximation error green line.
   *
   * The Z error (difference in Z height between #boundary_line and the
   * "real" line) must not exceed 2cm. This is a stricter requirement than
   * for errors in the XY plane, because Z differences between lanes
   * influence driving very much.
   *
   * Note: if two lanes have different Z heights (e.g. a driving lane is
   * beside a sidewalk, where the sidewalk is 10cm higher than the road),
   * then these lanes cannot share a boundary, since their boundaries have
   * different Z heights.
   */
  boundary_line: LogicalLaneBoundary_LogicalBoundaryPoint[];
  /**
   * The reference line for this boundary.
   *
   * The reference line is used as a coordinate system for this boundary.
   * All points of this LogicalLaneBoundary must have S coordinates in the
   * range [\c sStart,\c sEnd].
   *
   * The reference line should roughly have the same shape as the boundary (so
   * roughly parallel to the lane middle), so that S coordinates continually
   * increase along the boundary.
   *
   * \rules
   * refers_to: ReferenceLine
   * \endrules
   */
  reference_line_id?:
    | Identifier
    | undefined;
  /**
   * Reference to the physical lane boundary or boundaries that make up this
   * logical boundary.
   *
   * Rules and notes:
   * - This list is empty if there are no physical lane boundaries to delimit
   *   a lane.
   * - In the common case, this will contain one physical boundary.
   * - This list contains several lane boundaries if there are several physical
   *   lane boundaries at one S position (e.g. both a broken and a solid
   *   line).
   * - If there are several lane boundaries, they must be listed in increasing
   *   T order (i.e. from right to left in reference line direction).
   *   Rationale: this makes it easier to determine e.g. rules on lane
   *   changes, which depend on the T order of the lanes.
   * - Whenever physical lane boundaries begin or end, or switch their T
   *   position (if there are multiple physical lane boundaries), a new
   *   LogicalLaneBoundary must be created.
   * - The referenced LaneBoundary objects may be longer than the
   *   LogicalLaneBoundary which references them, but must never be shorter.
   *
   * Example:
   * <pre>
   *       Lane 1
   *  --------a------------------ - - - -c- - - -           ----&gt;
   *  \- - - -b- - - -
   *       Lane -1
   * </pre>
   *
   * This shows the boundary between lane 1 and lane -1, with the reference
   * line going from left to right. First there is a solid-broken line (a and
   * b), then there is only a solid line (a), then there is a broken line
   * (c). There would be three LogicalLaneBoundary objects between Lane1 and
   * Lane2: the first would reference first b and then a, the second would
   * reference only a, and the third would reference c.
   *
   * \rules
   * refers_to: LaneBoundary
   * \endrules
   */
  physical_boundary_id: Identifier[];
  /**
   * The passing rules, insomuch as they can be determined just from road
   * markings.
   */
  passing_rule?:
    | LogicalLaneBoundary_PassingRule
    | undefined;
  /**
   * Optional external reference to the lane boundary source.
   *
   * \note For OpenDRIVE, there is no direct possibility to reference the
   *       RoadMark, as there is no unique identifier in this sub-object.
   *
   * \note For non-ASAM Standards, it is implementation-specific how
   *       source_reference is resolved.
   *
   * \note The value has to be repeated because one object may be derived
   *       from more than one origin source, for example, from a scenario file
   *       and from sensors.
   */
  source_reference: ExternalReference[];
}

/**
 * Passing rule of the LogicalLaneBoundary.
 *
 * This describes how vehicles are legally allowed to move across the
 * LogicalLaneBoundary. The PassingRule is determined solely based
 * on the semantics of (physical) lane boundaries, not on any signs
 * (i.e. it may be overridden by signs).
 */
export enum LogicalLaneBoundary_PassingRule {
  /** PASSING_RULE_UNKNOWN - Passing rule is unknown (must not be used in ground truth). */
  PASSING_RULE_UNKNOWN = 0,
  /**
   * PASSING_RULE_OTHER - Passing rule fits neither of the other categories.
   *
   * Example: this type needs to be used if passing depends on the agent
   * type, e.g. if cars may change lane, but trucks may not.
   *
   * This value is also used between LogicalLanes where the traffic
   * regulations do not say anything about passing rules (e.g. for a
   * LogicalLaneBoundary between LogicalLanes of TYPE_NORMAL
   * and TYPE_CURB or between LogicalLanes of TYPE_BORDER and
   * TYPE_SHOULDER) .
   */
  PASSING_RULE_OTHER = 1,
  /**
   * PASSING_RULE_NONE_ALLOWED - No passing is allowed (neither from left to right nor from right to
   * left).
   */
  PASSING_RULE_NONE_ALLOWED = 2,
  /**
   * PASSING_RULE_INCREASING_T - Only passing in increasing T direction allowed. Passing is allowed
   * from one lane to the other if the points on the target lane have
   * larger T values than points on the source lane (at the same S
   * position). In reference line direction (but not necessarily in
   * driving direction), this means changing from right to left is
   * allowed.
   */
  PASSING_RULE_INCREASING_T = 3,
  /**
   * PASSING_RULE_DECREASING_T - Only passing in decreasing T direction allowed. Passing is allowed
   * from one lane to the other if the points on the target lane have
   * smaller T values than points on the source lane (at the same S
   * position). In reference line direction (but not necessarily in
   * driving direction), this means changing from left to right is
   * allowed.
   */
  PASSING_RULE_DECREASING_T = 4,
  /**
   * PASSING_RULE_BOTH_ALLOWED - Passing is allowed in both directions (left to right and right to
   * left).
   */
  PASSING_RULE_BOTH_ALLOWED = 5,
}

export function logicalLaneBoundary_PassingRuleFromJSON(object: any): LogicalLaneBoundary_PassingRule {
  switch (object) {
    case 0:
    case "PASSING_RULE_UNKNOWN":
      return LogicalLaneBoundary_PassingRule.PASSING_RULE_UNKNOWN;
    case 1:
    case "PASSING_RULE_OTHER":
      return LogicalLaneBoundary_PassingRule.PASSING_RULE_OTHER;
    case 2:
    case "PASSING_RULE_NONE_ALLOWED":
      return LogicalLaneBoundary_PassingRule.PASSING_RULE_NONE_ALLOWED;
    case 3:
    case "PASSING_RULE_INCREASING_T":
      return LogicalLaneBoundary_PassingRule.PASSING_RULE_INCREASING_T;
    case 4:
    case "PASSING_RULE_DECREASING_T":
      return LogicalLaneBoundary_PassingRule.PASSING_RULE_DECREASING_T;
    case 5:
    case "PASSING_RULE_BOTH_ALLOWED":
      return LogicalLaneBoundary_PassingRule.PASSING_RULE_BOTH_ALLOWED;
    default:
      throw new globalThis.Error("Unrecognized enum value " + object + " for enum LogicalLaneBoundary_PassingRule");
  }
}

export function logicalLaneBoundary_PassingRuleToJSON(object: LogicalLaneBoundary_PassingRule): string {
  switch (object) {
    case LogicalLaneBoundary_PassingRule.PASSING_RULE_UNKNOWN:
      return "PASSING_RULE_UNKNOWN";
    case LogicalLaneBoundary_PassingRule.PASSING_RULE_OTHER:
      return "PASSING_RULE_OTHER";
    case LogicalLaneBoundary_PassingRule.PASSING_RULE_NONE_ALLOWED:
      return "PASSING_RULE_NONE_ALLOWED";
    case LogicalLaneBoundary_PassingRule.PASSING_RULE_INCREASING_T:
      return "PASSING_RULE_INCREASING_T";
    case LogicalLaneBoundary_PassingRule.PASSING_RULE_DECREASING_T:
      return "PASSING_RULE_DECREASING_T";
    case LogicalLaneBoundary_PassingRule.PASSING_RULE_BOTH_ALLOWED:
      return "PASSING_RULE_BOTH_ALLOWED";
    default:
      throw new globalThis.Error("Unrecognized enum value " + object + " for enum LogicalLaneBoundary_PassingRule");
  }
}

/** \brief A point on the boundary */
export interface LogicalLaneBoundary_LogicalBoundaryPoint {
  /** The position of the \c LaneBoundaryPoint. */
  position?:
    | Vector3d
    | undefined;
  /**
   * S position of the LaneBoundaryPoint, measured along the parent's
   * reference_line_id.
   */
  s_position?:
    | number
    | undefined;
  /**
   * T position of the LaneBoundaryPoint, measured along the parent's
   * reference_line_id.
   */
  t_position?: number | undefined;
}

/**
 * \brief A logical lane in the road network.
 *
 * A logical lane is part of a road. Compared to a physical lane (OSI type
 * \c Lane), its existence doesn't hinge on the existence of road markings. So
 * e.g. a road with two driving directions but no road markings in-between
 * would be presented as two \link LogicalLane LogicalLanes\endlink, but only
 * one Lane. So one Lane can consist of multiple \link LogicalLane
 * LogicalLanes\endlink. E.g. on intersections, each driving path is one
 * LogicalLane, but the whole area is one \c Lane of type \link
 * osi3::Lane::Classification::TYPE_INTERSECTION \c TYPE_INTERSECTION \endlink.
 *
 * Outside of intersections, logical lanes are constructed such that each point on
 * the road belongs to at least one (typically: exactly one) logical lane. So
 * there are no gaps between logical lanes, and no areas that don't belong to a
 * logical lane.
 *
 * If OSI is generated from OpenDRIVE, then \link LogicalLane
 * LogicalLanes\endlink map directly to OpenDRIVE lanes. However, it is allowed
 * to merge multiple consecutive (in S direction) OpenDRIVE lanes with the same
 * type into one OSI LogicalLane: if an OpenDRIVE lane has a single successor,
 * which has the same lane type, and this successor has only one predecessor
 * (so no lane merging or splitting) then the two lanes may be presented as one
 * continuous LogicalLane. This may be done recursively.
 *
 * The \link ReferenceLine reference line\endlink pointed to by
 * #reference_line_id defines an ST coordinate system for the lane. This ST
 * coordinate system is used to describe positions on the lane.
 *
 * ## Example
 *
 * The example below shows two logical lanes on an intersection, with a focus
 * on the left-turn lane (\c l1):
 * \image html OSI_LogicalLane1.png "Two logical lanes on an intersection"
 *
 * Assumptions not shown in the image:
 * - This is right-hand traffic (and thus vehicles on \c l1 drive from the bottom
 *   to the left, vehicles on \c l2 drive from right to left).
 * - The yellow line is a ReferenceLine, defined starting at the bottom, and
 *   going to the left.
 *
 * Some features shown in the image relative to \c l1:
 * - The yellow line is the ReferenceLine of \c l1 . The ReferenceLine can be
 *   shared with other lanes.  Because the ReferenceLine has the same direction
 *   as the driving direction of \c l1 in this example,
 *   <code>#move_direction == #MOVE_DIRECTION_INCREASING_S</code>.
 * - The red line marks the area where \c l2 is left of
 *   \c l1 - this info is recorded in #left_adjacent_lane of \c l1.
 * - The red area is the area where \c l2 overlaps \c l1. This is recorded in
 *   #overlapping_lane of \c l1.
 *
 * The image below shows the same two lanes, but from the perspective of \c l2:
 * \image html OSI_LogicalLane2.png "Two logical lanes on an intersection"
 *
 * Assumptions not shown in the image:
 * - The yellow line is a ReferenceLine, defined starting at the right, going
 *   to the left.
 *
 * Some features shown in the image relative to \c l2:
 * - The yellow line is the ReferenceLine of \c l2 . The ReferenceLine can be
 *   shared with other lanes.  Because the ReferenceLine has the same direction
 *   as the driving direction of \c l2 in this example,
 *   <code>#move_direction == #MOVE_DIRECTION_INCREASING_S</code>.
 * - The green line marks the area where \c l1 is right of
 *   \c l2 - this info is recorded in #right_adjacent_lane of \c l2.
 * - The red area is the area where \c l1 overlaps \c l2. This is recorded in
 *   #overlapping_lane of \c l1.
 *
 * As can be seen in the images, the two highlighted lanes are neighbors for
 * part of their length, but it makes no sense for them to have the same
 * reference line, since they diverge significantly.
 *
 * Note: all the relations shown above are also defined outside of intersections.
 */
export interface LogicalLane {
  /**
   * The ID of the logical lane.
   *
   * \note Note ID is global unique.
   *
   * \rules
   * is_globally_unique
   * \endrules
   */
  id?:
    | Identifier
    | undefined;
  /** The type of the logical lane. */
  type?:
    | LogicalLane_Type
    | undefined;
  /**
   * Optional external reference to the lane source.
   *
   * The external reference points to the source of the lane, if it is derived
   * from one or more objects or external references.
   *
   * For example, to reference a lane defined in an OpenDRIVE map
   * the items should be set as follows:
   * * reference = URI to map, can remain empty if identical with definition
   *               in \c GroundTruth::map_reference
   * * type = "net.asam.opendrive"
   * * identifier[0] = id of t_road
   * * identifier[1] = s of t_road_lanes_laneSection
   * * identifier[2] = id of t_road_lanes_laneSection_left_lane,
   *                         t_road_lanes_laneSection_right_lane
   *
   * \note For non-ASAM Standards, it is implementation-specific how
   *       source_reference is resolved.
   *
   * \note The value has to be repeated, because one lane segment may be
   *       derived from more than one origin segment. Multiple sources
   *       may be added as reference as well, for example, a map and sensors.
   */
  source_reference: ExternalReference[];
  /**
   * Reference to the physical lanes this logical lane belongs to.
   *
   * This makes it possible to get detailed information on the physical lane
   * properties, e.g. the visual colors of the boundaries, the road
   * condition, etc..
   *
   * Note: a logical lane may consist of several physical lanes (in a row).
   * At any one S position, a logical lane should only reference one physical
   * lane. Several logical lanes may reference the same physical lane (see
   * drawing below).
   *
   * Logical lanes should not extend beyond intersections. All logical lanes
   * on intersections should end at the latest at the border of the
   * intersection.
   *
   * Example:
   * <pre>
   * ---------------------------------
   *  l1                       l2
   * ----------    l3        ---------
   *  l4                       l5
   * ---------------------------------
   * </pre>
   *
   * In this case, we have five physical lanes: l1, l2, l4 and l5 where a
   * lane marking is present. And l3 is one lane covering the whole road
   * (because no road marking is present).
   *
   * This would typically be presented as two logical lanes:
   * - One encompassing l1, part of l3, and l2
   * - The other encompassing l4, part of l3 and l5
   *
   * In this example, both logical lanes would reference l3. Their shared
   * LogicalLaneBoundary would cut through the middle of l3.
   *
   * physical_lane_reference does not give any information how much of the
   * area of a physical lane is covered by a logical lane.
   *
   * For LogicalLanes without a correspondence to a Lane.Classification.Subtype
   * (i.e. TYPE_MEDIAN, TYPE_CURB, TYPE_TRAM, TYPE_RAIL) this field has no value.
   *
   * \rules
   * refers_to: Lane
   * \endrules
   */
  physical_lane_reference: LogicalLane_PhysicalLaneReference[];
  /**
   * The \link ReferenceLine reference line\endlink for this logical lane
   *
   * The reference line is used as a coordinate system on this lane.
   *
   * The reference line should roughly have the same shape as the lane, so
   * that S coordinates continually increase/decrease along the lane. It is
   * not required that the reference line has the same direction as the
   * driving direction of the lane.
   *
   * Neighboring lanes (i.e. lanes that are neighbors and whose directions
   * do not diverge significantly) are strongly encouraged to reference the
   * same ReferenceLine, so that vehicles that are next to each other on
   * neighboring lanes have comparable S positions.
   *
   * The S coordinate of the reference line makes it easy to find e.g. which
   * object is next on a lane, using the LogicalLaneAssignment of the
   * objects.
   *
   * The reference trajectory must be sampled such that there are no two
   * positions on the lane more than 5cm apart with the same ST coordinate.
   *
   * \rules
   * refers_to: ReferenceLine
   * \endrules
   */
  reference_line_id?:
    | Identifier
    | undefined;
  /**
   * Start S position of the lane.
   *
   * Must be in range [\c sStart,\c sEnd] of the reference line.
   */
  start_s?:
    | number
    | undefined;
  /**
   * End S position of the lane.
   *
   * Must be in range [\c sStart,\c sEnd] of the reference line.
   *
   * Requirement: #end_s > #start_s
   */
  end_s?:
    | number
    | undefined;
  /** Definition of the intended driving direction. */
  move_direction?:
    | LogicalLane_MoveDirection
    | undefined;
  /**
   * Lanes that are directly right of this lane, without gap or overlap.
   *
   * "Right" is in definition direction (not driving direction), so right lanes
   * have smaller T coordinates.
   * Entries must be ordered: first by #start_s, then by #end_s.
   *
   * The XY positions of the polyline generated by the LogicalLaneBoundaries
   * of adjacent lanes must match up to a small error (5cm).
   * Typically adjacent lanes will share a LogicalLaneBoundary, but this will
   * not always be true. Examples: on intersections, it might be hard to generate
   * data such that lanes that are adjacent for a short length share a
   * LogicalLaneBoundary for this length; also different LogicalLaneBoundaries
   * are needed if the lanes have different heights at their boundaries (e.g.
   * road adjacent to a sidewalk).
   */
  right_adjacent_lane: LogicalLane_LaneRelation[];
  /**
   * Lanes that are directly left of this lane, without gap or overlap.
   *
   * "Left" is in definition direction (not driving direction), so left lanes
   * have larger T coordinates.
   * Entries must be ordered: first by #start_s, then by #end_s.
   *
   * The XY positions of the polyline generated by the LogicalLaneBoundaries
   * of adjacent lanes must match up to a small error (5cm).
   * Typically adjacent lanes will share a LogicalLaneBoundary, but this will
   * not always be true. Examples: on intersections, it might be hard to generate
   * data such that lanes that are adjacent for a short length share a
   * LogicalLaneBoundary for this length; also different LogicalLaneBoundaries
   * are needed if the lanes have different heights at their boundaries (e.g.
   * road adjacent to a sidewalk).
   */
  left_adjacent_lane: LogicalLane_LaneRelation[];
  /**
   * Lanes that partially or completely overlap this lane.
   *
   * Only overlaps laterally larger than 5cm are considered overlaps for the
   * purpose of this relation.
   *
   * This will typically contain a lot of entries on intersections, but might
   * also be used outside of intersections (e.g. if a #TYPE_BIKING lane
   * overlaps a #TYPE_NORMAL lane).
   *
   * Entries must be ordered: first by #start_s, then by #end_s.
   */
  overlapping_lane: LogicalLane_LaneRelation[];
  /**
   * Right boundary of this lane.
   *
   * References to LogicalLaneBoundary elements.
   * All LogicalLaneBoundary elements referenced here must refer to the same
   * ReferenceLine as this lane.
   * The boundaries together must cover the whole length of the lane (the
   * range \[#start_s,#end_s\]) without gap or overlap. The boundaries must be
   * stored in ascending order, starting with the smallest S position.
   * Consecutive boundaries must share a point: the last point of the
   * previous boundary must be identical to the first point of the next
   * boundary.
   *
   * Note: the referenced boundaries may have points outside of
   * \[#start_s,#end_s\] (e.g. a boundary may extend beyond the end of a lane).
   *
   * Note: A curb is a type of LogicalLane and of LaneBoundary.
   * If LogicalLane.Type == TYPE_CURB, by convention this
   * field references the respective LaneBoundary of TYPE_CURB
   * identically to the left_boundary_id of this LogicalLane.
   *
   * \rules
   * refers_to: LogicalLaneBoundary
   * \endrules
   */
  right_boundary_id: Identifier[];
  /**
   * Left boundary of this lane.
   *
   * References to LogicalLaneBoundary elements.
   * All LogicalLaneBoundary elements referenced here must refer to the same
   * ReferenceLine as this lane.
   * The boundaries together must cover the whole length of the lane (the
   * range \[#start_s,#end_s\]) without gap or overlap. The boundaries must be
   * stored in ascending order, starting with the smallest S position.
   * Consecutive boundaries must share a point: the last point of the
   * previous boundary must be identical to the first point of the next
   * boundary.
   *
   * Note: the referenced boundaries may have points outside of
   * \[#start_s,#end_s\] (e.g. a boundary may extend beyond the end of a lane).
   *
   * Note: A curb is a type of LogicalLane and of LaneBoundary.
   * If LogicalLane.Type == TYPE_CURB, by convention this
   * field references the respective LaneBoundary of TYPE_CURB.
   * identically to the right_boundary_id of this LogicalLane.
   *
   * \rules
   * refers_to: LogicalLaneBoundary
   * \endrules
   */
  left_boundary_id: Identifier[];
  /**
   * Lanes that directly are connected to this lane at the beginning.
   *
   * "Beginning" is relative to the reference line, so connections at #start_s.
   *
   * Lane predecessors and successors shall only be used to connect lanes if
   * a physical connection at the beginning or end of both lanes exist. Both
   * lanes have a non-zero width at the connection point and they are
   * semantically connected.
   *
   * A lane may have several predecessors e.g. on intersections, or if a wide
   * lane splits into two, or two merge into one.
   */
  predecessor_lane: LogicalLane_LaneConnection[];
  /**
   * Lanes that directly are connected to this lane at the end.
   *
   * "End" is relative to the reference line, so connections at #end_s.
   *
   * Lane predecessors and successors shall only be used to connect lanes if
   * a physical connection at the beginning or end of both lanes exist. Both
   * lanes have a non-zero width at the connection point and they are
   * semantically connected.
   *
   * A lane may have several successors e.g. on intersections, or if a wide
   * lane splits into two, or two merge into one.
   */
  successor_lane: LogicalLane_LaneConnection[];
  /** Name of the street this lane belongs to. */
  street_name?:
    | string
    | undefined;
  /** A list of traffic rules on the lane. */
  traffic_rule: LogicalLane_TrafficRule[];
}

/**
 * Definition of available lane types.
 *
 * This is mostly aligned with OpenDRIVE, except that lane types modeling
 * access restrictions (e.g. "taxi") are not made available here. These are
 * already deprecated in OpenDRIVE.  To support this, access restrictions
 * should be added later, in alignment with OpenDRIVE.
 */
export enum LogicalLane_Type {
  /** TYPE_UNKNOWN - %Lane of unknown type. Do not use in ground truth. */
  TYPE_UNKNOWN = 0,
  /** TYPE_OTHER - Any other type of lane. */
  TYPE_OTHER = 1,
  /**
   * TYPE_NORMAL - A normal driving lane.
   * Example: Lanes with IDs l1, l2, l3 and l4 in image \ref
   * HighwayExit.
   * This matches the OpenDRIVE type "driving".
   *
   * Note: a lane with OpenDRIVE type "bidirectional" will have an OSI
   * type of TYPE_NORMAL, with <code>#move_direction ==
   * #MOVE_DIRECTION_BOTH_ALLOWED</code>.
   */
  TYPE_NORMAL = 2,
  /**
   * TYPE_BIKING - A lane that is designated for bicycles
   * Note that biking lanes that cross the road (e.g. on an intersection)
   * are also labeled with this type.
   */
  TYPE_BIKING = 3,
  /**
   * TYPE_SIDEWALK - A lane that is designated for pedestrians (sidewalk).
   * Note that pedestrian lanes that cross the road (e.g. on an
   * intersection) are also labeled with this type.
   */
  TYPE_SIDEWALK = 4,
  /** TYPE_PARKING - A lane with parking spaces. */
  TYPE_PARKING = 5,
  /**
   * TYPE_STOP - A hard shoulder on motorways for emergency stops.
   * Example: Lane l5 in image \ref
   * HighwayExit.
   */
  TYPE_STOP = 6,
  /** TYPE_RESTRICTED - A lane on which cars should not drive. */
  TYPE_RESTRICTED = 7,
  /** TYPE_BORDER - A hard border on the edge of a road. */
  TYPE_BORDER = 8,
  /** TYPE_SHOULDER - A soft border on the edge of a road. */
  TYPE_SHOULDER = 9,
  /**
   * TYPE_EXIT - A deceleration lane in parallel to the main road.
   * Example: Lane l6 in image \ref
   * HighwayExit.
   */
  TYPE_EXIT = 10,
  /** TYPE_ENTRY - An acceleration lane in parallel to the main road. */
  TYPE_ENTRY = 11,
  /** TYPE_ONRAMP - A ramp from rural or urban roads joining a motorway. */
  TYPE_ONRAMP = 12,
  /** TYPE_OFFRAMP - A ramp leading off a motorway onto rural or urban roads. */
  TYPE_OFFRAMP = 13,
  /** TYPE_CONNECTINGRAMP - A ramp that connect two motorways. */
  TYPE_CONNECTINGRAMP = 14,
  /**
   * TYPE_MEDIAN - A lane that sits between driving lanes
   * that lead in opposite directions. It is
   * typically used to separate traffic in
   * towns on large roads.
   */
  TYPE_MEDIAN = 15,
  /**
   * TYPE_CURB - Curb stones. Curb stones have a different
   * height than the adjacent drivable lanes.
   */
  TYPE_CURB = 16,
  /**
   * TYPE_RAIL - A rail lane. This lane covers the area a train needs to drive along
   * its rails.
   * #overlapping_lane then describes where a train crosses other lanes.
   */
  TYPE_RAIL = 17,
  /**
   * TYPE_TRAM - A tram lane. This lane covers the area a tram needs to drive along
   * its rails.
   * #overlapping_lane then describes where a tram crosses other lanes.
   */
  TYPE_TRAM = 18,
}

export function logicalLane_TypeFromJSON(object: any): LogicalLane_Type {
  switch (object) {
    case 0:
    case "TYPE_UNKNOWN":
      return LogicalLane_Type.TYPE_UNKNOWN;
    case 1:
    case "TYPE_OTHER":
      return LogicalLane_Type.TYPE_OTHER;
    case 2:
    case "TYPE_NORMAL":
      return LogicalLane_Type.TYPE_NORMAL;
    case 3:
    case "TYPE_BIKING":
      return LogicalLane_Type.TYPE_BIKING;
    case 4:
    case "TYPE_SIDEWALK":
      return LogicalLane_Type.TYPE_SIDEWALK;
    case 5:
    case "TYPE_PARKING":
      return LogicalLane_Type.TYPE_PARKING;
    case 6:
    case "TYPE_STOP":
      return LogicalLane_Type.TYPE_STOP;
    case 7:
    case "TYPE_RESTRICTED":
      return LogicalLane_Type.TYPE_RESTRICTED;
    case 8:
    case "TYPE_BORDER":
      return LogicalLane_Type.TYPE_BORDER;
    case 9:
    case "TYPE_SHOULDER":
      return LogicalLane_Type.TYPE_SHOULDER;
    case 10:
    case "TYPE_EXIT":
      return LogicalLane_Type.TYPE_EXIT;
    case 11:
    case "TYPE_ENTRY":
      return LogicalLane_Type.TYPE_ENTRY;
    case 12:
    case "TYPE_ONRAMP":
      return LogicalLane_Type.TYPE_ONRAMP;
    case 13:
    case "TYPE_OFFRAMP":
      return LogicalLane_Type.TYPE_OFFRAMP;
    case 14:
    case "TYPE_CONNECTINGRAMP":
      return LogicalLane_Type.TYPE_CONNECTINGRAMP;
    case 15:
    case "TYPE_MEDIAN":
      return LogicalLane_Type.TYPE_MEDIAN;
    case 16:
    case "TYPE_CURB":
      return LogicalLane_Type.TYPE_CURB;
    case 17:
    case "TYPE_RAIL":
      return LogicalLane_Type.TYPE_RAIL;
    case 18:
    case "TYPE_TRAM":
      return LogicalLane_Type.TYPE_TRAM;
    default:
      throw new globalThis.Error("Unrecognized enum value " + object + " for enum LogicalLane_Type");
  }
}

export function logicalLane_TypeToJSON(object: LogicalLane_Type): string {
  switch (object) {
    case LogicalLane_Type.TYPE_UNKNOWN:
      return "TYPE_UNKNOWN";
    case LogicalLane_Type.TYPE_OTHER:
      return "TYPE_OTHER";
    case LogicalLane_Type.TYPE_NORMAL:
      return "TYPE_NORMAL";
    case LogicalLane_Type.TYPE_BIKING:
      return "TYPE_BIKING";
    case LogicalLane_Type.TYPE_SIDEWALK:
      return "TYPE_SIDEWALK";
    case LogicalLane_Type.TYPE_PARKING:
      return "TYPE_PARKING";
    case LogicalLane_Type.TYPE_STOP:
      return "TYPE_STOP";
    case LogicalLane_Type.TYPE_RESTRICTED:
      return "TYPE_RESTRICTED";
    case LogicalLane_Type.TYPE_BORDER:
      return "TYPE_BORDER";
    case LogicalLane_Type.TYPE_SHOULDER:
      return "TYPE_SHOULDER";
    case LogicalLane_Type.TYPE_EXIT:
      return "TYPE_EXIT";
    case LogicalLane_Type.TYPE_ENTRY:
      return "TYPE_ENTRY";
    case LogicalLane_Type.TYPE_ONRAMP:
      return "TYPE_ONRAMP";
    case LogicalLane_Type.TYPE_OFFRAMP:
      return "TYPE_OFFRAMP";
    case LogicalLane_Type.TYPE_CONNECTINGRAMP:
      return "TYPE_CONNECTINGRAMP";
    case LogicalLane_Type.TYPE_MEDIAN:
      return "TYPE_MEDIAN";
    case LogicalLane_Type.TYPE_CURB:
      return "TYPE_CURB";
    case LogicalLane_Type.TYPE_RAIL:
      return "TYPE_RAIL";
    case LogicalLane_Type.TYPE_TRAM:
      return "TYPE_TRAM";
    default:
      throw new globalThis.Error("Unrecognized enum value " + object + " for enum LogicalLane_Type");
  }
}

/**
 * Describes in which direction moving objects may typically move along a
 * lane.
 *
 * This describes the allowed typical driving direction on a lane, or (in
 * the case of pedestrian) the allowed walking direction.
 *
 * Note: Allowed overtaking (e.g. on country roads) does not automatically
 * make a lane bidirectional, since vehicles may normally only drive in the
 * other direction during the overtake maneuver, not for longer periods of
 * time.
 */
export enum LogicalLane_MoveDirection {
  /** MOVE_DIRECTION_UNKNOWN - Move direction is unknown. Do not use in ground truth. */
  MOVE_DIRECTION_UNKNOWN = 0,
  /**
   * MOVE_DIRECTION_OTHER - Move direction fits neither of the other categories.
   *
   * Example: a lane where cars may only drive in one direction, but
   * bikes may drive in both.
   */
  MOVE_DIRECTION_OTHER = 1,
  /**
   * MOVE_DIRECTION_INCREASING_S - Objects may move in increasing S direction.
   *
   * This means they move in the same direction as the reference line.
   */
  MOVE_DIRECTION_INCREASING_S = 2,
  /**
   * MOVE_DIRECTION_DECREASING_S - Objects may move in decreasing S direction.
   *
   * This means they move in the opposite direction as the reference line.
   */
  MOVE_DIRECTION_DECREASING_S = 3,
  /** MOVE_DIRECTION_BOTH_ALLOWED - Objects may move in both directions. */
  MOVE_DIRECTION_BOTH_ALLOWED = 4,
}

export function logicalLane_MoveDirectionFromJSON(object: any): LogicalLane_MoveDirection {
  switch (object) {
    case 0:
    case "MOVE_DIRECTION_UNKNOWN":
      return LogicalLane_MoveDirection.MOVE_DIRECTION_UNKNOWN;
    case 1:
    case "MOVE_DIRECTION_OTHER":
      return LogicalLane_MoveDirection.MOVE_DIRECTION_OTHER;
    case 2:
    case "MOVE_DIRECTION_INCREASING_S":
      return LogicalLane_MoveDirection.MOVE_DIRECTION_INCREASING_S;
    case 3:
    case "MOVE_DIRECTION_DECREASING_S":
      return LogicalLane_MoveDirection.MOVE_DIRECTION_DECREASING_S;
    case 4:
    case "MOVE_DIRECTION_BOTH_ALLOWED":
      return LogicalLane_MoveDirection.MOVE_DIRECTION_BOTH_ALLOWED;
    default:
      throw new globalThis.Error("Unrecognized enum value " + object + " for enum LogicalLane_MoveDirection");
  }
}

export function logicalLane_MoveDirectionToJSON(object: LogicalLane_MoveDirection): string {
  switch (object) {
    case LogicalLane_MoveDirection.MOVE_DIRECTION_UNKNOWN:
      return "MOVE_DIRECTION_UNKNOWN";
    case LogicalLane_MoveDirection.MOVE_DIRECTION_OTHER:
      return "MOVE_DIRECTION_OTHER";
    case LogicalLane_MoveDirection.MOVE_DIRECTION_INCREASING_S:
      return "MOVE_DIRECTION_INCREASING_S";
    case LogicalLane_MoveDirection.MOVE_DIRECTION_DECREASING_S:
      return "MOVE_DIRECTION_DECREASING_S";
    case LogicalLane_MoveDirection.MOVE_DIRECTION_BOTH_ALLOWED:
      return "MOVE_DIRECTION_BOTH_ALLOWED";
    default:
      throw new globalThis.Error("Unrecognized enum value " + object + " for enum LogicalLane_MoveDirection");
  }
}

/** \brief Reference to a physical lane. */
export interface LogicalLane_PhysicalLaneReference {
  /**
   * Id of the physical lane referenced.
   *
   * \rules
   * refers_to: Lane
   * \endrules
   */
  physical_lane_id?:
    | Identifier
    | undefined;
  /** S position on the logical lane where the physical lane starts. */
  start_s?:
    | number
    | undefined;
  /**
   * S position on the logical lane where the physical lane ends.
   *
   * Requirement: #end_s > #start_s
   */
  end_s?: number | undefined;
}

/** \brief Connection to another lane (predecessor or successor) */
export interface LogicalLane_LaneConnection {
  /**
   * Id of the other logical lane that is connected.
   *
   * \rules
   * refers_to: LogicalLane
   * \endrules
   */
  other_lane_id?:
    | Identifier
    | undefined;
  /**
   * If true: LaneConnection is at the beginning of the other lane
   * If false: LaneConnection is a the end of the other lane
   */
  at_begin_of_other_lane?: boolean | undefined;
}

/** \brief Relation of this lane to another logical lane */
export interface LogicalLane_LaneRelation {
  /**
   * Id of the other logical lane.
   *
   * \rules
   * refers_to: LogicalLane
   * \endrules
   */
  other_lane_id?:
    | Identifier
    | undefined;
  /** Start s position of the relation. */
  start_s?:
    | number
    | undefined;
  /**
   * End s position of the relation.
   *
   * Requirement: #end_s > #start_s
   */
  end_s?:
    | number
    | undefined;
  /**
   * Start s position of the relation on the other lane.
   *
   * This is the same place as #start_s, but measured along the reference
   * line of the other lane.
   */
  start_s_other?:
    | number
    | undefined;
  /**
   * End s position of the relation on the other lane.
   *
   * This is the same place as #end_s, but measured along the reference
   * line of the other lane.
   *
   * Note: #end_s_other might be smaller than #start_s_other
   */
  end_s_other?: number | undefined;
}

/**
 * Describes traffic rules on a lane.
 * The traffic rule can thereby be induced by regulations, traffic signs
 * or by other means. If the modeled traffic rule is induced by a traffic sign
 * the information should be identical with the respective traffic sign.
 *
 * Note: Every instance should be corresponding to only one specific rule.
 * The type of the traffic rule should be set using the respective field.
 * Additionally, every message should contain the traffic rule validity information
 * and the respective field for the respective traffic rule type.
 * In case of traffic rule (priority) conflicts for rules of the same type that
 * can not be depicted using the traffic rule validity only the currently
 * valid rule should be provided.
 *
 * Note: Each traffic rule corresponds to only one lane. If the traffic rule
 * is also valid on adjacent/successor/predecessor lanes it needs to be
 * specified for each lane individually.
 *
 * \brief Logical Model of a traffic rule on a lane.
 */
export interface LogicalLane_TrafficRule {
  /**
   * The type of the traffic rule.
   *
   * This specifies the type of the traffic rule to be modeled.
   * Based on the type the respective message containing the information
   * corresponding to the traffic rule should be filled.
   */
  traffic_rule_type?:
    | LogicalLane_TrafficRule_TrafficRuleType
    | undefined;
  /** The validity information of the traffic rule. */
  traffic_rule_validity?:
    | LogicalLane_TrafficRule_TrafficRuleValidity
    | undefined;
  /** Traffic rule information for traffic rule of type speed limit. */
  speed_limit?: LogicalLane_TrafficRule_SpeedLimit | undefined;
}

/** The type of the the traffic rule. */
export enum LogicalLane_TrafficRule_TrafficRuleType {
  /** TRAFFIC_RULE_TYPE_SPEED_LIMIT - Traffic rule is of type speed limit */
  TRAFFIC_RULE_TYPE_SPEED_LIMIT = 0,
}

export function logicalLane_TrafficRule_TrafficRuleTypeFromJSON(object: any): LogicalLane_TrafficRule_TrafficRuleType {
  switch (object) {
    case 0:
    case "TRAFFIC_RULE_TYPE_SPEED_LIMIT":
      return LogicalLane_TrafficRule_TrafficRuleType.TRAFFIC_RULE_TYPE_SPEED_LIMIT;
    default:
      throw new globalThis.Error(
        "Unrecognized enum value " + object + " for enum LogicalLane_TrafficRule_TrafficRuleType",
      );
  }
}

export function logicalLane_TrafficRule_TrafficRuleTypeToJSON(object: LogicalLane_TrafficRule_TrafficRuleType): string {
  switch (object) {
    case LogicalLane_TrafficRule_TrafficRuleType.TRAFFIC_RULE_TYPE_SPEED_LIMIT:
      return "TRAFFIC_RULE_TYPE_SPEED_LIMIT";
    default:
      throw new globalThis.Error(
        "Unrecognized enum value " + object + " for enum LogicalLane_TrafficRule_TrafficRuleType",
      );
  }
}

/** \brief Validity information for a traffic rule. */
export interface LogicalLane_TrafficRule_TrafficRuleValidity {
  /**
   * The starting point of the traffic rule validity on the lane.
   * Must be in range [\c sStart,\c sEnd] of the reference line.
   *
   * Note: The traffic rule applies only to traffic with notional
   * direction of travel from the start_s coordinate towards
   * the end_s coordinate. For unidirectional lanes this must
   * match the direction of travel as specified by the
   * move_direction field of the logical lane. For bidirectional
   * lanes this allows the specification of separate rules for
   * each direction of travel.
   */
  start_s?:
    | number
    | undefined;
  /**
   * The ending point of the traffic rule validity on the lane.
   * Must be in range [\c sStart,\c sEnd] of the reference line.
   */
  end_s?:
    | number
    | undefined;
  /**
   * List of traffic participant types for which the speed limit is valid.
   * If the traffic rule validity is independent of the vehicle type
   * the list should be empty.
   */
  valid_for_type: LogicalLane_TrafficRule_TrafficRuleValidity_TypeValidity[];
}

/** \brief Type of traffic participant for which a rule is valid. */
export interface LogicalLane_TrafficRule_TrafficRuleValidity_TypeValidity {
  /** The type of object for which the traffic rule is valid. */
  type?:
    | MovingObject_Type
    | undefined;
  /**
   * Vehicle classification type for traffic participants.
   *
   * Should be set to TYPE_UNKNOWN if type is not TYPE_VEHICLE
   * or the rule is valid for all vehicle types.
   */
  vehicle_type?:
    | MovingObject_VehicleClassification_Type
    | undefined;
  /**
   * Role of traffic participant.
   *
   * Should be set to ROLE_UNKNOWN if type is not TYPE_VEHICLE
   * or the rule is valid for all vehicle roles.
   */
  vehicle_role?: MovingObject_VehicleClassification_Role | undefined;
}

/** \brief Speed limit on a lane. */
export interface LogicalLane_TrafficRule_SpeedLimit {
  /**
   * The value of the speed limit.
   * The unit field in the TrafficSignValue message may only be set to
   * units associated with velocities and must not be UNKNOWN.
   *
   * Note: All speed limits are to be modeled this way, independent
   * of how they are induced.
   */
  speed_limit_value?: TrafficSignValue | undefined;
}

function createBaseLogicalLaneBoundary(): LogicalLaneBoundary {
  return {
    id: undefined,
    boundary_line: [],
    reference_line_id: undefined,
    physical_boundary_id: [],
    passing_rule: 0,
    source_reference: [],
  };
}

export const LogicalLaneBoundary: MessageFns<LogicalLaneBoundary> = {
  encode(message: LogicalLaneBoundary, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== undefined) {
      Identifier.encode(message.id, writer.uint32(10).fork()).join();
    }
    for (const v of message.boundary_line) {
      LogicalLaneBoundary_LogicalBoundaryPoint.encode(v!, writer.uint32(18).fork()).join();
    }
    if (message.reference_line_id !== undefined) {
      Identifier.encode(message.reference_line_id, writer.uint32(26).fork()).join();
    }
    for (const v of message.physical_boundary_id) {
      Identifier.encode(v!, writer.uint32(34).fork()).join();
    }
    if (message.passing_rule !== undefined && message.passing_rule !== 0) {
      writer.uint32(40).int32(message.passing_rule);
    }
    for (const v of message.source_reference) {
      ExternalReference.encode(v!, writer.uint32(50).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LogicalLaneBoundary {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLogicalLaneBoundary();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = Identifier.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.boundary_line.push(LogicalLaneBoundary_LogicalBoundaryPoint.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.reference_line_id = Identifier.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.physical_boundary_id.push(Identifier.decode(reader, reader.uint32()));
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.passing_rule = reader.int32() as any;
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.source_reference.push(ExternalReference.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LogicalLaneBoundary {
    return {
      id: isSet(object.id) ? Identifier.fromJSON(object.id) : undefined,
      boundary_line: globalThis.Array.isArray(object?.boundary_line)
        ? object.boundary_line.map((e: any) => LogicalLaneBoundary_LogicalBoundaryPoint.fromJSON(e))
        : [],
      reference_line_id: isSet(object.reference_line_id) ? Identifier.fromJSON(object.reference_line_id) : undefined,
      physical_boundary_id: globalThis.Array.isArray(object?.physical_boundary_id)
        ? object.physical_boundary_id.map((e: any) => Identifier.fromJSON(e))
        : [],
      passing_rule: isSet(object.passing_rule) ? logicalLaneBoundary_PassingRuleFromJSON(object.passing_rule) : 0,
      source_reference: globalThis.Array.isArray(object?.source_reference)
        ? object.source_reference.map((e: any) => ExternalReference.fromJSON(e))
        : [],
    };
  },

  toJSON(message: LogicalLaneBoundary): unknown {
    const obj: any = {};
    if (message.id !== undefined) {
      obj.id = Identifier.toJSON(message.id);
    }
    if (message.boundary_line?.length) {
      obj.boundary_line = message.boundary_line.map((e) => LogicalLaneBoundary_LogicalBoundaryPoint.toJSON(e));
    }
    if (message.reference_line_id !== undefined) {
      obj.reference_line_id = Identifier.toJSON(message.reference_line_id);
    }
    if (message.physical_boundary_id?.length) {
      obj.physical_boundary_id = message.physical_boundary_id.map((e) => Identifier.toJSON(e));
    }
    if (message.passing_rule !== undefined) {
      obj.passing_rule = logicalLaneBoundary_PassingRuleToJSON(message.passing_rule);
    }
    if (message.source_reference?.length) {
      obj.source_reference = message.source_reference.map((e) => ExternalReference.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LogicalLaneBoundary>, I>>(base?: I): LogicalLaneBoundary {
    return LogicalLaneBoundary.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LogicalLaneBoundary>, I>>(object: I): LogicalLaneBoundary {
    const message = createBaseLogicalLaneBoundary();
    message.id = (object.id !== undefined && object.id !== null) ? Identifier.fromPartial(object.id) : undefined;
    message.boundary_line = object.boundary_line?.map((e) => LogicalLaneBoundary_LogicalBoundaryPoint.fromPartial(e)) ||
      [];
    message.reference_line_id = (object.reference_line_id !== undefined && object.reference_line_id !== null)
      ? Identifier.fromPartial(object.reference_line_id)
      : undefined;
    message.physical_boundary_id = object.physical_boundary_id?.map((e) => Identifier.fromPartial(e)) || [];
    message.passing_rule = object.passing_rule ?? 0;
    message.source_reference = object.source_reference?.map((e) => ExternalReference.fromPartial(e)) || [];
    return message;
  },
};

function createBaseLogicalLaneBoundary_LogicalBoundaryPoint(): LogicalLaneBoundary_LogicalBoundaryPoint {
  return { position: undefined, s_position: 0, t_position: 0 };
}

export const LogicalLaneBoundary_LogicalBoundaryPoint: MessageFns<LogicalLaneBoundary_LogicalBoundaryPoint> = {
  encode(message: LogicalLaneBoundary_LogicalBoundaryPoint, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.position !== undefined) {
      Vector3d.encode(message.position, writer.uint32(10).fork()).join();
    }
    if (message.s_position !== undefined && message.s_position !== 0) {
      writer.uint32(17).double(message.s_position);
    }
    if (message.t_position !== undefined && message.t_position !== 0) {
      writer.uint32(25).double(message.t_position);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LogicalLaneBoundary_LogicalBoundaryPoint {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLogicalLaneBoundary_LogicalBoundaryPoint();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.position = Vector3d.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 17) {
            break;
          }

          message.s_position = reader.double();
          continue;
        }
        case 3: {
          if (tag !== 25) {
            break;
          }

          message.t_position = reader.double();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LogicalLaneBoundary_LogicalBoundaryPoint {
    return {
      position: isSet(object.position) ? Vector3d.fromJSON(object.position) : undefined,
      s_position: isSet(object.s_position) ? globalThis.Number(object.s_position) : 0,
      t_position: isSet(object.t_position) ? globalThis.Number(object.t_position) : 0,
    };
  },

  toJSON(message: LogicalLaneBoundary_LogicalBoundaryPoint): unknown {
    const obj: any = {};
    if (message.position !== undefined) {
      obj.position = Vector3d.toJSON(message.position);
    }
    if (message.s_position !== undefined) {
      obj.s_position = message.s_position;
    }
    if (message.t_position !== undefined) {
      obj.t_position = message.t_position;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LogicalLaneBoundary_LogicalBoundaryPoint>, I>>(
    base?: I,
  ): LogicalLaneBoundary_LogicalBoundaryPoint {
    return LogicalLaneBoundary_LogicalBoundaryPoint.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LogicalLaneBoundary_LogicalBoundaryPoint>, I>>(
    object: I,
  ): LogicalLaneBoundary_LogicalBoundaryPoint {
    const message = createBaseLogicalLaneBoundary_LogicalBoundaryPoint();
    message.position = (object.position !== undefined && object.position !== null)
      ? Vector3d.fromPartial(object.position)
      : undefined;
    message.s_position = object.s_position ?? 0;
    message.t_position = object.t_position ?? 0;
    return message;
  },
};

function createBaseLogicalLane(): LogicalLane {
  return {
    id: undefined,
    type: 0,
    source_reference: [],
    physical_lane_reference: [],
    reference_line_id: undefined,
    start_s: 0,
    end_s: 0,
    move_direction: 0,
    right_adjacent_lane: [],
    left_adjacent_lane: [],
    overlapping_lane: [],
    right_boundary_id: [],
    left_boundary_id: [],
    predecessor_lane: [],
    successor_lane: [],
    street_name: "",
    traffic_rule: [],
  };
}

export const LogicalLane: MessageFns<LogicalLane> = {
  encode(message: LogicalLane, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== undefined) {
      Identifier.encode(message.id, writer.uint32(10).fork()).join();
    }
    if (message.type !== undefined && message.type !== 0) {
      writer.uint32(16).int32(message.type);
    }
    for (const v of message.source_reference) {
      ExternalReference.encode(v!, writer.uint32(26).fork()).join();
    }
    for (const v of message.physical_lane_reference) {
      LogicalLane_PhysicalLaneReference.encode(v!, writer.uint32(34).fork()).join();
    }
    if (message.reference_line_id !== undefined) {
      Identifier.encode(message.reference_line_id, writer.uint32(42).fork()).join();
    }
    if (message.start_s !== undefined && message.start_s !== 0) {
      writer.uint32(49).double(message.start_s);
    }
    if (message.end_s !== undefined && message.end_s !== 0) {
      writer.uint32(57).double(message.end_s);
    }
    if (message.move_direction !== undefined && message.move_direction !== 0) {
      writer.uint32(64).int32(message.move_direction);
    }
    for (const v of message.right_adjacent_lane) {
      LogicalLane_LaneRelation.encode(v!, writer.uint32(74).fork()).join();
    }
    for (const v of message.left_adjacent_lane) {
      LogicalLane_LaneRelation.encode(v!, writer.uint32(82).fork()).join();
    }
    for (const v of message.overlapping_lane) {
      LogicalLane_LaneRelation.encode(v!, writer.uint32(90).fork()).join();
    }
    for (const v of message.right_boundary_id) {
      Identifier.encode(v!, writer.uint32(98).fork()).join();
    }
    for (const v of message.left_boundary_id) {
      Identifier.encode(v!, writer.uint32(106).fork()).join();
    }
    for (const v of message.predecessor_lane) {
      LogicalLane_LaneConnection.encode(v!, writer.uint32(114).fork()).join();
    }
    for (const v of message.successor_lane) {
      LogicalLane_LaneConnection.encode(v!, writer.uint32(122).fork()).join();
    }
    if (message.street_name !== undefined && message.street_name !== "") {
      writer.uint32(130).string(message.street_name);
    }
    for (const v of message.traffic_rule) {
      LogicalLane_TrafficRule.encode(v!, writer.uint32(138).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LogicalLane {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLogicalLane();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = Identifier.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.type = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.source_reference.push(ExternalReference.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.physical_lane_reference.push(LogicalLane_PhysicalLaneReference.decode(reader, reader.uint32()));
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.reference_line_id = Identifier.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 49) {
            break;
          }

          message.start_s = reader.double();
          continue;
        }
        case 7: {
          if (tag !== 57) {
            break;
          }

          message.end_s = reader.double();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.move_direction = reader.int32() as any;
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.right_adjacent_lane.push(LogicalLane_LaneRelation.decode(reader, reader.uint32()));
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.left_adjacent_lane.push(LogicalLane_LaneRelation.decode(reader, reader.uint32()));
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.overlapping_lane.push(LogicalLane_LaneRelation.decode(reader, reader.uint32()));
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.right_boundary_id.push(Identifier.decode(reader, reader.uint32()));
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.left_boundary_id.push(Identifier.decode(reader, reader.uint32()));
          continue;
        }
        case 14: {
          if (tag !== 114) {
            break;
          }

          message.predecessor_lane.push(LogicalLane_LaneConnection.decode(reader, reader.uint32()));
          continue;
        }
        case 15: {
          if (tag !== 122) {
            break;
          }

          message.successor_lane.push(LogicalLane_LaneConnection.decode(reader, reader.uint32()));
          continue;
        }
        case 16: {
          if (tag !== 130) {
            break;
          }

          message.street_name = reader.string();
          continue;
        }
        case 17: {
          if (tag !== 138) {
            break;
          }

          message.traffic_rule.push(LogicalLane_TrafficRule.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LogicalLane {
    return {
      id: isSet(object.id) ? Identifier.fromJSON(object.id) : undefined,
      type: isSet(object.type) ? logicalLane_TypeFromJSON(object.type) : 0,
      source_reference: globalThis.Array.isArray(object?.source_reference)
        ? object.source_reference.map((e: any) => ExternalReference.fromJSON(e))
        : [],
      physical_lane_reference: globalThis.Array.isArray(object?.physical_lane_reference)
        ? object.physical_lane_reference.map((e: any) => LogicalLane_PhysicalLaneReference.fromJSON(e))
        : [],
      reference_line_id: isSet(object.reference_line_id) ? Identifier.fromJSON(object.reference_line_id) : undefined,
      start_s: isSet(object.start_s) ? globalThis.Number(object.start_s) : 0,
      end_s: isSet(object.end_s) ? globalThis.Number(object.end_s) : 0,
      move_direction: isSet(object.move_direction) ? logicalLane_MoveDirectionFromJSON(object.move_direction) : 0,
      right_adjacent_lane: globalThis.Array.isArray(object?.right_adjacent_lane)
        ? object.right_adjacent_lane.map((e: any) => LogicalLane_LaneRelation.fromJSON(e))
        : [],
      left_adjacent_lane: globalThis.Array.isArray(object?.left_adjacent_lane)
        ? object.left_adjacent_lane.map((e: any) => LogicalLane_LaneRelation.fromJSON(e))
        : [],
      overlapping_lane: globalThis.Array.isArray(object?.overlapping_lane)
        ? object.overlapping_lane.map((e: any) => LogicalLane_LaneRelation.fromJSON(e))
        : [],
      right_boundary_id: globalThis.Array.isArray(object?.right_boundary_id)
        ? object.right_boundary_id.map((e: any) => Identifier.fromJSON(e))
        : [],
      left_boundary_id: globalThis.Array.isArray(object?.left_boundary_id)
        ? object.left_boundary_id.map((e: any) => Identifier.fromJSON(e))
        : [],
      predecessor_lane: globalThis.Array.isArray(object?.predecessor_lane)
        ? object.predecessor_lane.map((e: any) => LogicalLane_LaneConnection.fromJSON(e))
        : [],
      successor_lane: globalThis.Array.isArray(object?.successor_lane)
        ? object.successor_lane.map((e: any) => LogicalLane_LaneConnection.fromJSON(e))
        : [],
      street_name: isSet(object.street_name) ? globalThis.String(object.street_name) : "",
      traffic_rule: globalThis.Array.isArray(object?.traffic_rule)
        ? object.traffic_rule.map((e: any) => LogicalLane_TrafficRule.fromJSON(e))
        : [],
    };
  },

  toJSON(message: LogicalLane): unknown {
    const obj: any = {};
    if (message.id !== undefined) {
      obj.id = Identifier.toJSON(message.id);
    }
    if (message.type !== undefined) {
      obj.type = logicalLane_TypeToJSON(message.type);
    }
    if (message.source_reference?.length) {
      obj.source_reference = message.source_reference.map((e) => ExternalReference.toJSON(e));
    }
    if (message.physical_lane_reference?.length) {
      obj.physical_lane_reference = message.physical_lane_reference.map((e) =>
        LogicalLane_PhysicalLaneReference.toJSON(e)
      );
    }
    if (message.reference_line_id !== undefined) {
      obj.reference_line_id = Identifier.toJSON(message.reference_line_id);
    }
    if (message.start_s !== undefined) {
      obj.start_s = message.start_s;
    }
    if (message.end_s !== undefined) {
      obj.end_s = message.end_s;
    }
    if (message.move_direction !== undefined) {
      obj.move_direction = logicalLane_MoveDirectionToJSON(message.move_direction);
    }
    if (message.right_adjacent_lane?.length) {
      obj.right_adjacent_lane = message.right_adjacent_lane.map((e) => LogicalLane_LaneRelation.toJSON(e));
    }
    if (message.left_adjacent_lane?.length) {
      obj.left_adjacent_lane = message.left_adjacent_lane.map((e) => LogicalLane_LaneRelation.toJSON(e));
    }
    if (message.overlapping_lane?.length) {
      obj.overlapping_lane = message.overlapping_lane.map((e) => LogicalLane_LaneRelation.toJSON(e));
    }
    if (message.right_boundary_id?.length) {
      obj.right_boundary_id = message.right_boundary_id.map((e) => Identifier.toJSON(e));
    }
    if (message.left_boundary_id?.length) {
      obj.left_boundary_id = message.left_boundary_id.map((e) => Identifier.toJSON(e));
    }
    if (message.predecessor_lane?.length) {
      obj.predecessor_lane = message.predecessor_lane.map((e) => LogicalLane_LaneConnection.toJSON(e));
    }
    if (message.successor_lane?.length) {
      obj.successor_lane = message.successor_lane.map((e) => LogicalLane_LaneConnection.toJSON(e));
    }
    if (message.street_name !== undefined) {
      obj.street_name = message.street_name;
    }
    if (message.traffic_rule?.length) {
      obj.traffic_rule = message.traffic_rule.map((e) => LogicalLane_TrafficRule.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LogicalLane>, I>>(base?: I): LogicalLane {
    return LogicalLane.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LogicalLane>, I>>(object: I): LogicalLane {
    const message = createBaseLogicalLane();
    message.id = (object.id !== undefined && object.id !== null) ? Identifier.fromPartial(object.id) : undefined;
    message.type = object.type ?? 0;
    message.source_reference = object.source_reference?.map((e) => ExternalReference.fromPartial(e)) || [];
    message.physical_lane_reference =
      object.physical_lane_reference?.map((e) => LogicalLane_PhysicalLaneReference.fromPartial(e)) || [];
    message.reference_line_id = (object.reference_line_id !== undefined && object.reference_line_id !== null)
      ? Identifier.fromPartial(object.reference_line_id)
      : undefined;
    message.start_s = object.start_s ?? 0;
    message.end_s = object.end_s ?? 0;
    message.move_direction = object.move_direction ?? 0;
    message.right_adjacent_lane = object.right_adjacent_lane?.map((e) => LogicalLane_LaneRelation.fromPartial(e)) || [];
    message.left_adjacent_lane = object.left_adjacent_lane?.map((e) => LogicalLane_LaneRelation.fromPartial(e)) || [];
    message.overlapping_lane = object.overlapping_lane?.map((e) => LogicalLane_LaneRelation.fromPartial(e)) || [];
    message.right_boundary_id = object.right_boundary_id?.map((e) => Identifier.fromPartial(e)) || [];
    message.left_boundary_id = object.left_boundary_id?.map((e) => Identifier.fromPartial(e)) || [];
    message.predecessor_lane = object.predecessor_lane?.map((e) => LogicalLane_LaneConnection.fromPartial(e)) || [];
    message.successor_lane = object.successor_lane?.map((e) => LogicalLane_LaneConnection.fromPartial(e)) || [];
    message.street_name = object.street_name ?? "";
    message.traffic_rule = object.traffic_rule?.map((e) => LogicalLane_TrafficRule.fromPartial(e)) || [];
    return message;
  },
};

function createBaseLogicalLane_PhysicalLaneReference(): LogicalLane_PhysicalLaneReference {
  return { physical_lane_id: undefined, start_s: 0, end_s: 0 };
}

export const LogicalLane_PhysicalLaneReference: MessageFns<LogicalLane_PhysicalLaneReference> = {
  encode(message: LogicalLane_PhysicalLaneReference, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.physical_lane_id !== undefined) {
      Identifier.encode(message.physical_lane_id, writer.uint32(10).fork()).join();
    }
    if (message.start_s !== undefined && message.start_s !== 0) {
      writer.uint32(17).double(message.start_s);
    }
    if (message.end_s !== undefined && message.end_s !== 0) {
      writer.uint32(25).double(message.end_s);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LogicalLane_PhysicalLaneReference {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLogicalLane_PhysicalLaneReference();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.physical_lane_id = Identifier.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 17) {
            break;
          }

          message.start_s = reader.double();
          continue;
        }
        case 3: {
          if (tag !== 25) {
            break;
          }

          message.end_s = reader.double();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LogicalLane_PhysicalLaneReference {
    return {
      physical_lane_id: isSet(object.physical_lane_id) ? Identifier.fromJSON(object.physical_lane_id) : undefined,
      start_s: isSet(object.start_s) ? globalThis.Number(object.start_s) : 0,
      end_s: isSet(object.end_s) ? globalThis.Number(object.end_s) : 0,
    };
  },

  toJSON(message: LogicalLane_PhysicalLaneReference): unknown {
    const obj: any = {};
    if (message.physical_lane_id !== undefined) {
      obj.physical_lane_id = Identifier.toJSON(message.physical_lane_id);
    }
    if (message.start_s !== undefined) {
      obj.start_s = message.start_s;
    }
    if (message.end_s !== undefined) {
      obj.end_s = message.end_s;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LogicalLane_PhysicalLaneReference>, I>>(
    base?: I,
  ): LogicalLane_PhysicalLaneReference {
    return LogicalLane_PhysicalLaneReference.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LogicalLane_PhysicalLaneReference>, I>>(
    object: I,
  ): LogicalLane_PhysicalLaneReference {
    const message = createBaseLogicalLane_PhysicalLaneReference();
    message.physical_lane_id = (object.physical_lane_id !== undefined && object.physical_lane_id !== null)
      ? Identifier.fromPartial(object.physical_lane_id)
      : undefined;
    message.start_s = object.start_s ?? 0;
    message.end_s = object.end_s ?? 0;
    return message;
  },
};

function createBaseLogicalLane_LaneConnection(): LogicalLane_LaneConnection {
  return { other_lane_id: undefined, at_begin_of_other_lane: false };
}

export const LogicalLane_LaneConnection: MessageFns<LogicalLane_LaneConnection> = {
  encode(message: LogicalLane_LaneConnection, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.other_lane_id !== undefined) {
      Identifier.encode(message.other_lane_id, writer.uint32(10).fork()).join();
    }
    if (message.at_begin_of_other_lane !== undefined && message.at_begin_of_other_lane !== false) {
      writer.uint32(16).bool(message.at_begin_of_other_lane);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LogicalLane_LaneConnection {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLogicalLane_LaneConnection();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.other_lane_id = Identifier.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.at_begin_of_other_lane = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LogicalLane_LaneConnection {
    return {
      other_lane_id: isSet(object.other_lane_id) ? Identifier.fromJSON(object.other_lane_id) : undefined,
      at_begin_of_other_lane: isSet(object.at_begin_of_other_lane)
        ? globalThis.Boolean(object.at_begin_of_other_lane)
        : false,
    };
  },

  toJSON(message: LogicalLane_LaneConnection): unknown {
    const obj: any = {};
    if (message.other_lane_id !== undefined) {
      obj.other_lane_id = Identifier.toJSON(message.other_lane_id);
    }
    if (message.at_begin_of_other_lane !== undefined) {
      obj.at_begin_of_other_lane = message.at_begin_of_other_lane;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LogicalLane_LaneConnection>, I>>(base?: I): LogicalLane_LaneConnection {
    return LogicalLane_LaneConnection.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LogicalLane_LaneConnection>, I>>(object: I): LogicalLane_LaneConnection {
    const message = createBaseLogicalLane_LaneConnection();
    message.other_lane_id = (object.other_lane_id !== undefined && object.other_lane_id !== null)
      ? Identifier.fromPartial(object.other_lane_id)
      : undefined;
    message.at_begin_of_other_lane = object.at_begin_of_other_lane ?? false;
    return message;
  },
};

function createBaseLogicalLane_LaneRelation(): LogicalLane_LaneRelation {
  return { other_lane_id: undefined, start_s: 0, end_s: 0, start_s_other: 0, end_s_other: 0 };
}

export const LogicalLane_LaneRelation: MessageFns<LogicalLane_LaneRelation> = {
  encode(message: LogicalLane_LaneRelation, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.other_lane_id !== undefined) {
      Identifier.encode(message.other_lane_id, writer.uint32(10).fork()).join();
    }
    if (message.start_s !== undefined && message.start_s !== 0) {
      writer.uint32(17).double(message.start_s);
    }
    if (message.end_s !== undefined && message.end_s !== 0) {
      writer.uint32(25).double(message.end_s);
    }
    if (message.start_s_other !== undefined && message.start_s_other !== 0) {
      writer.uint32(33).double(message.start_s_other);
    }
    if (message.end_s_other !== undefined && message.end_s_other !== 0) {
      writer.uint32(41).double(message.end_s_other);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LogicalLane_LaneRelation {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLogicalLane_LaneRelation();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.other_lane_id = Identifier.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 17) {
            break;
          }

          message.start_s = reader.double();
          continue;
        }
        case 3: {
          if (tag !== 25) {
            break;
          }

          message.end_s = reader.double();
          continue;
        }
        case 4: {
          if (tag !== 33) {
            break;
          }

          message.start_s_other = reader.double();
          continue;
        }
        case 5: {
          if (tag !== 41) {
            break;
          }

          message.end_s_other = reader.double();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LogicalLane_LaneRelation {
    return {
      other_lane_id: isSet(object.other_lane_id) ? Identifier.fromJSON(object.other_lane_id) : undefined,
      start_s: isSet(object.start_s) ? globalThis.Number(object.start_s) : 0,
      end_s: isSet(object.end_s) ? globalThis.Number(object.end_s) : 0,
      start_s_other: isSet(object.start_s_other) ? globalThis.Number(object.start_s_other) : 0,
      end_s_other: isSet(object.end_s_other) ? globalThis.Number(object.end_s_other) : 0,
    };
  },

  toJSON(message: LogicalLane_LaneRelation): unknown {
    const obj: any = {};
    if (message.other_lane_id !== undefined) {
      obj.other_lane_id = Identifier.toJSON(message.other_lane_id);
    }
    if (message.start_s !== undefined) {
      obj.start_s = message.start_s;
    }
    if (message.end_s !== undefined) {
      obj.end_s = message.end_s;
    }
    if (message.start_s_other !== undefined) {
      obj.start_s_other = message.start_s_other;
    }
    if (message.end_s_other !== undefined) {
      obj.end_s_other = message.end_s_other;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LogicalLane_LaneRelation>, I>>(base?: I): LogicalLane_LaneRelation {
    return LogicalLane_LaneRelation.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LogicalLane_LaneRelation>, I>>(object: I): LogicalLane_LaneRelation {
    const message = createBaseLogicalLane_LaneRelation();
    message.other_lane_id = (object.other_lane_id !== undefined && object.other_lane_id !== null)
      ? Identifier.fromPartial(object.other_lane_id)
      : undefined;
    message.start_s = object.start_s ?? 0;
    message.end_s = object.end_s ?? 0;
    message.start_s_other = object.start_s_other ?? 0;
    message.end_s_other = object.end_s_other ?? 0;
    return message;
  },
};

function createBaseLogicalLane_TrafficRule(): LogicalLane_TrafficRule {
  return { traffic_rule_type: 0, traffic_rule_validity: undefined, speed_limit: undefined };
}

export const LogicalLane_TrafficRule: MessageFns<LogicalLane_TrafficRule> = {
  encode(message: LogicalLane_TrafficRule, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.traffic_rule_type !== undefined && message.traffic_rule_type !== 0) {
      writer.uint32(8).int32(message.traffic_rule_type);
    }
    if (message.traffic_rule_validity !== undefined) {
      LogicalLane_TrafficRule_TrafficRuleValidity.encode(message.traffic_rule_validity, writer.uint32(18).fork())
        .join();
    }
    if (message.speed_limit !== undefined) {
      LogicalLane_TrafficRule_SpeedLimit.encode(message.speed_limit, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LogicalLane_TrafficRule {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLogicalLane_TrafficRule();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.traffic_rule_type = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.traffic_rule_validity = LogicalLane_TrafficRule_TrafficRuleValidity.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.speed_limit = LogicalLane_TrafficRule_SpeedLimit.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LogicalLane_TrafficRule {
    return {
      traffic_rule_type: isSet(object.traffic_rule_type)
        ? logicalLane_TrafficRule_TrafficRuleTypeFromJSON(object.traffic_rule_type)
        : 0,
      traffic_rule_validity: isSet(object.traffic_rule_validity)
        ? LogicalLane_TrafficRule_TrafficRuleValidity.fromJSON(object.traffic_rule_validity)
        : undefined,
      speed_limit: isSet(object.speed_limit)
        ? LogicalLane_TrafficRule_SpeedLimit.fromJSON(object.speed_limit)
        : undefined,
    };
  },

  toJSON(message: LogicalLane_TrafficRule): unknown {
    const obj: any = {};
    if (message.traffic_rule_type !== undefined) {
      obj.traffic_rule_type = logicalLane_TrafficRule_TrafficRuleTypeToJSON(message.traffic_rule_type);
    }
    if (message.traffic_rule_validity !== undefined) {
      obj.traffic_rule_validity = LogicalLane_TrafficRule_TrafficRuleValidity.toJSON(message.traffic_rule_validity);
    }
    if (message.speed_limit !== undefined) {
      obj.speed_limit = LogicalLane_TrafficRule_SpeedLimit.toJSON(message.speed_limit);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LogicalLane_TrafficRule>, I>>(base?: I): LogicalLane_TrafficRule {
    return LogicalLane_TrafficRule.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LogicalLane_TrafficRule>, I>>(object: I): LogicalLane_TrafficRule {
    const message = createBaseLogicalLane_TrafficRule();
    message.traffic_rule_type = object.traffic_rule_type ?? 0;
    message.traffic_rule_validity =
      (object.traffic_rule_validity !== undefined && object.traffic_rule_validity !== null)
        ? LogicalLane_TrafficRule_TrafficRuleValidity.fromPartial(object.traffic_rule_validity)
        : undefined;
    message.speed_limit = (object.speed_limit !== undefined && object.speed_limit !== null)
      ? LogicalLane_TrafficRule_SpeedLimit.fromPartial(object.speed_limit)
      : undefined;
    return message;
  },
};

function createBaseLogicalLane_TrafficRule_TrafficRuleValidity(): LogicalLane_TrafficRule_TrafficRuleValidity {
  return { start_s: 0, end_s: 0, valid_for_type: [] };
}

export const LogicalLane_TrafficRule_TrafficRuleValidity: MessageFns<LogicalLane_TrafficRule_TrafficRuleValidity> = {
  encode(
    message: LogicalLane_TrafficRule_TrafficRuleValidity,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.start_s !== undefined && message.start_s !== 0) {
      writer.uint32(9).double(message.start_s);
    }
    if (message.end_s !== undefined && message.end_s !== 0) {
      writer.uint32(17).double(message.end_s);
    }
    for (const v of message.valid_for_type) {
      LogicalLane_TrafficRule_TrafficRuleValidity_TypeValidity.encode(v!, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LogicalLane_TrafficRule_TrafficRuleValidity {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLogicalLane_TrafficRule_TrafficRuleValidity();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 9) {
            break;
          }

          message.start_s = reader.double();
          continue;
        }
        case 2: {
          if (tag !== 17) {
            break;
          }

          message.end_s = reader.double();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.valid_for_type.push(
            LogicalLane_TrafficRule_TrafficRuleValidity_TypeValidity.decode(reader, reader.uint32()),
          );
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LogicalLane_TrafficRule_TrafficRuleValidity {
    return {
      start_s: isSet(object.start_s) ? globalThis.Number(object.start_s) : 0,
      end_s: isSet(object.end_s) ? globalThis.Number(object.end_s) : 0,
      valid_for_type: globalThis.Array.isArray(object?.valid_for_type)
        ? object.valid_for_type.map((e: any) => LogicalLane_TrafficRule_TrafficRuleValidity_TypeValidity.fromJSON(e))
        : [],
    };
  },

  toJSON(message: LogicalLane_TrafficRule_TrafficRuleValidity): unknown {
    const obj: any = {};
    if (message.start_s !== undefined) {
      obj.start_s = message.start_s;
    }
    if (message.end_s !== undefined) {
      obj.end_s = message.end_s;
    }
    if (message.valid_for_type?.length) {
      obj.valid_for_type = message.valid_for_type.map((e) =>
        LogicalLane_TrafficRule_TrafficRuleValidity_TypeValidity.toJSON(e)
      );
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LogicalLane_TrafficRule_TrafficRuleValidity>, I>>(
    base?: I,
  ): LogicalLane_TrafficRule_TrafficRuleValidity {
    return LogicalLane_TrafficRule_TrafficRuleValidity.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LogicalLane_TrafficRule_TrafficRuleValidity>, I>>(
    object: I,
  ): LogicalLane_TrafficRule_TrafficRuleValidity {
    const message = createBaseLogicalLane_TrafficRule_TrafficRuleValidity();
    message.start_s = object.start_s ?? 0;
    message.end_s = object.end_s ?? 0;
    message.valid_for_type =
      object.valid_for_type?.map((e) => LogicalLane_TrafficRule_TrafficRuleValidity_TypeValidity.fromPartial(e)) || [];
    return message;
  },
};

function createBaseLogicalLane_TrafficRule_TrafficRuleValidity_TypeValidity(): LogicalLane_TrafficRule_TrafficRuleValidity_TypeValidity {
  return { type: 0, vehicle_type: 0, vehicle_role: 0 };
}

export const LogicalLane_TrafficRule_TrafficRuleValidity_TypeValidity: MessageFns<
  LogicalLane_TrafficRule_TrafficRuleValidity_TypeValidity
> = {
  encode(
    message: LogicalLane_TrafficRule_TrafficRuleValidity_TypeValidity,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.type !== undefined && message.type !== 0) {
      writer.uint32(8).int32(message.type);
    }
    if (message.vehicle_type !== undefined && message.vehicle_type !== 0) {
      writer.uint32(16).int32(message.vehicle_type);
    }
    if (message.vehicle_role !== undefined && message.vehicle_role !== 0) {
      writer.uint32(24).int32(message.vehicle_role);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LogicalLane_TrafficRule_TrafficRuleValidity_TypeValidity {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLogicalLane_TrafficRule_TrafficRuleValidity_TypeValidity();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.type = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.vehicle_type = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.vehicle_role = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LogicalLane_TrafficRule_TrafficRuleValidity_TypeValidity {
    return {
      type: isSet(object.type) ? movingObject_TypeFromJSON(object.type) : 0,
      vehicle_type: isSet(object.vehicle_type)
        ? movingObject_VehicleClassification_TypeFromJSON(object.vehicle_type)
        : 0,
      vehicle_role: isSet(object.vehicle_role)
        ? movingObject_VehicleClassification_RoleFromJSON(object.vehicle_role)
        : 0,
    };
  },

  toJSON(message: LogicalLane_TrafficRule_TrafficRuleValidity_TypeValidity): unknown {
    const obj: any = {};
    if (message.type !== undefined) {
      obj.type = movingObject_TypeToJSON(message.type);
    }
    if (message.vehicle_type !== undefined) {
      obj.vehicle_type = movingObject_VehicleClassification_TypeToJSON(message.vehicle_type);
    }
    if (message.vehicle_role !== undefined) {
      obj.vehicle_role = movingObject_VehicleClassification_RoleToJSON(message.vehicle_role);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LogicalLane_TrafficRule_TrafficRuleValidity_TypeValidity>, I>>(
    base?: I,
  ): LogicalLane_TrafficRule_TrafficRuleValidity_TypeValidity {
    return LogicalLane_TrafficRule_TrafficRuleValidity_TypeValidity.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LogicalLane_TrafficRule_TrafficRuleValidity_TypeValidity>, I>>(
    object: I,
  ): LogicalLane_TrafficRule_TrafficRuleValidity_TypeValidity {
    const message = createBaseLogicalLane_TrafficRule_TrafficRuleValidity_TypeValidity();
    message.type = object.type ?? 0;
    message.vehicle_type = object.vehicle_type ?? 0;
    message.vehicle_role = object.vehicle_role ?? 0;
    return message;
  },
};

function createBaseLogicalLane_TrafficRule_SpeedLimit(): LogicalLane_TrafficRule_SpeedLimit {
  return { speed_limit_value: undefined };
}

export const LogicalLane_TrafficRule_SpeedLimit: MessageFns<LogicalLane_TrafficRule_SpeedLimit> = {
  encode(message: LogicalLane_TrafficRule_SpeedLimit, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.speed_limit_value !== undefined) {
      TrafficSignValue.encode(message.speed_limit_value, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LogicalLane_TrafficRule_SpeedLimit {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLogicalLane_TrafficRule_SpeedLimit();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.speed_limit_value = TrafficSignValue.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LogicalLane_TrafficRule_SpeedLimit {
    return {
      speed_limit_value: isSet(object.speed_limit_value)
        ? TrafficSignValue.fromJSON(object.speed_limit_value)
        : undefined,
    };
  },

  toJSON(message: LogicalLane_TrafficRule_SpeedLimit): unknown {
    const obj: any = {};
    if (message.speed_limit_value !== undefined) {
      obj.speed_limit_value = TrafficSignValue.toJSON(message.speed_limit_value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LogicalLane_TrafficRule_SpeedLimit>, I>>(
    base?: I,
  ): LogicalLane_TrafficRule_SpeedLimit {
    return LogicalLane_TrafficRule_SpeedLimit.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LogicalLane_TrafficRule_SpeedLimit>, I>>(
    object: I,
  ): LogicalLane_TrafficRule_SpeedLimit {
    const message = createBaseLogicalLane_TrafficRule_SpeedLimit();
    message.speed_limit_value = (object.speed_limit_value !== undefined && object.speed_limit_value !== null)
      ? TrafficSignValue.fromPartial(object.speed_limit_value)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
