// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: osi_hostvehicledata.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  BaseMoving,
  GeodeticPosition,
  Identifier,
  KeyValuePair,
  Orientation3d,
  Timestamp,
  Vector3d,
  VehicleSteeringWheel,
} from "./osi_common";
import { Route } from "./osi_route";
import { InterfaceVersion } from "./osi_version";

/**
 * \brief Host vehicle data is about the perception of the vehicle about its own internal states.
 * It captures the knowledge the vehicle has internally, which can differ from the actual or global truth for various reasons.
 * This message can also be understood as an interface container for the signals of a rest bus simulation.
 *
 * It consists of different messages categorizing the vehicle in:
 * Basics, powertrain, brake system, steering, wheels and localization.
 *
 * \image html OSI_HostVehicle.svg
 */
export interface HostVehicleData {
  /** The interface version used by the sender. */
  version?:
    | InterfaceVersion
    | undefined;
  /**
   * The timestamp of the host vehicle data. Zero time is arbitrary but must be
   * identical for all messages. Zero time does not need to coincide with
   * the unix epoch. Recommended is the starting time point of the
   * simulation or measurement.
   *
   * \note This is the point in time that the host vehicle data message becomes
   * available as snapshot from the board net information.
   */
  timestamp?:
    | Timestamp
    | undefined;
  /** The ID of the host vehicle in any associated GroundTruth data. */
  host_vehicle_id?:
    | Identifier
    | undefined;
  /**
   * Deprecated: Will be removed in next major release. Moved to vehicle_localization.
   * Current estimated location based on GPS- and related navigation sensors.
   *
   * \note Note that dimension and base_polygon need not be set.
   */
  location?:
    | BaseMoving
    | undefined;
  /**
   * Deprecated: Will be removed in next major release. Moved to vehicle_localization.
   * Current estimated location error based on GPS and related navigation
   * sensors.
   *
   * \note Note that dimension and base_polygon need not be set.
   */
  location_rmse?:
    | BaseMoving
    | undefined;
  /** The basic parameters and overall states of the vehicle. */
  vehicle_basics?:
    | HostVehicleData_VehicleBasics
    | undefined;
  /** Interface regarding the powertrain. */
  vehicle_powertrain?:
    | HostVehicleData_VehiclePowertrain
    | undefined;
  /** Interface regarding the brake system. */
  vehicle_brake_system?:
    | HostVehicleData_VehicleBrakeSystem
    | undefined;
  /** Interface regarding the steering. */
  vehicle_steering?:
    | HostVehicleData_VehicleSteering
    | undefined;
  /** Interface regarding the internal wheel states. */
  vehicle_wheels?:
    | HostVehicleData_VehicleWheels
    | undefined;
  /** Interface regarding the localization. */
  vehicle_localization?:
    | HostVehicleData_VehicleLocalization
    | undefined;
  /**
   * State of any automated driving functions.
   *
   * This can include:
   *  - information presented to the driver, for example, parking sensors
   *  - warnings raised by the vehicle, for example, forward collision warning
   *  - corrective action taken by the vehicle, for example, auto emergency braking
   *  - full level 4 self driving systems
   *
   * \note OSI uses singular instead of plural for repeated field names.
   */
  vehicle_automated_driving_function: HostVehicleData_VehicleAutomatedDrivingFunction[];
  /** Interface regarding the vehicle motion. */
  vehicle_motion?:
    | HostVehicleData_VehicleMotion
    | undefined;
  /** Currently planned route of the vehicle */
  route?: Route | undefined;
}

/** \brief Base parameters and overall states of the vehicle. */
export interface HostVehicleData_VehicleBasics {
  /**
   * The total mass of the vehicle (curb weight).
   *
   * Unit: kg
   *
   * \par Reference:
   * Paragraph 42 of the German Road Traffic Admission Regulations (StVZO).
   */
  curb_weight?:
    | number
    | undefined;
  /** The operating state of the vehicle. */
  operating_state?: HostVehicleData_VehicleBasics_OperatingState | undefined;
}

/**
 * Possible operating states of the vehicle.
 * It is user specific which states are used and how their transitions work.
 */
export enum HostVehicleData_VehicleBasics_OperatingState {
  /** OPERATING_STATE_UNKNOWN - The operating state is unknown. */
  OPERATING_STATE_UNKNOWN = 0,
  /** OPERATING_STATE_OTHER - The operating state is another one. */
  OPERATING_STATE_OTHER = 1,
  /**
   * OPERATING_STATE_SLEEP - The minimum electrical state of the vehicle (and its ECUs).
   * Usually the driver has left the vehicle a while ago.
   */
  OPERATING_STATE_SLEEP = 2,
  /**
   * OPERATING_STATE_STANDBY - Cabin lights and entertainment are off. The vehicle can not be driven.
   * Some ECUs are still operating and not in their minimum electrical sate.
   * Usually the driver has left (and closed) the vehicle recently.
   */
  OPERATING_STATE_STANDBY = 3,
  /**
   * OPERATING_STATE_BOARDING - Some features of the vehicle are available e.g. cabin lights.
   * Entertainment is off and the vehicle can not be driven.
   * Usually the driver wants to enter or leave the vehicle.
   */
  OPERATING_STATE_BOARDING = 4,
  /**
   * OPERATING_STATE_ENTERTAINMENT - Entertainment, navigation or similar systems can be used by the driver.
   * The vehicle can not be driven.
   * Usually the driver sits in the vehicle before or after a drive.
   */
  OPERATING_STATE_ENTERTAINMENT = 5,
  /** OPERATING_STATE_DRIVING - The electrical state that is necessary to drive the vehicle. */
  OPERATING_STATE_DRIVING = 6,
  /** OPERATING_STATE_DIAGNOSTIC - The electrical state that is necessary for analysis and diagnostics. */
  OPERATING_STATE_DIAGNOSTIC = 7,
}

export function hostVehicleData_VehicleBasics_OperatingStateFromJSON(
  object: any,
): HostVehicleData_VehicleBasics_OperatingState {
  switch (object) {
    case 0:
    case "OPERATING_STATE_UNKNOWN":
      return HostVehicleData_VehicleBasics_OperatingState.OPERATING_STATE_UNKNOWN;
    case 1:
    case "OPERATING_STATE_OTHER":
      return HostVehicleData_VehicleBasics_OperatingState.OPERATING_STATE_OTHER;
    case 2:
    case "OPERATING_STATE_SLEEP":
      return HostVehicleData_VehicleBasics_OperatingState.OPERATING_STATE_SLEEP;
    case 3:
    case "OPERATING_STATE_STANDBY":
      return HostVehicleData_VehicleBasics_OperatingState.OPERATING_STATE_STANDBY;
    case 4:
    case "OPERATING_STATE_BOARDING":
      return HostVehicleData_VehicleBasics_OperatingState.OPERATING_STATE_BOARDING;
    case 5:
    case "OPERATING_STATE_ENTERTAINMENT":
      return HostVehicleData_VehicleBasics_OperatingState.OPERATING_STATE_ENTERTAINMENT;
    case 6:
    case "OPERATING_STATE_DRIVING":
      return HostVehicleData_VehicleBasics_OperatingState.OPERATING_STATE_DRIVING;
    case 7:
    case "OPERATING_STATE_DIAGNOSTIC":
      return HostVehicleData_VehicleBasics_OperatingState.OPERATING_STATE_DIAGNOSTIC;
    default:
      throw new globalThis.Error(
        "Unrecognized enum value " + object + " for enum HostVehicleData_VehicleBasics_OperatingState",
      );
  }
}

export function hostVehicleData_VehicleBasics_OperatingStateToJSON(
  object: HostVehicleData_VehicleBasics_OperatingState,
): string {
  switch (object) {
    case HostVehicleData_VehicleBasics_OperatingState.OPERATING_STATE_UNKNOWN:
      return "OPERATING_STATE_UNKNOWN";
    case HostVehicleData_VehicleBasics_OperatingState.OPERATING_STATE_OTHER:
      return "OPERATING_STATE_OTHER";
    case HostVehicleData_VehicleBasics_OperatingState.OPERATING_STATE_SLEEP:
      return "OPERATING_STATE_SLEEP";
    case HostVehicleData_VehicleBasics_OperatingState.OPERATING_STATE_STANDBY:
      return "OPERATING_STATE_STANDBY";
    case HostVehicleData_VehicleBasics_OperatingState.OPERATING_STATE_BOARDING:
      return "OPERATING_STATE_BOARDING";
    case HostVehicleData_VehicleBasics_OperatingState.OPERATING_STATE_ENTERTAINMENT:
      return "OPERATING_STATE_ENTERTAINMENT";
    case HostVehicleData_VehicleBasics_OperatingState.OPERATING_STATE_DRIVING:
      return "OPERATING_STATE_DRIVING";
    case HostVehicleData_VehicleBasics_OperatingState.OPERATING_STATE_DIAGNOSTIC:
      return "OPERATING_STATE_DIAGNOSTIC";
    default:
      throw new globalThis.Error(
        "Unrecognized enum value " + object + " for enum HostVehicleData_VehicleBasics_OperatingState",
      );
  }
}

/** \brief State description of the powertrain. */
export interface HostVehicleData_VehiclePowertrain {
  /**
   * Position of the acceleration pedal.
   * Range: 0-1 (Unpressed - fully pressed)
   */
  pedal_position_acceleration?:
    | number
    | undefined;
  /**
   * Position of the clutch pedal.
   * Range: 0-1 (Unpressed - fully pressed)
   */
  pedal_position_clutch?:
    | number
    | undefined;
  /**
   * The actual gear of the transmission.
   * For example, a gear lever can be on "D" and the transmission on "4", but not the
   * other way around.
   *
   * The sign of this field is linked to the gear's mode as following:
   * - zero: neutral position
   * - positive: driving forward mode
   * - negative: reverse mode (generally -1, but few vehicles have more than 1
   *   reverse mode gears)
   */
  gear_transmission?:
    | number
    | undefined;
  /** Information about the motor(s). */
  motor: HostVehicleData_VehiclePowertrain_Motor[];
}

/** \brief A description of the motor states. */
export interface HostVehicleData_VehiclePowertrain_Motor {
  /** The type of the motor. */
  type?:
    | HostVehicleData_VehiclePowertrain_Motor_Type
    | undefined;
  /**
   * Revolutions per minute of the motor.
   *
   * Unit: 1/min
   */
  rpm?:
    | number
    | undefined;
  /**
   * Torque of the motor.
   *
   * Unit: N*m
   */
  torque?: number | undefined;
}

/** Definition which type of motor is used. */
export enum HostVehicleData_VehiclePowertrain_Motor_Type {
  /** TYPE_UNKNOWN - The motor type is unknown. */
  TYPE_UNKNOWN = 0,
  /** TYPE_OTHER - It is another motor type. */
  TYPE_OTHER = 1,
  /** TYPE_OTTO - A motor working after the principle of Nicolaus Otto. */
  TYPE_OTTO = 2,
  /** TYPE_DIESEL - A motor working after the principle of Rudolf Diesel. */
  TYPE_DIESEL = 3,
  /** TYPE_ELECTRIC - A motor working electric. */
  TYPE_ELECTRIC = 4,
}

export function hostVehicleData_VehiclePowertrain_Motor_TypeFromJSON(
  object: any,
): HostVehicleData_VehiclePowertrain_Motor_Type {
  switch (object) {
    case 0:
    case "TYPE_UNKNOWN":
      return HostVehicleData_VehiclePowertrain_Motor_Type.TYPE_UNKNOWN;
    case 1:
    case "TYPE_OTHER":
      return HostVehicleData_VehiclePowertrain_Motor_Type.TYPE_OTHER;
    case 2:
    case "TYPE_OTTO":
      return HostVehicleData_VehiclePowertrain_Motor_Type.TYPE_OTTO;
    case 3:
    case "TYPE_DIESEL":
      return HostVehicleData_VehiclePowertrain_Motor_Type.TYPE_DIESEL;
    case 4:
    case "TYPE_ELECTRIC":
      return HostVehicleData_VehiclePowertrain_Motor_Type.TYPE_ELECTRIC;
    default:
      throw new globalThis.Error(
        "Unrecognized enum value " + object + " for enum HostVehicleData_VehiclePowertrain_Motor_Type",
      );
  }
}

export function hostVehicleData_VehiclePowertrain_Motor_TypeToJSON(
  object: HostVehicleData_VehiclePowertrain_Motor_Type,
): string {
  switch (object) {
    case HostVehicleData_VehiclePowertrain_Motor_Type.TYPE_UNKNOWN:
      return "TYPE_UNKNOWN";
    case HostVehicleData_VehiclePowertrain_Motor_Type.TYPE_OTHER:
      return "TYPE_OTHER";
    case HostVehicleData_VehiclePowertrain_Motor_Type.TYPE_OTTO:
      return "TYPE_OTTO";
    case HostVehicleData_VehiclePowertrain_Motor_Type.TYPE_DIESEL:
      return "TYPE_DIESEL";
    case HostVehicleData_VehiclePowertrain_Motor_Type.TYPE_ELECTRIC:
      return "TYPE_ELECTRIC";
    default:
      throw new globalThis.Error(
        "Unrecognized enum value " + object + " for enum HostVehicleData_VehiclePowertrain_Motor_Type",
      );
  }
}

/** \brief The focus here is on the description of the brake system. */
export interface HostVehicleData_VehicleBrakeSystem {
  /**
   * Position of the brake pedal.
   * Range: 0-1 (Unpressed - fully pressed)
   */
  pedal_position_brake?: number | undefined;
}

/** \brief The focus here is on the description of the steering train. */
export interface HostVehicleData_VehicleSteering {
  /** Description of the steering wheel. */
  vehicle_steering_wheel?: VehicleSteeringWheel | undefined;
}

/** \brief The focus here is on the description of internal wheel states. */
export interface HostVehicleData_VehicleWheels {
  /**
   * Description of each wheel.
   *
   * \note OSI uses singular instead of plural for repeated field names.
   */
  wheel_data: HostVehicleData_VehicleWheels_WheelData[];
}

/** \brief The focus here is on the description of internal wheel states. */
export interface HostVehicleData_VehicleWheels_WheelData {
  /**
   * The axle which contains this wheel. A value of 0 represents the
   * foremost axle of the vehicle, with higher numbers ascending
   * towards the rearmost axle.
   */
  axle?:
    | number
    | undefined;
  /**
   * The index of the wheel on the axle, counted in positive y- direction,
   * that is, right-to-left.
   *
   * For example, on a standard 2-axle, 4-wheel car, the rear-right
   * wheel would be (axle=1, index=0).
   * This concept also works for twin tires.
   */
  index?:
    | number
    | undefined;
  /**
   * Rotation rate of the wheel based on the processed output of the hall sensor measurements at the wheel.
   * The rotation rate around the y-axis with respect to the wheel's coordinate system.
   *
   * Unit: rad/s.
   *
   * The sign convention is defined using the right-hand rule.
   * It is applied on the y-axis of the vehicle's reference system, that is, the center of bounding box.
   * Counterclockwise is positive and clockwise is negative.
   *
   * \image html OSI_RotationRate.svg
   * \note The vehicle's reference coordinate system is only used to determine the sign convention of the rotation rate.
   */
  rotation_rate?:
    | number
    | undefined;
  /**
   * Contains the longitudinal, measured slip of the tire.
   * \par References:
   * [1] kfz-tech.de, Schlupf, Retrieved June 30, 2021, from https://www.kfz-tech.de/Biblio/Formelsammlung/Schlupf.htm
   *
   * Unit: %
   *
   * The sign convention is defined using the right-hand rule.
   * It is applied on the y-axis of the vehicle's reference system, that is, the center of bounding box.
   * Counterclockwise is positive and clockwise is negative.
   */
  slip?: number | undefined;
}

/**
 * \brief Current calculated and estimated location that can be based on GNSS and related navigation sensors.
 * This message does not contain the individual sensor values of the sensor technology.
 *
 * This message contains the most accurate information the vehicle knows about its position
 * available in the on-board network.
 * Because of this the values can differ from the "true" values calculated out of
 * GroundTruth::proj_string, GroundTruth::MovingObject::BaseMoving::position, GroundTruth::host_vehicle_id.
 *
 * This data uses the reference point coincident with the center (x,y,z) of the bounding box.
 */
export interface HostVehicleData_VehicleLocalization {
  /**
   * Most accurate position information of the vehicle available in the on-board network
   * measured in context to the global coordinate system.
   */
  position?:
    | Vector3d
    | undefined;
  /**
   * Most accurate orientation information of the vehicle available in the on-board network
   * measured in context to the global coordinate system.
   */
  orientation?:
    | Orientation3d
    | undefined;
  /** Most accurate geodetic information of the vehicle available in the on-board network. */
  geodetic_position?: GeodeticPosition | undefined;
}

/**
 * \brief Current calculated and estimated motion related information.
 *
 * This message contains the most accurate information the vehicle knows about its motion
 * including vehicle dynamics and control related information available in the on-board network,
 * which can differ from the "true" values calculated out of the ground truth.
 *
 * This data uses the reference point coincident with the middle (in x, y and z) of rear axle
 * under neutral load conditions as defined in \c MovingObject::VehicleAttributes::bbcenter_to_rear.
 */
export interface HostVehicleData_VehicleMotion {
  /**
   * Most accurate position of the vehicle available in the on-board network
   * measured in the cartesian global coordinate system.
   */
  position?:
    | Vector3d
    | undefined;
  /**
   * Most accurate orientation information of the vehicle available in the on-board network
   * measured on the vehicle coordinate system in context of the global inertial system.
   */
  orientation?:
    | Orientation3d
    | undefined;
  /**
   * Most accurate velocity information of the vehicle, available in the on-board network
   * measured on the vehicle coordinate system in context of the global inertial system.
   */
  velocity?:
    | Vector3d
    | undefined;
  /**
   * Most accurate orientation rate of the vehicle, available in the on-board network
   * measured on the vehicle coordinate system in context of the global inertial system.
   */
  orientation_rate?:
    | Orientation3d
    | undefined;
  /**
   * Most accurate acceleration information of the vehicle, available in the on-board network
   * measured on the vehicle coordinate system in context of the global inertial system.
   */
  acceleration?:
    | Vector3d
    | undefined;
  /**
   * Most accurate curvature currently followed by vehicle and available in the on-board network
   *
   * Unit: m^-1
   */
  current_curvature?: number | undefined;
}

/** \brief State of one automated driving function on the host vehicle. */
export interface HostVehicleData_VehicleAutomatedDrivingFunction {
  /** The particular driving function being reported about. */
  name?:
    | HostVehicleData_VehicleAutomatedDrivingFunction_Name
    | undefined;
  /**
   * Custom driving function name.
   *
   * Only used if name is set to NAME_OTHER.
   */
  custom_name?:
    | string
    | undefined;
  /**
   * The state of the function.
   *
   * This is whether the function has actually been triggered, for
   * example, a warning has been raised, or additional braking is
   * in effect.
   */
  state?:
    | HostVehicleData_VehicleAutomatedDrivingFunction_State
    | undefined;
  /**
   * Custom state.
   *
   * Only used if the state is set to STATE_OTHER.
   */
  custom_state?:
    | string
    | undefined;
  /** Whether, and how, the driver has overridden this function. */
  driver_override?:
    | HostVehicleData_VehicleAutomatedDrivingFunction_DriverOverride
    | undefined;
  /**
   * Custom detail.
   *
   * An opaque set of key-value pairs which capture any user specific
   * details that may be relevant.  This could include details about
   * how a warning was raised (dashboard, audible, etc.) or it could
   * be about settings which would influence evaluation, such as
   * sensitivity settings.
   */
  custom_detail: KeyValuePair[];
}

/**
 * A list of possible automated driving features.
 *
 * \note This can span (in theory) from Level 0 all the way to Level 5.
 *
 * \par References:
 * [1] CLEARING THE CONFUSION: Recommended Common Naming for Advanced Driver Assistance Technologies, SAE International, Retrieved October 22, 2021, from https://www.sae.org/binaries/content/assets/cm/content/miscellaneous/adas-nomenclature.pdf
 * [2] Automated Driving, German Association of the Automotive Industry (VDA), Retrieved October 22, 2021, from https://www.vda.de/en/topics/innovation-and-technology/automated-driving/automated-driving
 */
export enum HostVehicleData_VehicleAutomatedDrivingFunction_Name {
  /** NAME_UNKNOWN - Unknown feature, should not be used. */
  NAME_UNKNOWN = 0,
  /** NAME_OTHER - Custom feature, see custom_name. */
  NAME_OTHER = 1,
  /** NAME_BLIND_SPOT_WARNING - Blind spot warning. */
  NAME_BLIND_SPOT_WARNING = 2,
  /** NAME_FORWARD_COLLISION_WARNING - Forward collision warning. */
  NAME_FORWARD_COLLISION_WARNING = 3,
  /** NAME_LANE_DEPARTURE_WARNING - Lane departure warning. */
  NAME_LANE_DEPARTURE_WARNING = 4,
  /** NAME_PARKING_COLLISION_WARNING - Parking collision warning. */
  NAME_PARKING_COLLISION_WARNING = 5,
  /** NAME_REAR_CROSS_TRAFFIC_WARNING - Rear cross-traffic warning */
  NAME_REAR_CROSS_TRAFFIC_WARNING = 6,
  /** NAME_AUTOMATIC_EMERGENCY_BRAKING - Automatic emergency braking */
  NAME_AUTOMATIC_EMERGENCY_BRAKING = 7,
  /** NAME_AUTOMATIC_EMERGENCY_STEERING - Emergency steering */
  NAME_AUTOMATIC_EMERGENCY_STEERING = 8,
  /** NAME_REVERSE_AUTOMATIC_EMERGENCY_BRAKING - Reverse automatic emergency braking */
  NAME_REVERSE_AUTOMATIC_EMERGENCY_BRAKING = 9,
  /** NAME_ADAPTIVE_CRUISE_CONTROL - Adaptive cruise control */
  NAME_ADAPTIVE_CRUISE_CONTROL = 10,
  /** NAME_LANE_KEEPING_ASSIST - Lane keeping assist */
  NAME_LANE_KEEPING_ASSIST = 11,
  /** NAME_ACTIVE_DRIVING_ASSISTANCE - Active driving assistance */
  NAME_ACTIVE_DRIVING_ASSISTANCE = 12,
  /** NAME_BACKUP_CAMERA - Backup camera */
  NAME_BACKUP_CAMERA = 13,
  /** NAME_SURROUND_VIEW_CAMERA - Surround view camera */
  NAME_SURROUND_VIEW_CAMERA = 14,
  /** NAME_ACTIVE_PARKING_ASSISTANCE - Active parking assistance */
  NAME_ACTIVE_PARKING_ASSISTANCE = 15,
  /** NAME_REMOTE_PARKING_ASSISTANCE - Remote parking assistance */
  NAME_REMOTE_PARKING_ASSISTANCE = 16,
  /** NAME_TRAILER_ASSISTANCE - Trailer assistance */
  NAME_TRAILER_ASSISTANCE = 17,
  /** NAME_AUTOMATIC_HIGH_BEAMS - Automatic high beams */
  NAME_AUTOMATIC_HIGH_BEAMS = 18,
  /** NAME_DRIVER_MONITORING - Driver monitoring */
  NAME_DRIVER_MONITORING = 19,
  /** NAME_HEAD_UP_DISPLAY - Head up display */
  NAME_HEAD_UP_DISPLAY = 20,
  /** NAME_NIGHT_VISION - Night vision */
  NAME_NIGHT_VISION = 21,
  /** NAME_URBAN_DRIVING - Urban driving */
  NAME_URBAN_DRIVING = 22,
  /** NAME_HIGHWAY_AUTOPILOT - Highway autopilot. */
  NAME_HIGHWAY_AUTOPILOT = 23,
  /** NAME_CRUISE_CONTROL - Cruise control. */
  NAME_CRUISE_CONTROL = 24,
  /** NAME_SPEED_LIMIT_CONTROL - Speed limit control */
  NAME_SPEED_LIMIT_CONTROL = 25,
}

export function hostVehicleData_VehicleAutomatedDrivingFunction_NameFromJSON(
  object: any,
): HostVehicleData_VehicleAutomatedDrivingFunction_Name {
  switch (object) {
    case 0:
    case "NAME_UNKNOWN":
      return HostVehicleData_VehicleAutomatedDrivingFunction_Name.NAME_UNKNOWN;
    case 1:
    case "NAME_OTHER":
      return HostVehicleData_VehicleAutomatedDrivingFunction_Name.NAME_OTHER;
    case 2:
    case "NAME_BLIND_SPOT_WARNING":
      return HostVehicleData_VehicleAutomatedDrivingFunction_Name.NAME_BLIND_SPOT_WARNING;
    case 3:
    case "NAME_FORWARD_COLLISION_WARNING":
      return HostVehicleData_VehicleAutomatedDrivingFunction_Name.NAME_FORWARD_COLLISION_WARNING;
    case 4:
    case "NAME_LANE_DEPARTURE_WARNING":
      return HostVehicleData_VehicleAutomatedDrivingFunction_Name.NAME_LANE_DEPARTURE_WARNING;
    case 5:
    case "NAME_PARKING_COLLISION_WARNING":
      return HostVehicleData_VehicleAutomatedDrivingFunction_Name.NAME_PARKING_COLLISION_WARNING;
    case 6:
    case "NAME_REAR_CROSS_TRAFFIC_WARNING":
      return HostVehicleData_VehicleAutomatedDrivingFunction_Name.NAME_REAR_CROSS_TRAFFIC_WARNING;
    case 7:
    case "NAME_AUTOMATIC_EMERGENCY_BRAKING":
      return HostVehicleData_VehicleAutomatedDrivingFunction_Name.NAME_AUTOMATIC_EMERGENCY_BRAKING;
    case 8:
    case "NAME_AUTOMATIC_EMERGENCY_STEERING":
      return HostVehicleData_VehicleAutomatedDrivingFunction_Name.NAME_AUTOMATIC_EMERGENCY_STEERING;
    case 9:
    case "NAME_REVERSE_AUTOMATIC_EMERGENCY_BRAKING":
      return HostVehicleData_VehicleAutomatedDrivingFunction_Name.NAME_REVERSE_AUTOMATIC_EMERGENCY_BRAKING;
    case 10:
    case "NAME_ADAPTIVE_CRUISE_CONTROL":
      return HostVehicleData_VehicleAutomatedDrivingFunction_Name.NAME_ADAPTIVE_CRUISE_CONTROL;
    case 11:
    case "NAME_LANE_KEEPING_ASSIST":
      return HostVehicleData_VehicleAutomatedDrivingFunction_Name.NAME_LANE_KEEPING_ASSIST;
    case 12:
    case "NAME_ACTIVE_DRIVING_ASSISTANCE":
      return HostVehicleData_VehicleAutomatedDrivingFunction_Name.NAME_ACTIVE_DRIVING_ASSISTANCE;
    case 13:
    case "NAME_BACKUP_CAMERA":
      return HostVehicleData_VehicleAutomatedDrivingFunction_Name.NAME_BACKUP_CAMERA;
    case 14:
    case "NAME_SURROUND_VIEW_CAMERA":
      return HostVehicleData_VehicleAutomatedDrivingFunction_Name.NAME_SURROUND_VIEW_CAMERA;
    case 15:
    case "NAME_ACTIVE_PARKING_ASSISTANCE":
      return HostVehicleData_VehicleAutomatedDrivingFunction_Name.NAME_ACTIVE_PARKING_ASSISTANCE;
    case 16:
    case "NAME_REMOTE_PARKING_ASSISTANCE":
      return HostVehicleData_VehicleAutomatedDrivingFunction_Name.NAME_REMOTE_PARKING_ASSISTANCE;
    case 17:
    case "NAME_TRAILER_ASSISTANCE":
      return HostVehicleData_VehicleAutomatedDrivingFunction_Name.NAME_TRAILER_ASSISTANCE;
    case 18:
    case "NAME_AUTOMATIC_HIGH_BEAMS":
      return HostVehicleData_VehicleAutomatedDrivingFunction_Name.NAME_AUTOMATIC_HIGH_BEAMS;
    case 19:
    case "NAME_DRIVER_MONITORING":
      return HostVehicleData_VehicleAutomatedDrivingFunction_Name.NAME_DRIVER_MONITORING;
    case 20:
    case "NAME_HEAD_UP_DISPLAY":
      return HostVehicleData_VehicleAutomatedDrivingFunction_Name.NAME_HEAD_UP_DISPLAY;
    case 21:
    case "NAME_NIGHT_VISION":
      return HostVehicleData_VehicleAutomatedDrivingFunction_Name.NAME_NIGHT_VISION;
    case 22:
    case "NAME_URBAN_DRIVING":
      return HostVehicleData_VehicleAutomatedDrivingFunction_Name.NAME_URBAN_DRIVING;
    case 23:
    case "NAME_HIGHWAY_AUTOPILOT":
      return HostVehicleData_VehicleAutomatedDrivingFunction_Name.NAME_HIGHWAY_AUTOPILOT;
    case 24:
    case "NAME_CRUISE_CONTROL":
      return HostVehicleData_VehicleAutomatedDrivingFunction_Name.NAME_CRUISE_CONTROL;
    case 25:
    case "NAME_SPEED_LIMIT_CONTROL":
      return HostVehicleData_VehicleAutomatedDrivingFunction_Name.NAME_SPEED_LIMIT_CONTROL;
    default:
      throw new globalThis.Error(
        "Unrecognized enum value " + object + " for enum HostVehicleData_VehicleAutomatedDrivingFunction_Name",
      );
  }
}

export function hostVehicleData_VehicleAutomatedDrivingFunction_NameToJSON(
  object: HostVehicleData_VehicleAutomatedDrivingFunction_Name,
): string {
  switch (object) {
    case HostVehicleData_VehicleAutomatedDrivingFunction_Name.NAME_UNKNOWN:
      return "NAME_UNKNOWN";
    case HostVehicleData_VehicleAutomatedDrivingFunction_Name.NAME_OTHER:
      return "NAME_OTHER";
    case HostVehicleData_VehicleAutomatedDrivingFunction_Name.NAME_BLIND_SPOT_WARNING:
      return "NAME_BLIND_SPOT_WARNING";
    case HostVehicleData_VehicleAutomatedDrivingFunction_Name.NAME_FORWARD_COLLISION_WARNING:
      return "NAME_FORWARD_COLLISION_WARNING";
    case HostVehicleData_VehicleAutomatedDrivingFunction_Name.NAME_LANE_DEPARTURE_WARNING:
      return "NAME_LANE_DEPARTURE_WARNING";
    case HostVehicleData_VehicleAutomatedDrivingFunction_Name.NAME_PARKING_COLLISION_WARNING:
      return "NAME_PARKING_COLLISION_WARNING";
    case HostVehicleData_VehicleAutomatedDrivingFunction_Name.NAME_REAR_CROSS_TRAFFIC_WARNING:
      return "NAME_REAR_CROSS_TRAFFIC_WARNING";
    case HostVehicleData_VehicleAutomatedDrivingFunction_Name.NAME_AUTOMATIC_EMERGENCY_BRAKING:
      return "NAME_AUTOMATIC_EMERGENCY_BRAKING";
    case HostVehicleData_VehicleAutomatedDrivingFunction_Name.NAME_AUTOMATIC_EMERGENCY_STEERING:
      return "NAME_AUTOMATIC_EMERGENCY_STEERING";
    case HostVehicleData_VehicleAutomatedDrivingFunction_Name.NAME_REVERSE_AUTOMATIC_EMERGENCY_BRAKING:
      return "NAME_REVERSE_AUTOMATIC_EMERGENCY_BRAKING";
    case HostVehicleData_VehicleAutomatedDrivingFunction_Name.NAME_ADAPTIVE_CRUISE_CONTROL:
      return "NAME_ADAPTIVE_CRUISE_CONTROL";
    case HostVehicleData_VehicleAutomatedDrivingFunction_Name.NAME_LANE_KEEPING_ASSIST:
      return "NAME_LANE_KEEPING_ASSIST";
    case HostVehicleData_VehicleAutomatedDrivingFunction_Name.NAME_ACTIVE_DRIVING_ASSISTANCE:
      return "NAME_ACTIVE_DRIVING_ASSISTANCE";
    case HostVehicleData_VehicleAutomatedDrivingFunction_Name.NAME_BACKUP_CAMERA:
      return "NAME_BACKUP_CAMERA";
    case HostVehicleData_VehicleAutomatedDrivingFunction_Name.NAME_SURROUND_VIEW_CAMERA:
      return "NAME_SURROUND_VIEW_CAMERA";
    case HostVehicleData_VehicleAutomatedDrivingFunction_Name.NAME_ACTIVE_PARKING_ASSISTANCE:
      return "NAME_ACTIVE_PARKING_ASSISTANCE";
    case HostVehicleData_VehicleAutomatedDrivingFunction_Name.NAME_REMOTE_PARKING_ASSISTANCE:
      return "NAME_REMOTE_PARKING_ASSISTANCE";
    case HostVehicleData_VehicleAutomatedDrivingFunction_Name.NAME_TRAILER_ASSISTANCE:
      return "NAME_TRAILER_ASSISTANCE";
    case HostVehicleData_VehicleAutomatedDrivingFunction_Name.NAME_AUTOMATIC_HIGH_BEAMS:
      return "NAME_AUTOMATIC_HIGH_BEAMS";
    case HostVehicleData_VehicleAutomatedDrivingFunction_Name.NAME_DRIVER_MONITORING:
      return "NAME_DRIVER_MONITORING";
    case HostVehicleData_VehicleAutomatedDrivingFunction_Name.NAME_HEAD_UP_DISPLAY:
      return "NAME_HEAD_UP_DISPLAY";
    case HostVehicleData_VehicleAutomatedDrivingFunction_Name.NAME_NIGHT_VISION:
      return "NAME_NIGHT_VISION";
    case HostVehicleData_VehicleAutomatedDrivingFunction_Name.NAME_URBAN_DRIVING:
      return "NAME_URBAN_DRIVING";
    case HostVehicleData_VehicleAutomatedDrivingFunction_Name.NAME_HIGHWAY_AUTOPILOT:
      return "NAME_HIGHWAY_AUTOPILOT";
    case HostVehicleData_VehicleAutomatedDrivingFunction_Name.NAME_CRUISE_CONTROL:
      return "NAME_CRUISE_CONTROL";
    case HostVehicleData_VehicleAutomatedDrivingFunction_Name.NAME_SPEED_LIMIT_CONTROL:
      return "NAME_SPEED_LIMIT_CONTROL";
    default:
      throw new globalThis.Error(
        "Unrecognized enum value " + object + " for enum HostVehicleData_VehicleAutomatedDrivingFunction_Name",
      );
  }
}

/**
 * The state that the feature is in.
 *
 * \note Not all of these will be applicable for all vehicles
 * and features.
 */
export enum HostVehicleData_VehicleAutomatedDrivingFunction_State {
  /** STATE_UNKNOWN - An unknown state, this should not be used. */
  STATE_UNKNOWN = 0,
  /**
   * STATE_OTHER - Used for custom states not covered by the definitions below.
   *
   * A string state can be specified in custom_state.
   */
  STATE_OTHER = 1,
  /** STATE_ERRORED - The function has thrown an error in some way that renders it ineffective. */
  STATE_ERRORED = 2,
  /**
   * STATE_UNAVAILABLE - The function cannot be used due to unfulfilled preconditions,
   * for example it is a highway only feature and the vehicle is in
   * an urban environment.
   */
  STATE_UNAVAILABLE = 3,
  /**
   * STATE_AVAILABLE - The function can be used as all preconditions are satisfied, but
   * it hasn't been enabled.
   */
  STATE_AVAILABLE = 4,
  /**
   * STATE_STANDBY - The function is available but conditions have not caused it to be
   * triggered, for example, no vehicles in front to trigger a forward collision warning.
   */
  STATE_STANDBY = 5,
  /**
   * STATE_ACTIVE - The function is currently active, for example, a warning is being
   * shown to the driver, or emergency braking is being applied/
   */
  STATE_ACTIVE = 6,
}

export function hostVehicleData_VehicleAutomatedDrivingFunction_StateFromJSON(
  object: any,
): HostVehicleData_VehicleAutomatedDrivingFunction_State {
  switch (object) {
    case 0:
    case "STATE_UNKNOWN":
      return HostVehicleData_VehicleAutomatedDrivingFunction_State.STATE_UNKNOWN;
    case 1:
    case "STATE_OTHER":
      return HostVehicleData_VehicleAutomatedDrivingFunction_State.STATE_OTHER;
    case 2:
    case "STATE_ERRORED":
      return HostVehicleData_VehicleAutomatedDrivingFunction_State.STATE_ERRORED;
    case 3:
    case "STATE_UNAVAILABLE":
      return HostVehicleData_VehicleAutomatedDrivingFunction_State.STATE_UNAVAILABLE;
    case 4:
    case "STATE_AVAILABLE":
      return HostVehicleData_VehicleAutomatedDrivingFunction_State.STATE_AVAILABLE;
    case 5:
    case "STATE_STANDBY":
      return HostVehicleData_VehicleAutomatedDrivingFunction_State.STATE_STANDBY;
    case 6:
    case "STATE_ACTIVE":
      return HostVehicleData_VehicleAutomatedDrivingFunction_State.STATE_ACTIVE;
    default:
      throw new globalThis.Error(
        "Unrecognized enum value " + object + " for enum HostVehicleData_VehicleAutomatedDrivingFunction_State",
      );
  }
}

export function hostVehicleData_VehicleAutomatedDrivingFunction_StateToJSON(
  object: HostVehicleData_VehicleAutomatedDrivingFunction_State,
): string {
  switch (object) {
    case HostVehicleData_VehicleAutomatedDrivingFunction_State.STATE_UNKNOWN:
      return "STATE_UNKNOWN";
    case HostVehicleData_VehicleAutomatedDrivingFunction_State.STATE_OTHER:
      return "STATE_OTHER";
    case HostVehicleData_VehicleAutomatedDrivingFunction_State.STATE_ERRORED:
      return "STATE_ERRORED";
    case HostVehicleData_VehicleAutomatedDrivingFunction_State.STATE_UNAVAILABLE:
      return "STATE_UNAVAILABLE";
    case HostVehicleData_VehicleAutomatedDrivingFunction_State.STATE_AVAILABLE:
      return "STATE_AVAILABLE";
    case HostVehicleData_VehicleAutomatedDrivingFunction_State.STATE_STANDBY:
      return "STATE_STANDBY";
    case HostVehicleData_VehicleAutomatedDrivingFunction_State.STATE_ACTIVE:
      return "STATE_ACTIVE";
    default:
      throw new globalThis.Error(
        "Unrecognized enum value " + object + " for enum HostVehicleData_VehicleAutomatedDrivingFunction_State",
      );
  }
}

/**
 * \brief Driver override information
 *
 * Information about whether and how and driver may have overridden
 * an automated driving function.
 */
export interface HostVehicleData_VehicleAutomatedDrivingFunction_DriverOverride {
  /**
   * The feature has been overridden by a driver action.
   *
   * \note If false, the rest of this message should be ignored.
   */
  active?:
    | boolean
    | undefined;
  /** What driver inputs have caused the override. */
  override_reason: HostVehicleData_VehicleAutomatedDrivingFunction_DriverOverride_Reason[];
}

/** Ways in which a driver could override a driving function. */
export enum HostVehicleData_VehicleAutomatedDrivingFunction_DriverOverride_Reason {
  /** REASON_BRAKE_PEDAL - The driver has applied sufficient input via the break pedal. */
  REASON_BRAKE_PEDAL = 0,
  /** REASON_STEERING_INPUT - The driver has applied sufficient steering input. */
  REASON_STEERING_INPUT = 1,
}

export function hostVehicleData_VehicleAutomatedDrivingFunction_DriverOverride_ReasonFromJSON(
  object: any,
): HostVehicleData_VehicleAutomatedDrivingFunction_DriverOverride_Reason {
  switch (object) {
    case 0:
    case "REASON_BRAKE_PEDAL":
      return HostVehicleData_VehicleAutomatedDrivingFunction_DriverOverride_Reason.REASON_BRAKE_PEDAL;
    case 1:
    case "REASON_STEERING_INPUT":
      return HostVehicleData_VehicleAutomatedDrivingFunction_DriverOverride_Reason.REASON_STEERING_INPUT;
    default:
      throw new globalThis.Error(
        "Unrecognized enum value " + object +
          " for enum HostVehicleData_VehicleAutomatedDrivingFunction_DriverOverride_Reason",
      );
  }
}

export function hostVehicleData_VehicleAutomatedDrivingFunction_DriverOverride_ReasonToJSON(
  object: HostVehicleData_VehicleAutomatedDrivingFunction_DriverOverride_Reason,
): string {
  switch (object) {
    case HostVehicleData_VehicleAutomatedDrivingFunction_DriverOverride_Reason.REASON_BRAKE_PEDAL:
      return "REASON_BRAKE_PEDAL";
    case HostVehicleData_VehicleAutomatedDrivingFunction_DriverOverride_Reason.REASON_STEERING_INPUT:
      return "REASON_STEERING_INPUT";
    default:
      throw new globalThis.Error(
        "Unrecognized enum value " + object +
          " for enum HostVehicleData_VehicleAutomatedDrivingFunction_DriverOverride_Reason",
      );
  }
}

function createBaseHostVehicleData(): HostVehicleData {
  return {
    version: undefined,
    timestamp: undefined,
    host_vehicle_id: undefined,
    location: undefined,
    location_rmse: undefined,
    vehicle_basics: undefined,
    vehicle_powertrain: undefined,
    vehicle_brake_system: undefined,
    vehicle_steering: undefined,
    vehicle_wheels: undefined,
    vehicle_localization: undefined,
    vehicle_automated_driving_function: [],
    vehicle_motion: undefined,
    route: undefined,
  };
}

export const HostVehicleData: MessageFns<HostVehicleData> = {
  encode(message: HostVehicleData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.version !== undefined) {
      InterfaceVersion.encode(message.version, writer.uint32(74).fork()).join();
    }
    if (message.timestamp !== undefined) {
      Timestamp.encode(message.timestamp, writer.uint32(82).fork()).join();
    }
    if (message.host_vehicle_id !== undefined) {
      Identifier.encode(message.host_vehicle_id, writer.uint32(90).fork()).join();
    }
    if (message.location !== undefined) {
      BaseMoving.encode(message.location, writer.uint32(10).fork()).join();
    }
    if (message.location_rmse !== undefined) {
      BaseMoving.encode(message.location_rmse, writer.uint32(18).fork()).join();
    }
    if (message.vehicle_basics !== undefined) {
      HostVehicleData_VehicleBasics.encode(message.vehicle_basics, writer.uint32(26).fork()).join();
    }
    if (message.vehicle_powertrain !== undefined) {
      HostVehicleData_VehiclePowertrain.encode(message.vehicle_powertrain, writer.uint32(34).fork()).join();
    }
    if (message.vehicle_brake_system !== undefined) {
      HostVehicleData_VehicleBrakeSystem.encode(message.vehicle_brake_system, writer.uint32(42).fork()).join();
    }
    if (message.vehicle_steering !== undefined) {
      HostVehicleData_VehicleSteering.encode(message.vehicle_steering, writer.uint32(50).fork()).join();
    }
    if (message.vehicle_wheels !== undefined) {
      HostVehicleData_VehicleWheels.encode(message.vehicle_wheels, writer.uint32(58).fork()).join();
    }
    if (message.vehicle_localization !== undefined) {
      HostVehicleData_VehicleLocalization.encode(message.vehicle_localization, writer.uint32(66).fork()).join();
    }
    for (const v of message.vehicle_automated_driving_function) {
      HostVehicleData_VehicleAutomatedDrivingFunction.encode(v!, writer.uint32(98).fork()).join();
    }
    if (message.vehicle_motion !== undefined) {
      HostVehicleData_VehicleMotion.encode(message.vehicle_motion, writer.uint32(106).fork()).join();
    }
    if (message.route !== undefined) {
      Route.encode(message.route, writer.uint32(114).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HostVehicleData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHostVehicleData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.version = InterfaceVersion.decode(reader, reader.uint32());
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.timestamp = Timestamp.decode(reader, reader.uint32());
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.host_vehicle_id = Identifier.decode(reader, reader.uint32());
          continue;
        }
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.location = BaseMoving.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.location_rmse = BaseMoving.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.vehicle_basics = HostVehicleData_VehicleBasics.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.vehicle_powertrain = HostVehicleData_VehiclePowertrain.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.vehicle_brake_system = HostVehicleData_VehicleBrakeSystem.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.vehicle_steering = HostVehicleData_VehicleSteering.decode(reader, reader.uint32());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.vehicle_wheels = HostVehicleData_VehicleWheels.decode(reader, reader.uint32());
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.vehicle_localization = HostVehicleData_VehicleLocalization.decode(reader, reader.uint32());
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.vehicle_automated_driving_function.push(
            HostVehicleData_VehicleAutomatedDrivingFunction.decode(reader, reader.uint32()),
          );
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.vehicle_motion = HostVehicleData_VehicleMotion.decode(reader, reader.uint32());
          continue;
        }
        case 14: {
          if (tag !== 114) {
            break;
          }

          message.route = Route.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HostVehicleData {
    return {
      version: isSet(object.version) ? InterfaceVersion.fromJSON(object.version) : undefined,
      timestamp: isSet(object.timestamp) ? Timestamp.fromJSON(object.timestamp) : undefined,
      host_vehicle_id: isSet(object.host_vehicle_id) ? Identifier.fromJSON(object.host_vehicle_id) : undefined,
      location: isSet(object.location) ? BaseMoving.fromJSON(object.location) : undefined,
      location_rmse: isSet(object.location_rmse) ? BaseMoving.fromJSON(object.location_rmse) : undefined,
      vehicle_basics: isSet(object.vehicle_basics)
        ? HostVehicleData_VehicleBasics.fromJSON(object.vehicle_basics)
        : undefined,
      vehicle_powertrain: isSet(object.vehicle_powertrain)
        ? HostVehicleData_VehiclePowertrain.fromJSON(object.vehicle_powertrain)
        : undefined,
      vehicle_brake_system: isSet(object.vehicle_brake_system)
        ? HostVehicleData_VehicleBrakeSystem.fromJSON(object.vehicle_brake_system)
        : undefined,
      vehicle_steering: isSet(object.vehicle_steering)
        ? HostVehicleData_VehicleSteering.fromJSON(object.vehicle_steering)
        : undefined,
      vehicle_wheels: isSet(object.vehicle_wheels)
        ? HostVehicleData_VehicleWheels.fromJSON(object.vehicle_wheels)
        : undefined,
      vehicle_localization: isSet(object.vehicle_localization)
        ? HostVehicleData_VehicleLocalization.fromJSON(object.vehicle_localization)
        : undefined,
      vehicle_automated_driving_function: globalThis.Array.isArray(object?.vehicle_automated_driving_function)
        ? object.vehicle_automated_driving_function.map((e: any) =>
          HostVehicleData_VehicleAutomatedDrivingFunction.fromJSON(e)
        )
        : [],
      vehicle_motion: isSet(object.vehicle_motion)
        ? HostVehicleData_VehicleMotion.fromJSON(object.vehicle_motion)
        : undefined,
      route: isSet(object.route) ? Route.fromJSON(object.route) : undefined,
    };
  },

  toJSON(message: HostVehicleData): unknown {
    const obj: any = {};
    if (message.version !== undefined) {
      obj.version = InterfaceVersion.toJSON(message.version);
    }
    if (message.timestamp !== undefined) {
      obj.timestamp = Timestamp.toJSON(message.timestamp);
    }
    if (message.host_vehicle_id !== undefined) {
      obj.host_vehicle_id = Identifier.toJSON(message.host_vehicle_id);
    }
    if (message.location !== undefined) {
      obj.location = BaseMoving.toJSON(message.location);
    }
    if (message.location_rmse !== undefined) {
      obj.location_rmse = BaseMoving.toJSON(message.location_rmse);
    }
    if (message.vehicle_basics !== undefined) {
      obj.vehicle_basics = HostVehicleData_VehicleBasics.toJSON(message.vehicle_basics);
    }
    if (message.vehicle_powertrain !== undefined) {
      obj.vehicle_powertrain = HostVehicleData_VehiclePowertrain.toJSON(message.vehicle_powertrain);
    }
    if (message.vehicle_brake_system !== undefined) {
      obj.vehicle_brake_system = HostVehicleData_VehicleBrakeSystem.toJSON(message.vehicle_brake_system);
    }
    if (message.vehicle_steering !== undefined) {
      obj.vehicle_steering = HostVehicleData_VehicleSteering.toJSON(message.vehicle_steering);
    }
    if (message.vehicle_wheels !== undefined) {
      obj.vehicle_wheels = HostVehicleData_VehicleWheels.toJSON(message.vehicle_wheels);
    }
    if (message.vehicle_localization !== undefined) {
      obj.vehicle_localization = HostVehicleData_VehicleLocalization.toJSON(message.vehicle_localization);
    }
    if (message.vehicle_automated_driving_function?.length) {
      obj.vehicle_automated_driving_function = message.vehicle_automated_driving_function.map((e) =>
        HostVehicleData_VehicleAutomatedDrivingFunction.toJSON(e)
      );
    }
    if (message.vehicle_motion !== undefined) {
      obj.vehicle_motion = HostVehicleData_VehicleMotion.toJSON(message.vehicle_motion);
    }
    if (message.route !== undefined) {
      obj.route = Route.toJSON(message.route);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<HostVehicleData>, I>>(base?: I): HostVehicleData {
    return HostVehicleData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HostVehicleData>, I>>(object: I): HostVehicleData {
    const message = createBaseHostVehicleData();
    message.version = (object.version !== undefined && object.version !== null)
      ? InterfaceVersion.fromPartial(object.version)
      : undefined;
    message.timestamp = (object.timestamp !== undefined && object.timestamp !== null)
      ? Timestamp.fromPartial(object.timestamp)
      : undefined;
    message.host_vehicle_id = (object.host_vehicle_id !== undefined && object.host_vehicle_id !== null)
      ? Identifier.fromPartial(object.host_vehicle_id)
      : undefined;
    message.location = (object.location !== undefined && object.location !== null)
      ? BaseMoving.fromPartial(object.location)
      : undefined;
    message.location_rmse = (object.location_rmse !== undefined && object.location_rmse !== null)
      ? BaseMoving.fromPartial(object.location_rmse)
      : undefined;
    message.vehicle_basics = (object.vehicle_basics !== undefined && object.vehicle_basics !== null)
      ? HostVehicleData_VehicleBasics.fromPartial(object.vehicle_basics)
      : undefined;
    message.vehicle_powertrain = (object.vehicle_powertrain !== undefined && object.vehicle_powertrain !== null)
      ? HostVehicleData_VehiclePowertrain.fromPartial(object.vehicle_powertrain)
      : undefined;
    message.vehicle_brake_system = (object.vehicle_brake_system !== undefined && object.vehicle_brake_system !== null)
      ? HostVehicleData_VehicleBrakeSystem.fromPartial(object.vehicle_brake_system)
      : undefined;
    message.vehicle_steering = (object.vehicle_steering !== undefined && object.vehicle_steering !== null)
      ? HostVehicleData_VehicleSteering.fromPartial(object.vehicle_steering)
      : undefined;
    message.vehicle_wheels = (object.vehicle_wheels !== undefined && object.vehicle_wheels !== null)
      ? HostVehicleData_VehicleWheels.fromPartial(object.vehicle_wheels)
      : undefined;
    message.vehicle_localization = (object.vehicle_localization !== undefined && object.vehicle_localization !== null)
      ? HostVehicleData_VehicleLocalization.fromPartial(object.vehicle_localization)
      : undefined;
    message.vehicle_automated_driving_function =
      object.vehicle_automated_driving_function?.map((e) =>
        HostVehicleData_VehicleAutomatedDrivingFunction.fromPartial(e)
      ) || [];
    message.vehicle_motion = (object.vehicle_motion !== undefined && object.vehicle_motion !== null)
      ? HostVehicleData_VehicleMotion.fromPartial(object.vehicle_motion)
      : undefined;
    message.route = (object.route !== undefined && object.route !== null) ? Route.fromPartial(object.route) : undefined;
    return message;
  },
};

function createBaseHostVehicleData_VehicleBasics(): HostVehicleData_VehicleBasics {
  return { curb_weight: 0, operating_state: 0 };
}

export const HostVehicleData_VehicleBasics: MessageFns<HostVehicleData_VehicleBasics> = {
  encode(message: HostVehicleData_VehicleBasics, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.curb_weight !== undefined && message.curb_weight !== 0) {
      writer.uint32(9).double(message.curb_weight);
    }
    if (message.operating_state !== undefined && message.operating_state !== 0) {
      writer.uint32(16).int32(message.operating_state);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HostVehicleData_VehicleBasics {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHostVehicleData_VehicleBasics();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 9) {
            break;
          }

          message.curb_weight = reader.double();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.operating_state = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HostVehicleData_VehicleBasics {
    return {
      curb_weight: isSet(object.curb_weight) ? globalThis.Number(object.curb_weight) : 0,
      operating_state: isSet(object.operating_state)
        ? hostVehicleData_VehicleBasics_OperatingStateFromJSON(object.operating_state)
        : 0,
    };
  },

  toJSON(message: HostVehicleData_VehicleBasics): unknown {
    const obj: any = {};
    if (message.curb_weight !== undefined) {
      obj.curb_weight = message.curb_weight;
    }
    if (message.operating_state !== undefined) {
      obj.operating_state = hostVehicleData_VehicleBasics_OperatingStateToJSON(message.operating_state);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<HostVehicleData_VehicleBasics>, I>>(base?: I): HostVehicleData_VehicleBasics {
    return HostVehicleData_VehicleBasics.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HostVehicleData_VehicleBasics>, I>>(
    object: I,
  ): HostVehicleData_VehicleBasics {
    const message = createBaseHostVehicleData_VehicleBasics();
    message.curb_weight = object.curb_weight ?? 0;
    message.operating_state = object.operating_state ?? 0;
    return message;
  },
};

function createBaseHostVehicleData_VehiclePowertrain(): HostVehicleData_VehiclePowertrain {
  return { pedal_position_acceleration: 0, pedal_position_clutch: 0, gear_transmission: 0, motor: [] };
}

export const HostVehicleData_VehiclePowertrain: MessageFns<HostVehicleData_VehiclePowertrain> = {
  encode(message: HostVehicleData_VehiclePowertrain, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.pedal_position_acceleration !== undefined && message.pedal_position_acceleration !== 0) {
      writer.uint32(9).double(message.pedal_position_acceleration);
    }
    if (message.pedal_position_clutch !== undefined && message.pedal_position_clutch !== 0) {
      writer.uint32(17).double(message.pedal_position_clutch);
    }
    if (message.gear_transmission !== undefined && message.gear_transmission !== 0) {
      writer.uint32(24).int32(message.gear_transmission);
    }
    for (const v of message.motor) {
      HostVehicleData_VehiclePowertrain_Motor.encode(v!, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HostVehicleData_VehiclePowertrain {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHostVehicleData_VehiclePowertrain();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 9) {
            break;
          }

          message.pedal_position_acceleration = reader.double();
          continue;
        }
        case 2: {
          if (tag !== 17) {
            break;
          }

          message.pedal_position_clutch = reader.double();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.gear_transmission = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.motor.push(HostVehicleData_VehiclePowertrain_Motor.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HostVehicleData_VehiclePowertrain {
    return {
      pedal_position_acceleration: isSet(object.pedal_position_acceleration)
        ? globalThis.Number(object.pedal_position_acceleration)
        : 0,
      pedal_position_clutch: isSet(object.pedal_position_clutch) ? globalThis.Number(object.pedal_position_clutch) : 0,
      gear_transmission: isSet(object.gear_transmission) ? globalThis.Number(object.gear_transmission) : 0,
      motor: globalThis.Array.isArray(object?.motor)
        ? object.motor.map((e: any) => HostVehicleData_VehiclePowertrain_Motor.fromJSON(e))
        : [],
    };
  },

  toJSON(message: HostVehicleData_VehiclePowertrain): unknown {
    const obj: any = {};
    if (message.pedal_position_acceleration !== undefined) {
      obj.pedal_position_acceleration = message.pedal_position_acceleration;
    }
    if (message.pedal_position_clutch !== undefined) {
      obj.pedal_position_clutch = message.pedal_position_clutch;
    }
    if (message.gear_transmission !== undefined) {
      obj.gear_transmission = Math.round(message.gear_transmission);
    }
    if (message.motor?.length) {
      obj.motor = message.motor.map((e) => HostVehicleData_VehiclePowertrain_Motor.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<HostVehicleData_VehiclePowertrain>, I>>(
    base?: I,
  ): HostVehicleData_VehiclePowertrain {
    return HostVehicleData_VehiclePowertrain.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HostVehicleData_VehiclePowertrain>, I>>(
    object: I,
  ): HostVehicleData_VehiclePowertrain {
    const message = createBaseHostVehicleData_VehiclePowertrain();
    message.pedal_position_acceleration = object.pedal_position_acceleration ?? 0;
    message.pedal_position_clutch = object.pedal_position_clutch ?? 0;
    message.gear_transmission = object.gear_transmission ?? 0;
    message.motor = object.motor?.map((e) => HostVehicleData_VehiclePowertrain_Motor.fromPartial(e)) || [];
    return message;
  },
};

function createBaseHostVehicleData_VehiclePowertrain_Motor(): HostVehicleData_VehiclePowertrain_Motor {
  return { type: 0, rpm: 0, torque: 0 };
}

export const HostVehicleData_VehiclePowertrain_Motor: MessageFns<HostVehicleData_VehiclePowertrain_Motor> = {
  encode(message: HostVehicleData_VehiclePowertrain_Motor, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.type !== undefined && message.type !== 0) {
      writer.uint32(8).int32(message.type);
    }
    if (message.rpm !== undefined && message.rpm !== 0) {
      writer.uint32(17).double(message.rpm);
    }
    if (message.torque !== undefined && message.torque !== 0) {
      writer.uint32(25).double(message.torque);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HostVehicleData_VehiclePowertrain_Motor {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHostVehicleData_VehiclePowertrain_Motor();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.type = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 17) {
            break;
          }

          message.rpm = reader.double();
          continue;
        }
        case 3: {
          if (tag !== 25) {
            break;
          }

          message.torque = reader.double();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HostVehicleData_VehiclePowertrain_Motor {
    return {
      type: isSet(object.type) ? hostVehicleData_VehiclePowertrain_Motor_TypeFromJSON(object.type) : 0,
      rpm: isSet(object.rpm) ? globalThis.Number(object.rpm) : 0,
      torque: isSet(object.torque) ? globalThis.Number(object.torque) : 0,
    };
  },

  toJSON(message: HostVehicleData_VehiclePowertrain_Motor): unknown {
    const obj: any = {};
    if (message.type !== undefined) {
      obj.type = hostVehicleData_VehiclePowertrain_Motor_TypeToJSON(message.type);
    }
    if (message.rpm !== undefined) {
      obj.rpm = message.rpm;
    }
    if (message.torque !== undefined) {
      obj.torque = message.torque;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<HostVehicleData_VehiclePowertrain_Motor>, I>>(
    base?: I,
  ): HostVehicleData_VehiclePowertrain_Motor {
    return HostVehicleData_VehiclePowertrain_Motor.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HostVehicleData_VehiclePowertrain_Motor>, I>>(
    object: I,
  ): HostVehicleData_VehiclePowertrain_Motor {
    const message = createBaseHostVehicleData_VehiclePowertrain_Motor();
    message.type = object.type ?? 0;
    message.rpm = object.rpm ?? 0;
    message.torque = object.torque ?? 0;
    return message;
  },
};

function createBaseHostVehicleData_VehicleBrakeSystem(): HostVehicleData_VehicleBrakeSystem {
  return { pedal_position_brake: 0 };
}

export const HostVehicleData_VehicleBrakeSystem: MessageFns<HostVehicleData_VehicleBrakeSystem> = {
  encode(message: HostVehicleData_VehicleBrakeSystem, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.pedal_position_brake !== undefined && message.pedal_position_brake !== 0) {
      writer.uint32(9).double(message.pedal_position_brake);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HostVehicleData_VehicleBrakeSystem {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHostVehicleData_VehicleBrakeSystem();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 9) {
            break;
          }

          message.pedal_position_brake = reader.double();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HostVehicleData_VehicleBrakeSystem {
    return {
      pedal_position_brake: isSet(object.pedal_position_brake) ? globalThis.Number(object.pedal_position_brake) : 0,
    };
  },

  toJSON(message: HostVehicleData_VehicleBrakeSystem): unknown {
    const obj: any = {};
    if (message.pedal_position_brake !== undefined) {
      obj.pedal_position_brake = message.pedal_position_brake;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<HostVehicleData_VehicleBrakeSystem>, I>>(
    base?: I,
  ): HostVehicleData_VehicleBrakeSystem {
    return HostVehicleData_VehicleBrakeSystem.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HostVehicleData_VehicleBrakeSystem>, I>>(
    object: I,
  ): HostVehicleData_VehicleBrakeSystem {
    const message = createBaseHostVehicleData_VehicleBrakeSystem();
    message.pedal_position_brake = object.pedal_position_brake ?? 0;
    return message;
  },
};

function createBaseHostVehicleData_VehicleSteering(): HostVehicleData_VehicleSteering {
  return { vehicle_steering_wheel: undefined };
}

export const HostVehicleData_VehicleSteering: MessageFns<HostVehicleData_VehicleSteering> = {
  encode(message: HostVehicleData_VehicleSteering, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.vehicle_steering_wheel !== undefined) {
      VehicleSteeringWheel.encode(message.vehicle_steering_wheel, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HostVehicleData_VehicleSteering {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHostVehicleData_VehicleSteering();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.vehicle_steering_wheel = VehicleSteeringWheel.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HostVehicleData_VehicleSteering {
    return {
      vehicle_steering_wheel: isSet(object.vehicle_steering_wheel)
        ? VehicleSteeringWheel.fromJSON(object.vehicle_steering_wheel)
        : undefined,
    };
  },

  toJSON(message: HostVehicleData_VehicleSteering): unknown {
    const obj: any = {};
    if (message.vehicle_steering_wheel !== undefined) {
      obj.vehicle_steering_wheel = VehicleSteeringWheel.toJSON(message.vehicle_steering_wheel);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<HostVehicleData_VehicleSteering>, I>>(base?: I): HostVehicleData_VehicleSteering {
    return HostVehicleData_VehicleSteering.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HostVehicleData_VehicleSteering>, I>>(
    object: I,
  ): HostVehicleData_VehicleSteering {
    const message = createBaseHostVehicleData_VehicleSteering();
    message.vehicle_steering_wheel =
      (object.vehicle_steering_wheel !== undefined && object.vehicle_steering_wheel !== null)
        ? VehicleSteeringWheel.fromPartial(object.vehicle_steering_wheel)
        : undefined;
    return message;
  },
};

function createBaseHostVehicleData_VehicleWheels(): HostVehicleData_VehicleWheels {
  return { wheel_data: [] };
}

export const HostVehicleData_VehicleWheels: MessageFns<HostVehicleData_VehicleWheels> = {
  encode(message: HostVehicleData_VehicleWheels, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.wheel_data) {
      HostVehicleData_VehicleWheels_WheelData.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HostVehicleData_VehicleWheels {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHostVehicleData_VehicleWheels();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.wheel_data.push(HostVehicleData_VehicleWheels_WheelData.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HostVehicleData_VehicleWheels {
    return {
      wheel_data: globalThis.Array.isArray(object?.wheel_data)
        ? object.wheel_data.map((e: any) => HostVehicleData_VehicleWheels_WheelData.fromJSON(e))
        : [],
    };
  },

  toJSON(message: HostVehicleData_VehicleWheels): unknown {
    const obj: any = {};
    if (message.wheel_data?.length) {
      obj.wheel_data = message.wheel_data.map((e) => HostVehicleData_VehicleWheels_WheelData.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<HostVehicleData_VehicleWheels>, I>>(base?: I): HostVehicleData_VehicleWheels {
    return HostVehicleData_VehicleWheels.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HostVehicleData_VehicleWheels>, I>>(
    object: I,
  ): HostVehicleData_VehicleWheels {
    const message = createBaseHostVehicleData_VehicleWheels();
    message.wheel_data = object.wheel_data?.map((e) => HostVehicleData_VehicleWheels_WheelData.fromPartial(e)) || [];
    return message;
  },
};

function createBaseHostVehicleData_VehicleWheels_WheelData(): HostVehicleData_VehicleWheels_WheelData {
  return { axle: 0, index: 0, rotation_rate: 0, slip: 0 };
}

export const HostVehicleData_VehicleWheels_WheelData: MessageFns<HostVehicleData_VehicleWheels_WheelData> = {
  encode(message: HostVehicleData_VehicleWheels_WheelData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.axle !== undefined && message.axle !== 0) {
      writer.uint32(8).uint32(message.axle);
    }
    if (message.index !== undefined && message.index !== 0) {
      writer.uint32(16).uint32(message.index);
    }
    if (message.rotation_rate !== undefined && message.rotation_rate !== 0) {
      writer.uint32(25).double(message.rotation_rate);
    }
    if (message.slip !== undefined && message.slip !== 0) {
      writer.uint32(33).double(message.slip);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HostVehicleData_VehicleWheels_WheelData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHostVehicleData_VehicleWheels_WheelData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.axle = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.index = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 25) {
            break;
          }

          message.rotation_rate = reader.double();
          continue;
        }
        case 4: {
          if (tag !== 33) {
            break;
          }

          message.slip = reader.double();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HostVehicleData_VehicleWheels_WheelData {
    return {
      axle: isSet(object.axle) ? globalThis.Number(object.axle) : 0,
      index: isSet(object.index) ? globalThis.Number(object.index) : 0,
      rotation_rate: isSet(object.rotation_rate) ? globalThis.Number(object.rotation_rate) : 0,
      slip: isSet(object.slip) ? globalThis.Number(object.slip) : 0,
    };
  },

  toJSON(message: HostVehicleData_VehicleWheels_WheelData): unknown {
    const obj: any = {};
    if (message.axle !== undefined) {
      obj.axle = Math.round(message.axle);
    }
    if (message.index !== undefined) {
      obj.index = Math.round(message.index);
    }
    if (message.rotation_rate !== undefined) {
      obj.rotation_rate = message.rotation_rate;
    }
    if (message.slip !== undefined) {
      obj.slip = message.slip;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<HostVehicleData_VehicleWheels_WheelData>, I>>(
    base?: I,
  ): HostVehicleData_VehicleWheels_WheelData {
    return HostVehicleData_VehicleWheels_WheelData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HostVehicleData_VehicleWheels_WheelData>, I>>(
    object: I,
  ): HostVehicleData_VehicleWheels_WheelData {
    const message = createBaseHostVehicleData_VehicleWheels_WheelData();
    message.axle = object.axle ?? 0;
    message.index = object.index ?? 0;
    message.rotation_rate = object.rotation_rate ?? 0;
    message.slip = object.slip ?? 0;
    return message;
  },
};

function createBaseHostVehicleData_VehicleLocalization(): HostVehicleData_VehicleLocalization {
  return { position: undefined, orientation: undefined, geodetic_position: undefined };
}

export const HostVehicleData_VehicleLocalization: MessageFns<HostVehicleData_VehicleLocalization> = {
  encode(message: HostVehicleData_VehicleLocalization, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.position !== undefined) {
      Vector3d.encode(message.position, writer.uint32(10).fork()).join();
    }
    if (message.orientation !== undefined) {
      Orientation3d.encode(message.orientation, writer.uint32(18).fork()).join();
    }
    if (message.geodetic_position !== undefined) {
      GeodeticPosition.encode(message.geodetic_position, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HostVehicleData_VehicleLocalization {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHostVehicleData_VehicleLocalization();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.position = Vector3d.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.orientation = Orientation3d.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.geodetic_position = GeodeticPosition.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HostVehicleData_VehicleLocalization {
    return {
      position: isSet(object.position) ? Vector3d.fromJSON(object.position) : undefined,
      orientation: isSet(object.orientation) ? Orientation3d.fromJSON(object.orientation) : undefined,
      geodetic_position: isSet(object.geodetic_position)
        ? GeodeticPosition.fromJSON(object.geodetic_position)
        : undefined,
    };
  },

  toJSON(message: HostVehicleData_VehicleLocalization): unknown {
    const obj: any = {};
    if (message.position !== undefined) {
      obj.position = Vector3d.toJSON(message.position);
    }
    if (message.orientation !== undefined) {
      obj.orientation = Orientation3d.toJSON(message.orientation);
    }
    if (message.geodetic_position !== undefined) {
      obj.geodetic_position = GeodeticPosition.toJSON(message.geodetic_position);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<HostVehicleData_VehicleLocalization>, I>>(
    base?: I,
  ): HostVehicleData_VehicleLocalization {
    return HostVehicleData_VehicleLocalization.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HostVehicleData_VehicleLocalization>, I>>(
    object: I,
  ): HostVehicleData_VehicleLocalization {
    const message = createBaseHostVehicleData_VehicleLocalization();
    message.position = (object.position !== undefined && object.position !== null)
      ? Vector3d.fromPartial(object.position)
      : undefined;
    message.orientation = (object.orientation !== undefined && object.orientation !== null)
      ? Orientation3d.fromPartial(object.orientation)
      : undefined;
    message.geodetic_position = (object.geodetic_position !== undefined && object.geodetic_position !== null)
      ? GeodeticPosition.fromPartial(object.geodetic_position)
      : undefined;
    return message;
  },
};

function createBaseHostVehicleData_VehicleMotion(): HostVehicleData_VehicleMotion {
  return {
    position: undefined,
    orientation: undefined,
    velocity: undefined,
    orientation_rate: undefined,
    acceleration: undefined,
    current_curvature: 0,
  };
}

export const HostVehicleData_VehicleMotion: MessageFns<HostVehicleData_VehicleMotion> = {
  encode(message: HostVehicleData_VehicleMotion, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.position !== undefined) {
      Vector3d.encode(message.position, writer.uint32(10).fork()).join();
    }
    if (message.orientation !== undefined) {
      Orientation3d.encode(message.orientation, writer.uint32(18).fork()).join();
    }
    if (message.velocity !== undefined) {
      Vector3d.encode(message.velocity, writer.uint32(26).fork()).join();
    }
    if (message.orientation_rate !== undefined) {
      Orientation3d.encode(message.orientation_rate, writer.uint32(34).fork()).join();
    }
    if (message.acceleration !== undefined) {
      Vector3d.encode(message.acceleration, writer.uint32(42).fork()).join();
    }
    if (message.current_curvature !== undefined && message.current_curvature !== 0) {
      writer.uint32(49).double(message.current_curvature);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HostVehicleData_VehicleMotion {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHostVehicleData_VehicleMotion();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.position = Vector3d.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.orientation = Orientation3d.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.velocity = Vector3d.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.orientation_rate = Orientation3d.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.acceleration = Vector3d.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 49) {
            break;
          }

          message.current_curvature = reader.double();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HostVehicleData_VehicleMotion {
    return {
      position: isSet(object.position) ? Vector3d.fromJSON(object.position) : undefined,
      orientation: isSet(object.orientation) ? Orientation3d.fromJSON(object.orientation) : undefined,
      velocity: isSet(object.velocity) ? Vector3d.fromJSON(object.velocity) : undefined,
      orientation_rate: isSet(object.orientation_rate) ? Orientation3d.fromJSON(object.orientation_rate) : undefined,
      acceleration: isSet(object.acceleration) ? Vector3d.fromJSON(object.acceleration) : undefined,
      current_curvature: isSet(object.current_curvature) ? globalThis.Number(object.current_curvature) : 0,
    };
  },

  toJSON(message: HostVehicleData_VehicleMotion): unknown {
    const obj: any = {};
    if (message.position !== undefined) {
      obj.position = Vector3d.toJSON(message.position);
    }
    if (message.orientation !== undefined) {
      obj.orientation = Orientation3d.toJSON(message.orientation);
    }
    if (message.velocity !== undefined) {
      obj.velocity = Vector3d.toJSON(message.velocity);
    }
    if (message.orientation_rate !== undefined) {
      obj.orientation_rate = Orientation3d.toJSON(message.orientation_rate);
    }
    if (message.acceleration !== undefined) {
      obj.acceleration = Vector3d.toJSON(message.acceleration);
    }
    if (message.current_curvature !== undefined) {
      obj.current_curvature = message.current_curvature;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<HostVehicleData_VehicleMotion>, I>>(base?: I): HostVehicleData_VehicleMotion {
    return HostVehicleData_VehicleMotion.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HostVehicleData_VehicleMotion>, I>>(
    object: I,
  ): HostVehicleData_VehicleMotion {
    const message = createBaseHostVehicleData_VehicleMotion();
    message.position = (object.position !== undefined && object.position !== null)
      ? Vector3d.fromPartial(object.position)
      : undefined;
    message.orientation = (object.orientation !== undefined && object.orientation !== null)
      ? Orientation3d.fromPartial(object.orientation)
      : undefined;
    message.velocity = (object.velocity !== undefined && object.velocity !== null)
      ? Vector3d.fromPartial(object.velocity)
      : undefined;
    message.orientation_rate = (object.orientation_rate !== undefined && object.orientation_rate !== null)
      ? Orientation3d.fromPartial(object.orientation_rate)
      : undefined;
    message.acceleration = (object.acceleration !== undefined && object.acceleration !== null)
      ? Vector3d.fromPartial(object.acceleration)
      : undefined;
    message.current_curvature = object.current_curvature ?? 0;
    return message;
  },
};

function createBaseHostVehicleData_VehicleAutomatedDrivingFunction(): HostVehicleData_VehicleAutomatedDrivingFunction {
  return { name: 0, custom_name: "", state: 0, custom_state: "", driver_override: undefined, custom_detail: [] };
}

export const HostVehicleData_VehicleAutomatedDrivingFunction: MessageFns<
  HostVehicleData_VehicleAutomatedDrivingFunction
> = {
  encode(
    message: HostVehicleData_VehicleAutomatedDrivingFunction,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.name !== undefined && message.name !== 0) {
      writer.uint32(8).int32(message.name);
    }
    if (message.custom_name !== undefined && message.custom_name !== "") {
      writer.uint32(18).string(message.custom_name);
    }
    if (message.state !== undefined && message.state !== 0) {
      writer.uint32(24).int32(message.state);
    }
    if (message.custom_state !== undefined && message.custom_state !== "") {
      writer.uint32(34).string(message.custom_state);
    }
    if (message.driver_override !== undefined) {
      HostVehicleData_VehicleAutomatedDrivingFunction_DriverOverride.encode(
        message.driver_override,
        writer.uint32(42).fork(),
      ).join();
    }
    for (const v of message.custom_detail) {
      KeyValuePair.encode(v!, writer.uint32(50).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HostVehicleData_VehicleAutomatedDrivingFunction {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHostVehicleData_VehicleAutomatedDrivingFunction();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.name = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.custom_name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.state = reader.int32() as any;
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.custom_state = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.driver_override = HostVehicleData_VehicleAutomatedDrivingFunction_DriverOverride.decode(
            reader,
            reader.uint32(),
          );
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.custom_detail.push(KeyValuePair.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HostVehicleData_VehicleAutomatedDrivingFunction {
    return {
      name: isSet(object.name) ? hostVehicleData_VehicleAutomatedDrivingFunction_NameFromJSON(object.name) : 0,
      custom_name: isSet(object.custom_name) ? globalThis.String(object.custom_name) : "",
      state: isSet(object.state) ? hostVehicleData_VehicleAutomatedDrivingFunction_StateFromJSON(object.state) : 0,
      custom_state: isSet(object.custom_state) ? globalThis.String(object.custom_state) : "",
      driver_override: isSet(object.driver_override)
        ? HostVehicleData_VehicleAutomatedDrivingFunction_DriverOverride.fromJSON(object.driver_override)
        : undefined,
      custom_detail: globalThis.Array.isArray(object?.custom_detail)
        ? object.custom_detail.map((e: any) => KeyValuePair.fromJSON(e))
        : [],
    };
  },

  toJSON(message: HostVehicleData_VehicleAutomatedDrivingFunction): unknown {
    const obj: any = {};
    if (message.name !== undefined) {
      obj.name = hostVehicleData_VehicleAutomatedDrivingFunction_NameToJSON(message.name);
    }
    if (message.custom_name !== undefined) {
      obj.custom_name = message.custom_name;
    }
    if (message.state !== undefined) {
      obj.state = hostVehicleData_VehicleAutomatedDrivingFunction_StateToJSON(message.state);
    }
    if (message.custom_state !== undefined) {
      obj.custom_state = message.custom_state;
    }
    if (message.driver_override !== undefined) {
      obj.driver_override = HostVehicleData_VehicleAutomatedDrivingFunction_DriverOverride.toJSON(
        message.driver_override,
      );
    }
    if (message.custom_detail?.length) {
      obj.custom_detail = message.custom_detail.map((e) => KeyValuePair.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<HostVehicleData_VehicleAutomatedDrivingFunction>, I>>(
    base?: I,
  ): HostVehicleData_VehicleAutomatedDrivingFunction {
    return HostVehicleData_VehicleAutomatedDrivingFunction.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HostVehicleData_VehicleAutomatedDrivingFunction>, I>>(
    object: I,
  ): HostVehicleData_VehicleAutomatedDrivingFunction {
    const message = createBaseHostVehicleData_VehicleAutomatedDrivingFunction();
    message.name = object.name ?? 0;
    message.custom_name = object.custom_name ?? "";
    message.state = object.state ?? 0;
    message.custom_state = object.custom_state ?? "";
    message.driver_override = (object.driver_override !== undefined && object.driver_override !== null)
      ? HostVehicleData_VehicleAutomatedDrivingFunction_DriverOverride.fromPartial(object.driver_override)
      : undefined;
    message.custom_detail = object.custom_detail?.map((e) => KeyValuePair.fromPartial(e)) || [];
    return message;
  },
};

function createBaseHostVehicleData_VehicleAutomatedDrivingFunction_DriverOverride(): HostVehicleData_VehicleAutomatedDrivingFunction_DriverOverride {
  return { active: false, override_reason: [] };
}

export const HostVehicleData_VehicleAutomatedDrivingFunction_DriverOverride: MessageFns<
  HostVehicleData_VehicleAutomatedDrivingFunction_DriverOverride
> = {
  encode(
    message: HostVehicleData_VehicleAutomatedDrivingFunction_DriverOverride,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.active !== undefined && message.active !== false) {
      writer.uint32(8).bool(message.active);
    }
    writer.uint32(18).fork();
    for (const v of message.override_reason) {
      writer.int32(v);
    }
    writer.join();
    return writer;
  },

  decode(
    input: BinaryReader | Uint8Array,
    length?: number,
  ): HostVehicleData_VehicleAutomatedDrivingFunction_DriverOverride {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHostVehicleData_VehicleAutomatedDrivingFunction_DriverOverride();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.active = reader.bool();
          continue;
        }
        case 2: {
          if (tag === 16) {
            message.override_reason.push(reader.int32() as any);

            continue;
          }

          if (tag === 18) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.override_reason.push(reader.int32() as any);
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HostVehicleData_VehicleAutomatedDrivingFunction_DriverOverride {
    return {
      active: isSet(object.active) ? globalThis.Boolean(object.active) : false,
      override_reason: globalThis.Array.isArray(object?.override_reason)
        ? object.override_reason.map((e: any) =>
          hostVehicleData_VehicleAutomatedDrivingFunction_DriverOverride_ReasonFromJSON(e)
        )
        : [],
    };
  },

  toJSON(message: HostVehicleData_VehicleAutomatedDrivingFunction_DriverOverride): unknown {
    const obj: any = {};
    if (message.active !== undefined) {
      obj.active = message.active;
    }
    if (message.override_reason?.length) {
      obj.override_reason = message.override_reason.map((e) =>
        hostVehicleData_VehicleAutomatedDrivingFunction_DriverOverride_ReasonToJSON(e)
      );
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<HostVehicleData_VehicleAutomatedDrivingFunction_DriverOverride>, I>>(
    base?: I,
  ): HostVehicleData_VehicleAutomatedDrivingFunction_DriverOverride {
    return HostVehicleData_VehicleAutomatedDrivingFunction_DriverOverride.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HostVehicleData_VehicleAutomatedDrivingFunction_DriverOverride>, I>>(
    object: I,
  ): HostVehicleData_VehicleAutomatedDrivingFunction_DriverOverride {
    const message = createBaseHostVehicleData_VehicleAutomatedDrivingFunction_DriverOverride();
    message.active = object.active ?? false;
    message.override_reason = object.override_reason?.map((e) => e) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
