// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: osi_version.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

/**
 * \brief The interface version number.
 *
 * The field denoting the version number. This needs to be set by the
 * sender to the actual OSI version that is to be sent.  Code wanting to
 * access the version number of the OSI code base can access a FileOptions,
 * which has the proper values, like this:
 *
 * \code
 * auto currentInterfaceVersion =
 *   InterfaceVersion::descriptor()->file()->options().GetExtension(current_interface_version);
 * \endcode
 *
 * If a message with all components set to the default value 0 is
 * received, this indicates that either that the message was sent by
 * a version 2.2.0 or earlier release, or that the sender did not
 * properly set the version components prior to sending.
 *
 * Increments will happen as part of changes to the whole interface.
 * The meaning of different InterfaceVersions is defined in the versioning chapter of the official OSI documentation.
 */
export interface InterfaceVersion {
  /** Major version number. */
  version_major?:
    | number
    | undefined;
  /** Minor version number. */
  version_minor?:
    | number
    | undefined;
  /** Patch version number. */
  version_patch?: number | undefined;
}

function createBaseInterfaceVersion(): InterfaceVersion {
  return { version_major: 0, version_minor: 0, version_patch: 0 };
}

export const InterfaceVersion: MessageFns<InterfaceVersion> = {
  encode(message: InterfaceVersion, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.version_major !== undefined && message.version_major !== 0) {
      writer.uint32(8).uint32(message.version_major);
    }
    if (message.version_minor !== undefined && message.version_minor !== 0) {
      writer.uint32(16).uint32(message.version_minor);
    }
    if (message.version_patch !== undefined && message.version_patch !== 0) {
      writer.uint32(24).uint32(message.version_patch);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): InterfaceVersion {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseInterfaceVersion();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.version_major = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.version_minor = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.version_patch = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): InterfaceVersion {
    return {
      version_major: isSet(object.version_major) ? globalThis.Number(object.version_major) : 0,
      version_minor: isSet(object.version_minor) ? globalThis.Number(object.version_minor) : 0,
      version_patch: isSet(object.version_patch) ? globalThis.Number(object.version_patch) : 0,
    };
  },

  toJSON(message: InterfaceVersion): unknown {
    const obj: any = {};
    if (message.version_major !== undefined) {
      obj.version_major = Math.round(message.version_major);
    }
    if (message.version_minor !== undefined) {
      obj.version_minor = Math.round(message.version_minor);
    }
    if (message.version_patch !== undefined) {
      obj.version_patch = Math.round(message.version_patch);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<InterfaceVersion>, I>>(base?: I): InterfaceVersion {
    return InterfaceVersion.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<InterfaceVersion>, I>>(object: I): InterfaceVersion {
    const message = createBaseInterfaceVersion();
    message.version_major = object.version_major ?? 0;
    message.version_minor = object.version_minor ?? 0;
    message.version_patch = object.version_patch ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
