import { mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { spawnSync } from "node:child_process";

const repoRoot = process.cwd();
const protoRoot = resolve(repoRoot, "open-simulation-interface");
const generatedDir = resolve(repoRoot, "generated");
const descriptorDefinitionsDir = resolve(repoRoot, "generated/type-descriptors");

type DescriptorTarget = {
  proto: string;
  pb: string;
  constName: string;
};

const descriptorTargets: DescriptorTarget[] = [
  {
    proto: "osi_groundtruth.proto",
    pb: "osi3_groundtruth_descriptor.pb",
    constName: "osi3GroundTruthDescriptor",
  },
  {
    proto: "osi_sensorview.proto",
    pb: "osi3_sensorview_descriptor.pb",
    constName: "osi3SensorViewDescriptor",
  },
  {
    proto: "osi_sensordata.proto",
    pb: "osi3_sensordata_descriptor.pb",
    constName: "osi3SensorDataDescriptor",
  },
];

function runProtoc(protoPath: string, outputPath: string): void {
  const result = spawnSync(
    "protoc",
    ["-I", protoRoot, "--include_imports", `--descriptor_set_out=${outputPath}`, protoPath],
    { cwd: repoRoot, stdio: "inherit" }
  );

  if (result.error != null) {
    throw result.error;
  }

  if (result.status !== 0) {
    throw new Error(`protoc failed with exit code ${result.status}`);
  }
}

function toUint8ArrayTs(constName: string, bytes: Buffer): string {
  const lines: string[] = [];
  lines.push("// Generated by scripts/generate-schema-definitions.ts. Do not edit manually.");
  lines.push(`export const ${constName} = new Uint8Array([`);
  for (let i = 0; i < bytes.length; i += 16) {
    const chunk = bytes.subarray(i, Math.min(i + 16, bytes.length));
    lines.push(`  ${Array.from(chunk).join(", ")},`);
  }
  lines.push("]);");
  lines.push("");
  return lines.join("\n");
}

function main(): void {
  mkdirSync(generatedDir, { recursive: true });
  mkdirSync(descriptorDefinitionsDir, { recursive: true });

  for (const target of descriptorTargets) {
    runProtoc(join(protoRoot, target.proto), join(generatedDir, target.pb));
  }

  for (const target of descriptorTargets) {
    const descriptorBytes = readFileSync(join(generatedDir, target.pb));
    const outputPath = join(descriptorDefinitionsDir, target.pb.replace(/\.pb$/, ".ts"));
    writeFileSync(outputPath, toUint8ArrayTs(target.constName, descriptorBytes), "utf8");
    rmSync(join(generatedDir, target.pb), { force: true });
  }
}

main();
