import { existsSync, readdirSync, writeFileSync } from "node:fs";
import { extname, resolve } from "node:path";

function toExportLines(directoryPath: string, exportPrefix: string): string[] {
  if (!existsSync(directoryPath)) {
    return [];
  }

  return readdirSync(directoryPath, { withFileTypes: true })
    .filter((entry) => entry.isFile() && extname(entry.name) === ".ts")
    .map((entry) => entry.name.replace(/\.ts$/, ""))
    .sort((a, b) => a.localeCompare(b))
    .map((moduleName) => `export * from "${exportPrefix}/${moduleName}";`);
}

function main(): void {
  const repoRoot = process.cwd();
  const outputPath = resolve(repoRoot, "index.ts");
  const typesPath = resolve(repoRoot, "generated/types");
  const descriptorsPath = resolve(repoRoot, "generated/type-descriptors");

  const typeExports = toExportLines(typesPath, "./generated/types");
  const descriptorExports = toExportLines(descriptorsPath, "./generated/type-descriptors");

  const outputLines: string[] = [];
  outputLines.push("// Generated by scripts/generate-index.ts. Do not edit manually.");
  outputLines.push(...typeExports);

  if (descriptorExports.length > 0) {
    outputLines.push(...descriptorExports);
  }

  writeFileSync(outputPath, `${outputLines.join("\n")}\n`, "utf8");
}

main();
